// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: openshift_images/configuring-samples-operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring the Cluster Samples Operator\n---\n\n# Configuring the Cluster Samples Operator {#configuring-samples-operator}\n\nYou can configure the Cluster Samples Operator to manage the installation and updates of {{ op_system_base_full }}-based OpenShift Container Platform image streams and templates in the `openshift` namespace.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
