// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: openshift_images/create-images.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating images\n---\n\n# Creating images {#creating-images}\n\nYou can create your own container images based on pre-built base images. This process includes following best practices for writing images, defining metadata, testing images, and using a custom builder workflow with Source-to-Image (S2I). After you create an image, you can push it to the {{ product_registry }}.\n\n## Additional resources {#additional-resources_create-images}\n\n- [S2I README](https://github.com/openshift/source-to-image/blob/master/README.md#installation)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
