// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: openshift_images/image-streams-manage.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Managing image streams\n---\n\n# Managing image streams {#managing-image-streams}\n\nTo create and update container images and track version changes in OpenShift Container Platform, you can use image streams and tags. Add, update, remove, and import image stream tags to manage your container images.\n\n## Additional resources {#additional-resources-remove-tag_image-streams-managing}\n\n- [Removing deprecated image stream tags from the Cluster Samples Operator](/openshift-docs-markdown/openshift_images/configuring-samples-operator#images-samples-operator-deprecated-image-stream_configuring-samples-operator)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
