// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: openshift_images/image-configuration.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Image configuration resources\n---\n\n# Image configuration resources {#image-configuration-classic}\n\nYou can configure an image registry to store and serve container images.\n\n## Additional resources {#additional-resources_image-configuration}\n\n- [Working with manifest lists](/openshift_images/image-streams-manage#images-imagestream-import-import-mode_image-streams-managing)\n- [Understanding feature gates](/nodes/clusters/nodes-cluster-enabling-features#nodes-cluster-enabling-features-about_nodes-cluster-enabling)\n- [Updating the global cluster pull secret](/openshift_images/managing_images/using-image-pull-secrets#images-update-global-pull-secret_using-image-pull-secrets)\n- [Configuring project-scoped image pull secrets for mirrored registries](/openshift_images/image-configuration#images-configuration-registry-mirror-project-secret_image-configuration)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
