// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: openshift_images/samples-operator-alt-registry.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using the Cluster Samples Operator with an alternate registry\n---\n\n# Using the Cluster Samples Operator with an alternate registry {#samples-operator-alt-registry}\n\nYou can use the Cluster Samples Operator with an alternate registry by preparing a mirror host and creating a mirror registry.\n\n## Additional resources {#additional-resources_samples-operator-alt-registry}\n\n- [Viewing the image pull source](/installing/validation_and_troubleshooting/validating-an-installation#viewing-the-image-pull-source_validating-an-installation)\n- [Using Cluster Samples Operator image streams with alternate or mirrored registries](/openshift_images/samples-operator-alt-registry#installation-restricted-network-samples_samples-operator-alt-registry)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
