// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/multiple_networks/primary_networks/about-primary-nwt-nad.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating primary networks using a NetworkAttachmentDefinition\n---\n\n# Creating primary networks using a NetworkAttachmentDefinition {#about-primary-nwt-nad}\n\nUse the `NetworkAttachmentDefinition` (NAD) resource to create primary networks when you need to use CNI plugins other than OVN-Kubernetes, such as IPVLAN or MACVLAN, or when you require direct control over the Container Network Interface (CNI) configuration for advanced networking scenarios.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
