// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: edge_computing/image_based_upgrade/preparing_for_image_based_upgrade/cnf-image-based-upgrade-shared-container-partition.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring a shared container partition for the image-based upgrade\n---\n\n# Configuring a shared container partition for the image-based upgrade {#cnf-image-based-upgrade-shared-container-partition}\n\nYour {{ sno }} clusters need to have a shared `/var/lib/containers` partition for the image-based upgrade. You can do this at install time.\n\n**Additional resources**\n\n- [Installing Butane](/installing/install_config/installing-customizing#installation-special-config-butane-install_installing-customizing)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
