// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: edge_computing/image_based_upgrade/preparing_for_image_based_upgrade/cnf-image-based-upgrade-generate-seed.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Generating a seed image for the image-based upgrade with the {{ lcao }}\n---\n\n# Generating a seed image for the image-based upgrade with the {{ lcao }} {#cnf-image-based-upgrade-generate-seed-image}\n\nUse the {{ lcao }} to generate the seed image with the `SeedGenerator` custom resource (CR).\n\n**Additional resources**\n\n- [Configuring a shared container partition between ostree stateroots](/openshift-docs-markdown/edge_computing/image_based_upgrade/preparing_for_image_based_upgrade/cnf-image-based-upgrade-shared-container-partition#cnf-image-based-upgrade-shared-container-partition_shared-container-partition)\n- [Configuring a shared container partition between ostree stateroots when using {{ ztp }}](/openshift-docs-markdown/edge_computing/image_based_upgrade/preparing_for_image_based_upgrade/cnf-image-based-upgrade-shared-container-partition#ztp-image-based-upgrade-shared-container-partition_shared-container-partition)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
