// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/file_integrity_operator/file-integrity-operator-understanding.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Understanding the File Integrity Operator\n---\n\n# Understanding the File Integrity Operator {#understanding-file-integrity-operator}\n\nThe File Integrity Operator is an OpenShift Container Platform Operator that continually runs file integrity checks on the cluster nodes. It deploys a daemon set that initializes and runs privileged advanced intrusion detection environment (AIDE) containers on each node, providing a status object with a log of files that are modified during the initial run of the daemon set pods.\n\n> [!IMPORTANT]\n> Currently, only {{ op_system_first }} nodes are supported.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
