// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/multiple_networks/about-virtual-routing-and-forwarding.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Virtual routing and forwarding\n---\n\n# Virtual routing and forwarding {#virtual-routing-and-forwarding}\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
