// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/advanced_networking/route_advertisements/example-route-advertisement-setup.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Example route advertisements setup\n---\n\n# Example route advertisements setup {#example-route-advertisements-setup}\n\nTo learn how to implement a route reflection setup on bare-metal infrastructure, you can follow this sample configuration. This example demonstrates how to enable the necessary feature gates and configure objects to advertise pod and egress IP routes.\n\nAs a cluster administrator, you can configure the following example route advertisements setup for your cluster. This configuration is intended as a sample that demonstrates how to configure route advertisements.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
