// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: edge_computing/ztp-deploying-far-edge-clusters-at-scale.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Challenges of the network far edge\n---\n\n# Challenges of the network far edge {#ztp-deploying-far-edge-clusters-at-scale}\n\nEdge computing presents complex challenges when managing many sites in geographically displaced locations. Use {{ ztp_first }} to provision and manage sites at the far edge of the network.\n\n**Additional resources**\n\n- [Configuring managed cluster policies by using PolicyGenerator resources](/openshift-docs-markdown/edge_computing/policygenerator_for_ztp/ztp-configuring-managed-clusters-policygenerator#ztp-configuring-managed-clusters-policygenerator)\n- [Comparing {{ rh_rhacm }} PolicyGenerator and PolicyGenTemplate resource patching](/openshift-docs-markdown/edge_computing/policygenerator_for_ztp/ztp-configuring-managed-clusters-policygenerator#ztp-comparing-pgt-and-rhacm-pg-patching-strategies_ztp-configuring-managed-clusters-policygenerator)\n- [Preparing the {{ ztp }} Git repository](/openshift-docs-markdown/edge_computing/ztp-preparing-the-hub-cluster#ztp-preparing-the-ztp-git-repository_ztp-preparing-the-hub-cluster)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
