// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/networking_operators/metallb-operator/metallb-upgrading-operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Upgrading the MetalLB Operator\n---\n\n# Upgrading the MetalLB Operator {#metallb-upgrading-operator}\n\nThe `Subscription` custom resource (CR) for the MetalLB Operator is used to manage whether the Operator is upgraded automatically or manually.\n\nBy default, the `Subscription` CR assigns the namespace to `metallb-system` and automatically sets the `installPlanApproval` parameter to `Automatic`. This means that when Red Hat-provided Operator catalogs include a newer version of the MetalLB Operator, the MetalLB Operator is automatically upgraded.\n\nIf you need to manually control upgrading the MetalLB Operator, set the `installPlanApproval` parameter to `Manual`.\n\n## Additional resources {#additional-resources}\n\n- [Introduction to OpenShift updates](/openshift-docs-markdown/updating/understanding_updates/intro-to-updates#intro-to-updates_intro-to-updates)\n- [Installing the MetalLB Operator](/openshift-docs-markdown/networking/networking_operators/metallb-operator/metallb-operator-install#metallb-operator-install)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
