// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: storage/persistent_storage/persistent-storage-fibre.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Persistent storage using Fibre Channel\n---\n\n# Persistent storage using Fibre Channel {#persistent-storage-using-fibre}\n\nYou can provision your OpenShift Container Platform cluster with persistent storage by using Fibre Channel volumes for workloads that require high-speed, reliable block-level storage.\n\n> [!IMPORTANT]\n> Persistent storage using Fibre Channel is not supported on ARM architecture based infrastructures.\n\nThe Kubernetes persistent volume framework allows administrators to provision a cluster with persistent storage and gives users a way to request those resources without having any knowledge of the underlying infrastructure. Persistent volumes are not bound to a single project or namespace; they can be shared across the OpenShift Container Platform cluster. Persistent volume claims are specific to a project or namespace and can be requested by users.\n\n> [!IMPORTANT]\n> High availability of storage in the infrastructure is left to the underlying storage provider.\n\n**Additional resources**\n\n- [Using Fibre Channel devices](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_storage_devices/using-fibre-channel-devices_managing-storage-devices)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
