// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/monitoring/virt-exposing-downward-metrics.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Exposing downward metrics for virtual machines\n---\n\n# Exposing downward metrics for virtual machines {#virt-exposing-downward-metrics}\n\nAs an administrator, you can expose a set of host and virtual machine (VM) metrics to a guest VM by enabling the `downwardMetrics` feature gate and configuring a downward metrics device. You can view these metrics by using the command line or the `vm-dump-metrics` tool.\n\n> [!NOTE]\n> On Red Hat Enterprise Linux (RHEL) 9, use the command line to view downward metrics.\n>\n> The `vm-dump-metrics` tool is not supported on the Red Hat Enterprise Linux (RHEL) 9 platform.\n\n## Additional resources {#additional-resources_virt-exposing-downward-metrics-for-vms}\n\n- [Viewing downward metrics by using the command line](/openshift-docs-markdown/virt/monitoring/virt-exposing-downward-metrics#virt-viewing-downward-metrics-cli_virt-exposing-downward-metrics)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
