// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: support/troubleshooting/troubleshooting-windows-container-workload-issues.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Troubleshooting Windows container workload issues\n---\n\n# Troubleshooting Windows container workload issues {#troubleshooting-windows-container-workload-issues}\n\nUse the following sections to troubleshoot Windows container workload issues.\n\n{% include \"./modules/accessing-windows-node.md\" %}\n\n{% include \"./modules/collecting-kube-node-logs-windows.md\" %}\n\n## Additional resources {#_additional_resources}\n\n- [Configuring hybrid networking](/networking/ovn_kubernetes_network_provider/configuring-hybrid-networking#configuring-hybrid-ovnkubernetes)\n- [Containers on Windows troubleshooting](https://docs.microsoft.com/en-us/virtualization/windowscontainers/troubleshooting)\n- [Troubleshoot host and container image mismatches](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/update-containers#troubleshoot-host-and-container-image-mismatches)\n- [Common Kubernetes problems with Windows](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/common-problems)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
