// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: applications/projects/creating-project-other-user.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating a project as another user\n---\n\n# Creating a project as another user {#creating-project-other-user}\n\nYou can use impersonation to create a project on behalf of a different user account.\n\n## API impersonation {#authentication-api-impersonation_creating-project-other-user}\n\nYou can configure API requests in OpenShift Container Platform to act as another user. Impersonation allows you to perform actions on behalf of another account without switching credentials.\n\n## Impersonating a user when you create a project {#impersonation-project-creation_creating-project-other-user}\n\nYou can impersonate a different user when you create a project request. Because `system:authenticated:oauth` is the only bootstrap group that can create project requests, you must impersonate that group.\n\n**Procedure**\n\n- To create a project request on behalf of a different user:\n\n  ```terminal\n  $ oc new-project <project> --as=<user> \\\n      --as-group=system:authenticated --as-group=system:authenticated:oauth\n  ```\n\n## Additional resources {#_additional_resources}\n\n- [User impersonation (Kubernetes documentation)](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
