// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: applications/projects/creating-project-other-user.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating a project as another user\n---\n\n# Creating a project as another user {#creating-project-other-user}\n\nYou can use impersonation to create a project on behalf of a different user account.\n\n## Additional resources {#_additional_resources}\n\n- [User impersonation (Kubernetes documentation)](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
