// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_azure/installing-azure-three-node.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing a three-node cluster on Azure\n---\n\n# Installing a three-node cluster on Azure {#installing-azure-three-node}\n\nIn OpenShift Container Platform version 4.22, you can install a three-node cluster on Microsoft Azure. A three-node cluster consists of three control plane machines, which also act as compute machines.\n\nThis type of cluster provides a smaller, more resource efficient cluster, for cluster administrators and developers to use for testing, development, and production.\n\nYou can install a three-node cluster by using either installer-provisioned or user-provisioned infrastructure.\n\n> [!NOTE]\n> Deploying a three-node cluster by using an Azure Marketplace image is not supported.\n\n## Additional resources {#additional-resources_installing-azure-three-node}\n\n- [Installing a cluster on Azure with customizations](/openshift-docs-markdown/installing/installing_azure/ipi/installing-azure-customizations#installing-azure-customizations)\n- [Installing a cluster on Azure using ARM templates](/openshift-docs-markdown/installing/installing_azure/upi/installing-azure-user-infra#installing-azure-user-infra)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
