// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/nodes/virt-managing-node-labeling-obsolete-cpu-models.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Managing node labeling for obsolete CPU models\n---\n\n# Managing node labeling for obsolete CPU models {#virt-managing-node-labeling-obsolete-cpu-models}\n\nYou can schedule a virtual machine (VM) on a node if the VM CPU model and policy are supported by the node.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
