// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-gcp.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Control plane configuration options for {{ gcp_full }}\n---\n\n# Control plane configuration options for {{ gcp_full }} {#cpmso-config-options-gcp}\n\nYou can update your control plane machines to reflect changes in your infrastructure or environment by editing values in the control plane machine set specification.\n\nWhen you save an update to the control plane machine set, the Control Plane Machine Set Operator updates the control plane machines according to your configured update strategy. For more information, see \"Updating the control plane configuration\".\n\nThe following example YAML snippets show provider specification and failure domain configurations for a {{ gcp_short }} cluster.\n\n## Additional resources {#additional-resources_cpmso-config-options-gcp}\n\n- [Updating the control plane configuration](/openshift-docs-markdown/machine_management/control_plane_machine_management/cpmso-managing-machines#cpmso-feat-config-update_cpmso-managing-machines)\n- [Configuring {{ gcp_full }} features for control plane machines](/openshift-docs-markdown/machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-supported-features-gcp#cpmso-supported-features-gcp)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
