// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance/optimization/routing-optimization.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Optimizing routing\n---\n\n# Optimizing routing {#routing-optimization}\n\nYou can scale or configure the OpenShift Container Platform HAProxy router to optimize routing performance.\n\n## Additional resources {#additional-resources_routing-optimization}\n\n- [Configuring Ingress Controller sharding by using route labels](/openshift-docs-markdown/networking/ingress_load_balancing/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller#nw-ingress-sharding-route-labels_configuring-ingress-cluster-traffic-ingress-controller)\n- [Configuring Ingress Controller sharding by using namespace labels](/openshift-docs-markdown/networking/ingress_load_balancing/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller#nw-ingress-sharding-namespace-labels_configuring-ingress-cluster-traffic-ingress-controller)\n- [Setting Ingress Controller thread count](/openshift-docs-markdown/networking/networking_operators/ingress-operator#nw-ingress-setting-thread-count_configuring-ingress)\n- [Ingress Controller configuration parameters](/openshift-docs-markdown/networking/networking_operators/ingress-operator#nw-ingress-controller-configuration-parameters_configuring-ingress)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
