// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/advanced_networking/bgp_routing/disabling-bgp-routing.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Disabling BGP routing\n---\n\n# Disabling BGP routing {#disabling-bgp-routing}\n\nTo stop external route advertisement and restore standard cluster networking behavior, disable OVN-Kubernetes Border Gateway Protocol (BGP) routing.\n\nAs a cluster administrator, you can disable OVN-Kubernetes BGP routing support for your cluster.\n\n## Disabling Border Gateway Protocol (BGP) routing {#nw-bgp-routing-config_disable-bgp-routing}\n\nDisable Border Gateway Protocol (BGP) routing for your cluster by removing additional routing capabilities from the network configuration.\n\nAs a cluster administrator, you can disable BGP routing support for your cluster on bare-metal infrastructure.\n\n**Prerequisites**\n\n- You have installed the OpenShift CLI (`oc`).\n- You are logged in to the cluster as a user with the `cluster-admin` role.\n- The cluster is installed on compatible infrastructure.\n\n**Procedure**\n\n- To disable dynamic routing, enter the following command:\n\n  ```terminal\n  $ oc patch Network.operator.openshift.io/cluster --type=merge -p '{\n    \"spec\": { \"additionalRoutingCapabilities\": null }\n  }'\n  ```\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
