// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/advanced_networking/bgp_routing/disabling-bgp-routing.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Disabling BGP routing\n---\n\n# Disabling BGP routing {#disabling-bgp-routing}\n\nTo stop external route advertisement and restore standard cluster networking behavior, disable OVN-Kubernetes Border Gateway Protocol (BGP) routing.\n\nAs a cluster administrator, you can disable OVN-Kubernetes BGP routing support for your cluster.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
