// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: hosted_control_planes/hcp-manage/hcp-manage-aws.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Managing {{ hcp }} on {{ aws_short }}\n---\n\n# Managing {{ hcp }} on {{ aws_short }} {#hcp-manage-aws}\n\nAfter you deploy a hosted cluster on {{ aws_first }}, you can manage the cluster.\n\n**Additional resources**\n\n- [Getting started with Amazon SQS](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-getting-started.html)\n- [Getting started: Create an Amazon EventBridge event bus rule](https://docs.aws.amazon.com/eventbridge/latest/userguide/event-bus-rule-get-started.html)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
