// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: web_console/web_terminal/configuring-web-terminal.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring the web terminal\n---\n\n# Configuring the web terminal {#configuring-web-terminal}\n\nYou can configure timeout and image settings for the web terminal, either for your current session or for all user sessions if you are a cluster administrator.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
