// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/network_security/AdminNetworkPolicy/ovn-k-anp-banp-metrics.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Monitoring ANP and BANP\n---\n\n# Monitoring ANP and BANP {#ovn-k-anp-banp-metrics}\n\nTo monitor and troubleshoot `AdminNetworkPolicy` and `BaselineAdminNetworkPolicy` resources in OpenShift Container Platform, you can use OVN-Kubernetes metrics that report resource counts, rules, and northbound database objects.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
