// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/installing/about-oadp-data-mover.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: About the {{ oadp_short }} Data Mover\n---\n\n# About the {{ oadp_short }} Data Mover {#about-oadp-data-mover}\n\nUse the {{ oadp_first }} built-in Data Mover to move Container Storage Interface (CSI) volume snapshots to remote object storage and restore stateful applications after cluster failures. This provides disaster recovery capabilities for both containerized and virtual machine workloads.\n\nThe Data Mover uses Kopia as the uploader mechanism to read the snapshot data and write to the unified repository.\n\n{{ oadp_short }} supports CSI snapshots on the following:\n\n- {{ odf_full }}\n- Any other cloud storage provider with the Container Storage Interface (CSI) driver that supports the Kubernetes Volume Snapshot API\n\n## Additional resources {#additional-resources_about-oadp-data-mover}\n\n- [About Kopia](/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-about-kopia#oadp-about-kopia)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
