// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/installing/configuring-oadp-multiple-bsl.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring the {{ oadp_first }} with more than one Backup Storage Location\n---\n\n# Configuring the {{ oadp_first }} with more than one Backup Storage Location {#configuring-oadp-multiple-bsl}\n\nConfigure multiple backup storage locations (BSLs) in the Data Protection Application (DPA) to store backups across different regions or storage providers. This provides flexibility and redundancy for your backup strategy.\n\n{{ oadp_short }} supports multiple credentials for configuring more than one BSL, so that you can specify the credentials to use with any BSL.\n\n**Additional resources**\n\n- [Creating profiles for different credentials](/openshift-docs-markdown/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws#oadp-aws-secrets-for-different-credentials_installing-oadp-aws)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
