// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/installing/configuring-oadp-multiple-vsl.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring the {{ oadp_first }} with more than one Volume Snapshot Location\n---\n\n# Configuring the {{ oadp_first }} with more than one Volume Snapshot Location {#configuring-oadp-multiple-vsl}\n\nConfigure multiple Volume Snapshot Locations (VSLs) in the Data Protection Application (DPA) to store volume snapshots across different cloud provider regions. This provides geographic redundancy and regional disaster recovery capabilities.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
