// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/installing/installing-oadp-ibm-cloud.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring the {{ oadp_full }} with {{ ibm_cloud_title }}\n---\n\n# Configuring the {{ oadp_full }} with {{ ibm_cloud_title }} {#installing-oadp-ibm-cloud}\n\nYou install the {{ oadp_first }} Operator on an {{ ibm_cloud_title }} cluster to back up and restore applications on the cluster. You configure {{ ibm_cloud_object_storage }} to store the backups.\n\n{% include \"./modules/configuring-ibm-cos.md\" %} {% include \"./modules/oadp-creating-default-secret.md\" %} {% include \"./modules/oadp-secrets-for-different-credentials.md\" %} {% include \"./modules/oadp-installing-dpa-1-3.md\" %} {% include \"./modules/oadp-setting-resource-limits-and-requests.md\" %} {% include \"./modules/oadp-configuring-node-agents.md\" %} {% include \"./modules/oadp-configuring-client-burst-qps.md\" %} {% include \"./modules/oadp-configuring-node-agent-load-affinity.md\" %} {% include \"./modules/oadp-node-agent-load-affinity-guidelines.md\" %} {% include \"./modules/oadp-configuring-node-agent-load-concurrency.md\" %} {% include \"./modules/oadp-configuring-repository-maintenance.md\" %} {% include \"./modules/oadp-configuring-velero-load-affinity.md\" %} {% include \"./modules/oadp-configuring-imagepullpolicy.md\" %}\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
