// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/installing/oadp-backup-restore-csi-snapshots.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Backing up and restoring CSI snapshots data movement\n---\n\n# Backing up and restoring CSI snapshots data movement {#oadp-backup-restore-csi-snapshots}\n\nYou can back up and restore persistent volumes by using the {{ oadp_short }} 1.3 Data Mover.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
