// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/installing/overriding-kopia-algorithms.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Overriding Kopia hashing, encryption, and splitter algorithms\n---\n\n# Overriding Kopia hashing, encryption, and splitter algorithms {#overriding-kopia-algorithms}\n\nOverride the default values of Kopia hashing, encryption, and splitter algorithms by using specific environment variables in the Data Protection Application (DPA).\n\n{% include \"./modules/oadp-kopia-configuring-algorithms.md\" %}\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
