// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: registry/securing-exposing-registry.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Exposing the registry\n---\n\n# Exposing the registry {#securing-exposing-registry}\n\nBy default, the {{ product_registry }} is secured during cluster installation so that it serves traffic through the Transport Layer Security (TLS) protocol. Unlike previous versions of OpenShift Container Platform, the registry is not exposed outside of the cluster at the time of installation.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
