// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/oadp-performance/oadp-recommended-network-settings.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: \"{{ oadp_short }} recommended network settings\"\n---\n\n# {{ oadp_short }} recommended network settings {#oadp-recommended-network-settings}\n\nKeep a stable network across your {{ OCP_short }} nodes, {{ aws_short }} Simple Storage Service (S3) storage, and cloud environments. Meeting these recommended network settings helps you ensure successful {{ oadp_first }} backup and restore operations, even when using remote {{ aws_short }} S3 buckets.\n\n## Additional resources {#_additional_resources}\n\n- \\[Configuring network settings\\](https://docs.redhat.com/en/documentation/openshift_container_platform/{{ ocp_version }}/html/configuring_network_settings/index)\n- [About installing {{ oadp_short }}](/openshift-docs-markdown/backup_and_restore/application_backup_and_restore/installing/about-installing-oadp#about-installing-oadp)\n- [Troubleshooting](/openshift-docs-markdown/backup_and_restore/application_backup_and_restore/troubleshooting/troubleshooting#troubleshooting)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
