// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/virt-customize-web-console.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Customize the web console\n---\n\n# Customize the web console {#virt-customize-web-console}\n\nAs a cluster administrator, you can customize the OpenShift Container Platform web console by integrating dynamic plugins. Virtual machine (VM) owners can then use the actions provided by these plugins from different tabs on the **Virtualization** page.\n\n## Additional resources {#additional-resources_virt-customize-web-console}\n\n- [Dynamic plugins overview](/web_console/dynamic-plugin/overview-dynamic-plugin#overview-dynamic-plugin)\n- [Getting started with dynamic plugins](/web_console/dynamic-plugin/dynamic-plugins-get-started#dynamic-plugins-get-started)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
