// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/virt-install-virtio-drivers-on-windows-vms.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Install VirtIO drivers on Windows VMs\n---\n\n# Install VirtIO drivers on Windows VMs {#virt-install-virtio-drivers-on-windows-vms}\n\nVirtIO drivers are paravirtualized device drivers required for Microsoft Windows virtual machines (VMs) to run in {{ VirtProductName }}. The drivers are shipped with the rest of the images and do not require a separate download.\n\nThe `container-native-virtualization/virtio-win` container disk must be attached to the VM as a SATA CD drive to enable driver installation. You can install VirtIO drivers during Windows installation or add them to an existing Windows installation.\n\nAfter the drivers are installed, the `container-native-virtualization/virtio-win` container disk can be removed from the VM.\n\n**Supported drivers**\n\n| Driver name | Hardware ID | Description |\n| --- | --- | --- |\n| **viostor** | VEN_1AF4&DEV_1001, VEN_1AF4&DEV_1042 | The block driver. Sometimes labeled as an **SCSI Controller** in the **Other devices** group. |\n| **viorng** | VEN_1AF4&DEV_1005, VEN_1AF4&DEV_1044 | The entropy source driver. Sometimes labeled as a **PCI Device** in the **Other devices** group. |\n| **NetKVM** | VEN_1AF4&DEV_1000, VEN_1AF4&DEV_1041 | The network driver. Sometimes labeled as an **Ethernet Controller** in the **Other devices** group. Available only if a VirtIO NIC is configured. |\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
