// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/virt-using-vtpm-devices.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Use a virtual Trusted Platform Module (vTPM) device\n---\n\n# Use a virtual Trusted Platform Module (vTPM) device {#virt-using-vtpm-devices}\n\nTo run Windows 11 or other workloads that require a Trusted Platform Module, you can add a virtual TPM (vTPM) to a new or existing virtual machine. Enable this by editing the `VirtualMachine` or `VirtualMachineInstance` manifest.\n\n> [!IMPORTANT]\n> With {{ VirtProductName }} 4.18 and newer, you can export virtual machines (VMs) with attached vTPM devices, create snapshots of these VMs, and restore VMs from these snapshots. However, cloning a VM with a vTPM device attached to it or creating a new VM from its snapshot is not supported.\n\n## Additional resources {#additional-resources_virt-using-vtpm-devices}\n\n- [Exporting virtual machines](/openshift-docs-markdown/virt/managing_vms/virt-exporting-vms#virt-exporting-vms)\n- [Creating a snapshot by using the CLI](/openshift-docs-markdown/virt/backup_restore/virt-backup-restore-snapshots#virt-creating-vm-snapshot-cli_virt-backup-restore-snapshots)\n- [Restoring a virtual machine from a snapshot by using the CLI](/openshift-docs-markdown/virt/backup_restore/virt-backup-restore-snapshots#virt-restoring-vm-from-snapshot-cli_virt-backup-restore-snapshots)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
