// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/networking_operators/sr-iov-operator/installing-sriov-operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing the SR-IOV Network Operator\n---\n\n# Installing the SR-IOV Network Operator {#installing-sriov-operator}\n\nTo manage SR-IOV network devices and network attachments on your cluster, install the Single Root I/O Virtualization (SR-IOV) Network Operator. By using this Operator, you can centralize the configuration and lifecycle management of your SR-IOV resources.\n\nAs a cluster administrator, you can install the Single Root I/O Virtualization (SR-IOV) Network Operator by using the OpenShift Container Platform CLI or the web console.\n\n## Additional resources {#additional-resources_installing-sriov-operator}\n\n- [Configuring the SR-IOV Network Operator](/networking/networking_operators/sr-iov-operator/configuring-sriov-operator#configuring-sriov-operator)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
