// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/scheduling/descheduler/nodes-descheduler-configuring.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Evicting pods using the descheduler\n---\n\n# Evicting pods using the descheduler {#nodes-descheduler-configuring}\n\nYou can run the descheduler in OpenShift Container Platform by installing the {{ descheduler_operator }} and setting the required profiles and other customizations.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
