// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/scheduling/descheduler/nodes-descheduler-uninstalling.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Uninstalling the {{ descheduler_operator }}\n---\n\n# Uninstalling the {{ descheduler_operator }} {#nodes-descheduler-uninstalling}\n\nIf you no longer need the {{ descheduler_operator }} in your cluster, you can uninstall the Operator and remove its related resources.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
