// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: rest_api/rbac_apis/rbac-apis-index.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: RBAC APIs\n---\n\n# RBAC APIs {#rbac-apis}\n\n## ClusterRoleBinding \\[rbac.authorization.k8s.io/v1\\] {#_clusterrolebinding_rbacauthorizationk8siov1}\n\nDescription\n:   ClusterRoleBinding references a ClusterRole, but not contain it.  It can reference a ClusterRole in the global namespace, and adds who information via Subject.\n\nType\n:   ```\n    `object`\n    ```\n\n## ClusterRole \\[rbac.authorization.k8s.io/v1\\] {#_clusterrole_rbacauthorizationk8siov1}\n\nDescription\n:   ClusterRole is a cluster level, logical grouping of PolicyRules that can be referenced as a unit by a RoleBinding or ClusterRoleBinding.\n\nType\n:   ```\n    `object`\n    ```\n\n## RoleBinding \\[rbac.authorization.k8s.io/v1\\] {#_rolebinding_rbacauthorizationk8siov1}\n\nDescription\n:   RoleBinding references a role, but does not contain it.  It can reference a Role in the same namespace or a ClusterRole in the global namespace. It adds who information via Subjects and namespace information by which namespace it exists in.  RoleBindings in a given namespace only have effect in that namespace.\n\nType\n:   ```\n    `object`\n    ```\n\n## Role \\[rbac.authorization.k8s.io/v1\\] {#_role_rbacauthorizationk8siov1}\n\nDescription\n:   Role is a namespaced, logical grouping of PolicyRules that can be referenced as a unit by a RoleBinding.\n\nType\n:   ```\n    `object`\n    ```\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
