// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: applications/creating_applications/templates-using-ruby-on-rails.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating applications using Ruby on Rails\n---\n\n# Creating applications using Ruby on Rails {#templates-using-ruby-on-rails}\n\nYou can build and deploy a Ruby on Rails 4 application on OpenShift Container Platform by developing it locally.\n\nStore the source in Git, then deploy the database, frontend, and route services. With this process, you can validate your application locally before deploying it to the cluster as a set of distinct services.\n\n> [!WARNING]\n> You must complete each part of this tutorial in order to before you deploy your application on OpenShift Container Platform. If a step fails, confirm that every preceding step completed successfully before you continue.\n\n## Prerequisites {#_prerequisites}\n\n- You have basic Ruby on Rails knowledge.\n- You have Ruby 2.0.0+, Rubygems, and Bundler installed locally.\n- You have basic Git knowledge.\n- You have a running instance of OpenShift Container Platform 4.\n- The {{ oc_first }} installed.\n- You are logged into a running OpenShift Container Platform cluster.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
