// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: applications/creating_applications/using-templates.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using templates\n---\n\n# Using templates {#using-templates}\n\nYou can use templates to deploy preconfigured applications and create reusable object definitions on your OpenShift Container Platform cluster. Upload, instantiate, and author templates from the web console or CLI to speed up application creation.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
