// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: cicd/jenkins/migrating-from-jenkins-to-openshift-pipelines.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Migrating from Jenkins to OpenShift Pipelines or Tekton\n---\n\n# Migrating from Jenkins to OpenShift Pipelines or Tekton {#migrating-from-jenkins-to-openshift-pipelines_{{ context }}}\n\nYou can migrate your CI/CD workflows from Jenkins to [{{ pipelines_title }}](https://docs.openshift.com/pipelines/latest/about/understanding-openshift-pipelines.html), a cloud-native CI/CD experience based on the Tekton project.\n\n## Additional resources {#_additional_resources}\n\n- [Understanding {{ pipelines_shortname }}](https://docs.openshift.com/pipelines/latest/about/understanding-openshift-pipelines.html)\n- [Role-based Access Control](/openshift-docs-markdown/authentication/using-rbac#using-rbac)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
