// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: cli_reference/gitops-argocd-cli-tools.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: \"{{ gitops_shortname }} CLI for use with {{ gitops_title }}\"\n---\n\n# GitOps CLI for use with Red Hat OpenShift GitOps {#gitops-argocd-cli-tools}\n\nThe GitOps `argocd` CLI is a tool for configuring and managing Red Hat OpenShift GitOps and Argo CD resources from a terminal.\n\nWith the GitOps CLI, you can make GitOps computing tasks simple and concise. You can install this CLI tool on different platforms.\n\n## Installing the GitOps CLI {#installing-argocd-gitops-cli}\n\nSee [Installing the GitOps CLI](https://docs.openshift.com/gitops/latest/installing_gitops/installing-argocd-gitops-cli.html).\n\n## Additional resources {#additional-resources_gitops-argocd-cli-tools}\n\n- [What is GitOps?](https://docs.openshift.com/gitops/latest/understanding_openshift_gitops/what-is-gitops.html#what-is-gitops)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
