// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: hardware_accelerators/amd-gpu-operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: AMD GPU Operator\n---\n\n# AMD GPU Operator {#amd-gpu-operator}\n\nAMD Instinct GPU accelerators combined with the AMD GPU Operator within your OpenShift Container Platform cluster lets you seamlessly harness computing capabilities for machine learning, Generative AI, and GPU-accelerated applications.\n\nThis documentation provides the information you need to enable, configure, and test the AMD GPU Operator. For more information, see [AMD Instinct™ Accelerators](https://www.amd.com/en/products/accelerators/instinct.html).\n\n**Next steps**\n\n1. Install the [Node Feature Discovery Operator](/hardware_enablement/psap-node-feature-discovery-operator#installing-the-node-feature-discovery-operator_node-feature-discovery-operator).\n2. Install the [Kernel Module Management Operator](/hardware_enablement/kmm-kernel-module-management#kmm-install_kernel-module-management-operator).\n3. Install and configure the [AMD GPU Operator](https://instinct.docs.amd.com/projects/gpu-operator/en/main/installation/openshift-olm.html#install-amd-gpu-operator).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
