// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: service_mesh/v2x/ossm-about.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: About OpenShift Service Mesh\n---\n\n# About OpenShift Service Mesh {#ossm-about}\n\n> [!NOTE]\n> Because {{ SMProductName }} releases on a different cadence from OpenShift Container Platform and because the {{ SMProductName }} Operator supports deploying multiple versions of the `ServiceMeshControlPlane`, the {{ SMProductShortName }} documentation does not maintain separate documentation sets for minor versions of the product.  The current documentation set applies to the most recent version of {{ SMProductShortName }} unless version-specific limitations are called out in a particular topic or for a particular feature.\n>\n> For additional information about the {{ SMProductName }} life cycle and supported platforms, refer to the [Platform Life Cycle Policy](https://access.redhat.com/support/policy/updates/openshift#ossm).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
