// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: service_mesh/v2x/ossm-profiles-users.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Managing users and profiles\n---\n\n# Managing users and profiles {#ossm-profiles-users}\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
