// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: service_mesh/v2x/ossm-extensions.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Extensions\n---\n\n# Extensions {#ossm-extensions}\n\nYou can use WebAssembly extensions to add new features directly into the {{ SMProductName }} proxies. This lets you move even more common functionality out of your applications, and implement them in a single language that compiles to WebAssembly bytecode.\n\n> [!NOTE]\n> WebAssembly extensions are not supported on {{ ibm_z_name }} and {{ ibm_power_name }}.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
