// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: service_mesh/v2x/ossm-performance-scalability.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Performance and scalability\n---\n\n# Performance and scalability {#ossm-performance-scalability}\n\nThe default `ServiceMeshControlPlane` settings are not intended for production use; they are designed to install successfully on a default OpenShift Container Platform installation, which is a resource-limited environment. After you have verified a successful SMCP installation, you should modify the settings defined within the SMCP to suit your environment.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
