// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: service_mesh/v2x/ossm-create-smcp.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating the ServiceMeshControlPlane\n---\n\n# Creating the ServiceMeshControlPlane {#ossm-create-smcp}\n\n## Additional resources {#_additional_resources}\n\n{{ SMProductName }} supports multiple independent control planes within the cluster. You can create reusable configurations with `ServiceMeshControlPlane` profiles. For more information, see [Creating control plane profiles](/service_mesh/v2x/ossm-profiles-users#ossm-control-plane-profiles_ossm-profiles-users).\n\n## Next steps {#_next_steps}\n\n- Add a project to the {{ SMProductShortName }} so that applications can be made available. For more information, see [Adding services to a service mesh](/service_mesh/v2x/ossm-create-mesh#ossm-create-mesh).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
