// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: service_mesh/v2x/removing-ossm.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Uninstalling Service Mesh\n---\n\n# Uninstalling Service Mesh {#removing-ossm}\n\nTo uninstall {{ SMProductName }} from an existing OpenShift Container Platform instance and remove its resources, you must delete the control plane, delete the Operators, and run commands to manually remove some resources.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
