// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: service_mesh/v2x/servicemesh-release-notes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Service Mesh Release Notes\n---\n\n# Service Mesh Release Notes {#service-mesh-release-notes}\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
