// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: applications/working_with_helm_charts/odc-working-with-helm-releases.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Working with Helm releases\n---\n\n# Working with Helm releases {#odc-working-with-helm-releases}\n\nYou can use the web console to create, update, roll back, or delete a Helm release.\n\n## Additional resources {#additional-resources_working-with-helm-releases}\n\n- [OpenShift web console](https://console.redhat.com/openshift/overview)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
