// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: ai_workloads/leader_worker_set/lws-uninstalling.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Uninstalling the {{ lws_operator }}\n---\n\n# Uninstalling the {{ lws_operator }} {#lws-uninstalling}\n\nIf you no longer need the {{ lws_operator }} in your cluster, you can uninstall the Operator and remove its related resources.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
