// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/compliance_operator/co-management/compliance-operator-uninstallation.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Uninstalling the Compliance Operator\n---\n\n# Uninstalling the Compliance Operator {#compliance-operator-uninstallation}\n\nYou can remove the OpenShift Compliance Operator from your cluster by using the OpenShift Container Platform web console or the {{ oc_first }}.\n\n## Additional resources {#additional-resources_compliance-operator-uninstallation}\n\n- [Installing the Compliance Operator](/security/compliance_operator/compliance-operator-installation#compliance-operator-installation)\n- [Managing the Compliance Operator](/security/compliance_operator/compliance-operator-manage#compliance-operator-understanding)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
