// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: sandboxed_containers/about-openshift-sandboxed-containers.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: About {{ osc }}\n---\n\n# About {{ osc }} {#about-openshift-sandboxed-containers}\n\n{{ osc }} provide security by running containerized applications in lightweight virtual machines. This architecture isolates your workloads from other workloads on the cluster and does not require significant changes to your existing workflows.\n\nConfidential Containers extend {{ osc }} and provide an additional layer of security. They ensure that your workloads are isolated from hypervisors and cloud providers. Confidential Containers protect data in use by leveraging hardware-based Trusted Execution Environments, which are verified by the Trustee attestation service.\n\n> [!NOTE]\n> Because {{ osc }} releases on a different cadence from OpenShift Container Platform, its documentation is now available as a separate documentation set at [Red Hat {{ osc }}](https://docs.redhat.com/en/documentation/openshift_sandboxed_containers).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
