// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/certificate_types_descriptions/machine-config-operator-certificates.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Machine Config Operator certificates\n---\n\n# Machine Config Operator certificates {#cert-types-machine-config-operator-certificates}\n\nUnderstand Machine Config Operator (MCO) certificates used to secure node connections to the Machine Config Server (MCS) during cluster provisioning, including their lifecycle, rotation, and support boundaries.\n\n**Additional resources**\n\n- [About the Machine Config Operator](/machine_configuration/index#about-machine-config-operator_machine-config-overview)\n- [About the OVN-Kubernetes network plugin](/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes#about-ovn-kubernetes)\n- [Regenerating CA certificates for the Machine Config Server](https://access.redhat.com/articles/regenerating_cluster_certificates#regenerating-ca-certificates-for-the-machine-config-server-5)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
