// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/certificate_types_descriptions/monitoring-and-cluster-logging-operator-component-certificates.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Monitoring and OpenShift Logging Operator component certificates\n---\n\n# Monitoring and OpenShift Logging Operator component certificates {#cert-types-monitoring-and-cluster-logging-operator-component-certificates}\n\nReview service certificate authority (CA) certificates for monitoring and Red Hat OpenShift Logging Operator components in OpenShift Container Platform, including validity, automatic rotation, and system-managed namespaces.\n\n## Expiration {#monitor-logging-component-certificates-expiration_cert-types-monitoring-and-cluster-logging-operator-component-certificates}\n\nMonitoring components secure their traffic with service CA certificates. These certificates are valid for 2 years and are replaced automatically on rotation of the service CA, which is every 13 months.\n\nIf the certificate is present in the `openshift-monitoring` or `openshift-logging` namespace, it is system managed and rotated automatically.\n\n## Management {#monitor-logging-component-certificates-management_cert-types-monitoring-and-cluster-logging-operator-component-certificates}\n\nThese certificates are managed by the system and not the user.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
