// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: observability/network_observability/flowcollector-api.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: FlowCollector API reference\n---\n\n# FlowCollector API reference {#flowcollector-api}\n\nThe `FlowCollector` API is the underlying schema used to pilot and configure the deployments for collecting network flows. This reference guide helps you manage those critical settings.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
