// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: observability/network_observability/metrics-alerts-dashboards.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using metrics with dashboards and alerts\n---\n\n# Using metrics with dashboards and alerts {#metrics-dashboards-alerts}\n\nThe Network Observability Operator uses the `flowlogs-pipeline` component to generate metrics from flow logs. Use these metrics to set custom alerts and view dashboards for network activity analysis.\n\n**Additional resources**\n\n- [Network Flows format reference](/observability/network_observability/json-flows-format-reference#network-observability-flows-format_json_reference)\n\n**Additional resources**\n\n- [Filtering eBPF flow data using a global rule](/observability/network_observability/observing-network-traffic#network-observability-filtering-ebpf-rule_nw-observe-network-traffic)\n- [Creating alerting rules for user-defined projects](https://docs.redhat.com/en/documentation/monitoring_stack_for_red_hat_openshift/latest/html/managing_alerts/managing-alerts-as-a-developer#creating-alerting-rules-for-user-defined-projects_managing-alerts-as-a-developer)\n- [Troubleshooting high cardinality metrics- Determining why Prometheus is consuming a lot of disk space](/support/troubleshooting/investigating-monitoring-issues#determining-why-prometheus-is-consuming-disk-space_investigating-monitoring-issues)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
