// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: observability/network_observability/network-observability-health-rules.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Network observability health rules\n---\n\n# Network observability health rules {#network-observability-health-rules}\n\nThe Network Observability Operator provides alerts by using built-in metrics and the OpenShift Container Platform monitoring stack to report cluster network health.\n\n> [!IMPORTANT]\n> Network observability health alerts require OpenShift Container Platform 4.16 or later.\n\n## Additional resources {#_additional_resources}\n\n- [List of default rules](/observability/network_observability/network-observability-health-rules#network-observability-default-rules_network-observability-health-rules)\n- [Viewing network observability metrics dashboards](/observability/network_observability/metrics-alerts-dashboards#network-observability-viewing-dashboards_metrics-dashboards-alerts)\n- [Creating alerts](/observability/network_observability/metrics-alerts-dashboards#network-observability-netobserv-dashboard-high-traffic-alert_metrics-dashboards-alerts)\n- [Monitoring stack architecture](https://docs.redhat.com/en/documentation/monitoring_stack_for_red_hat_openshift/latest/html/about_monitoring/monitoring-stack-architecture)\n- [Network Observability Operator runbooks](https://github.com/openshift/runbooks/tree/master/alerts/network-observability-operator)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
