// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: observability/network_observability/network-observability-dns-resolution-analysis.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Network observability DNS resolution analysis\n---\n\n# Network observability DNS resolution analysis {#network-observability-dns-resolution-analysis_{{ context }}}\n\nLearn how DNS resolution analysis uses eBPF-based decoding to identify service discovery issues and follow the steps to enable DNS tracking in the FlowCollector resource to enrich network flow records with domain names.\n\n**Additional resources**\n\n- [Network flows format reference](/observability/network_observability/json-flows-format-reference#network-observability-flows-format_json_reference)\n- [Network Observability Operator runbooks](https://github.com/openshift/runbooks/tree/master/alerts/network-observability-operator)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
