// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: observability/network_observability/network-observability-kafka-operator-scaling-network-flow-collection.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Scaling network flow collection with Kafka\n---\n\n# Scaling network flow collection with Kafka {#network-observability-kafka-operator-scaling-network-flow-collection}\n\nScale your network flow collection by using the Kafka Operator to manage high-volume telemetry. Configure compression to reduce network bandwidth while balancing CPU overhead in large-scale cluster environments.\n\n## Additional resources {#additional-resources_network-observability-kafka-operator-scaling-network-flow-collection}\n\n- [Red Hat AMQ Streams documentation](https://access.redhat.com/documentation/en-us/red_hat_amq_streams)\n- [Configuring the FlowCollector resource with Kafka](/observability/network_observability/configuring-operator#network-observability-flowcollector-kafka-config_network_observability)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
