// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: observability/network_observability/network-observability-secondary-networks.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Secondary networks\n---\n\n# Secondary networks {#network-observability-secondary-networks}\n\nYou can configure the Network Observability Operator to collect and enrich network flow data from secondary networks, such as `SR-IOV` and `OVN-Kubernetes`.\n\n## Prerequisites {#network-observability-secondary-network-prerequisites_network-observability-secondary-networks}\n\n- Access to an OpenShift Container Platform cluster with an additional network interface, such as a secondary interface or an L2 network.\n\n**Additional resources**\n\n- [Configuring an SR-IOV network device](/openshift-docs-markdown/networking/hardware_networks/configuring-sriov-device#cnf-creating-an-additional-sriov-network-with-vrf-plug-in_configuring-sriov-device)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
