// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: observability/network_observability/troubleshooting-network-observability.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Troubleshooting network observability\n---\n\n# Troubleshooting network observability {#installing-troubleshooting}\n\nPerform diagnostic actions to troubleshoot common issues related to the Network Observability Operator and its components.\n\n**Additional resources**\n\n- [Resource considerations](/observability/network_observability/configuring-operator#network-observability-resources-table_network_observability)\n\n**Additional resources**\n\n- [Network flows format reference](/observability/network_observability/json-flows-format-reference#network-observability-flows-format_json_reference)\n- [FlowMetric API reference](/observability/network_observability/flowmetric-api#flowmetric-flows-netobserv-io-v1alpha1)\n- [Configuring custom metrics by using FlowMetric API](/observability/network_observability/metrics-alerts-dashboards#network-observability-configuring-custom-metrics_metrics-dashboards-alerts)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
