// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: updating/preparing_for_updates/kmm-preflight-validation.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Preflight validation for Kernel Module Management (KMM) Modules\n---\n\n# Preflight validation for Kernel Module Management (KMM) Modules {#kmm-preflight-validation}\n\nBefore you upgrade a cluster that uses Kernel Module Management (KMM) modules, verify that the kernel modules can be installed on the nodes after the upgrade. This preflight validation helps you avoid unexpected module failures caused by kernel changes.\n\nPreflight attempts to validate every `Module` loaded in the cluster, in parallel. Preflight does not wait for validation of one `Module` to complete before starting validation of another `Module`.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
