// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_alibaba/installing-alibaba-assisted-installer.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing a cluster on Alibaba Cloud by using the Assisted Installer\n---\n\n# Installing a cluster on Alibaba Cloud by using the Assisted Installer {#installing-alibaba-assisted-installer}\n\nYou can install an OpenShift Container Platform cluster on {{ alibaba }} using the {{ ai_full }}.\n\n{{ alibaba }} provides a broad range of cloud computing and data storage services to online businesses and global enterprises.\n\n**Additional resources**\n\n- [Installing OpenShift Container Platform with the {{ ai_full }}](https://docs.redhat.com/en/documentation/assisted_installer_for_openshift_container_platform/2025)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
