// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: observability/distr_tracing/distr-tracing-tempo-architecture.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: About the {{ DTShortName }}\n---\n\n# About the {{ DTShortName }} {#distr-tracing-tempo-architecture}\n\nThe standalone {{ DTProductName }} documentation is available at [https://docs.redhat.com/en/documentation/red_hat_openshift_distributed_tracing_platform/latest](https://docs.redhat.com/en/documentation/red_hat_openshift_distributed_tracing_platform/latest).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
