// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/configuring_network_settings/configuring-a-custom-pki.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring a custom PKI\n---\n\n# Configuring a custom PKI {#configuring-a-custom-pki}\n\nTo ensure secure communication between internal components in your OpenShift Container Platform cluster, you can add your organization’s custom Certificate Authority (CA) certificates to the cluster-wide truststore.\n\nYou can add your custom CA certificates to the cluster-wide truststore in one of two ways:\n\n- During cluster installation, by adding your CA certificate to the `install-config.yaml` file.\n- On a running cluster, by creating a `ConfigMap` object that contains your CA certificate and referencing it in the cluster `Proxy` object.\n\n> [!IMPORTANT]\n> The cluster Proxy object is the mechanism for managing the cluster-wide truststore. This guide focuses only on the task of adding a CA. If you also need to configure an egress proxy, refer to the \"Configuring the cluster-wide proxy\" chapter for detailed instructions.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
