// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/oadp-advanced-topics/oadp-backing-up-data-one-cluster-restoring-another-cluster.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Backing up data from one cluster and restoring it to another cluster\n---\n\n# Backing up data from one cluster and restoring it to another cluster {#oadp-backing-up-data-one-cluster-restoring-another-cluster}\n\nExplore how to back up application data from one OpenShift Container Platform cluster and restore it to another cluster. While more complex than single-cluster operations, {{ oadp_full }} provides the tools to manage this cross-cluster data recovery.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
