// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: updating/understanding_updates/intro-to-updates.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Introduction to OpenShift updates\n---\n\n# Introduction to OpenShift updates {#understanding-openshift-updates}\n\nWith OpenShift Container Platform 4, you can update an OpenShift Container Platform cluster with a single operation by using the web console or the OpenShift CLI (`oc`).\n\nPlatform administrators can view new update options either by going to **Administration** -> **Cluster Settings** in the web console or by looking at the output of the `oc adm upgrade` command.\n\n**Additional resources**\n\n- [Understanding update channels and releases](/updating/understanding_updates/understanding-update-channels-release#understanding-update-channels-releases)\n\n**Additional resources**\n\n- [Machine Config Overview](/machine_configuration/index#machine-config-overview)\n- [Using the OpenShift Update Service in a disconnected environment](/disconnected/updating/disconnected-update-osus#update-service-overview_updating-disconnected-cluster-osus)\n- [Update channels](/updating/understanding_updates/understanding-update-channels-release#understanding-update-channels_understanding-update-channels-releases)\n\n## Additional resources {#understanding-openshift-updates-additional-resources}\n\n- [How cluster updates work](/updating/understanding_updates/how-updates-work#how-updates-work)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
