// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: windows_containers/creating_windows_machinesets/creating-windows-machineset-gcp.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating a Windows machine set on {{ gcp_short }}\n---\n\n# Creating a Windows machine set on {{ gcp_short }} {#creating-windows-machineset-gcp}\n\nYou can use a `MachineSet` custom resource (CR) to add a Windows compute node to your {{ gcp_full }} cluster, where you can run Windows container workloads.\n\nFor example, you might create infrastructure Windows machine sets and related machines so that you can move supporting Windows workloads to the new Windows machines. For more information about machine sets, see \"Overview of machine management\".\n\n## Prerequisites {#prerequisites_creating-windows-machineset-gcp}\n\n- You installed the Windows Machine Config Operator (WMCO) using Operator Lifecycle Manager (OLM).\n- You are using a supported Windows Server as the operating system image.\n\n## Additional resources {#creating-windows-machineset-gcp-additional}\n\n- [Overview of machine management](/openshift-docs-markdown/machine_management/index#overview-of-machine-management)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
