// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/networking_operators/external_dns_operator/nw-configuring-cluster-wide-egress-proxy.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring the cluster-wide proxy on the External DNS Operator\n---\n\n# Configuring the cluster-wide proxy on the External DNS Operator {#external-dns-operator-cluster-wide-proxy}\n\nTo propagate proxy settings to your deployed Operators, configure the cluster-wide proxy. The Operator Lifecycle Manager (OLM) automatically updates these Operators with the new `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
