// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/networking_operators/external_dns_operator/nw-creating-dns-records-on-infoblox.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating DNS records on Infoblox\n---\n\n# Creating DNS records on Infoblox {#creating-dns-records-on-infoblox}\n\nTo create DNS records on Infoblox, use the External DNS Operator. The Operator manages external name resolution for your cluster services.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
