// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/networking_operators/external_dns_operator/nw-creating-dns-records-on-azure.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating DNS records on Azure\n---\n\n# Creating DNS records on Azure {#creating-dns-records-on-azure}\n\nTo create DNS records on {{ azure_first }}, use the External DNS Operator. By using this Operator, you can manage external name resolution for your cluster services.\n\n> [!IMPORTANT]\n> Using the External DNS Operator on a {{ entra_first }}-enabled cluster or a cluster that runs in {{ azure_full }} Government (MAG) regions is not supported.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
