// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/networking_operators/external_dns_operator/nw-installing-external-dns-operator-on-cloud-providers.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing the External DNS Operator\n---\n\n# Installing the External DNS Operator {#installing-external-dns-on-cloud-providers}\n\nTo manage DNS records on your cloud infrastructure, install the External DNS Operator. This Operator supports deployment on major cloud providers, including {{ aws_first }}, {{ azure_first }}, and {{ gcp_first }}.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
