// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: hosted_control_planes/hcp-prepare/hcp-cli.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing the {{ hcp }} command-line interface\n---\n\n# Installing the {{ hcp }} command-line interface {#hcp-cli}\n\nThe {{ hcp }} command-line interface, `hcp`, is a tool that you can use to get started with {{ hcp }}. For Day 2 operations, such as management and configuration, use GitOps or your own automation tool.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
