// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: hosted_control_planes/hcp-prepare/hcp-enable-disable.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Enabling or disabling the {{ hcp }} feature\n---\n\n# Enabling or disabling the {{ hcp }} feature {#hcp-enable-disable}\n\nThe {{ hcp }} feature, as well as the `hypershift-addon` managed cluster add-on, are enabled by default. If needed, you can disable the feature, or if you disabled it, you can manually enable it.\n\nYou can uninstall the HyperShift Operator and disable the {{ hcp }} feature. When you disable the {{ hcp }} feature, you must destroy the hosted cluster and the managed cluster resource on {{ mce_short }}, as described in the *Destroying a hosted cluster* section.\n\n**Additional resources**\n\n- [Destroying a hosted cluster](/openshift-docs-markdown/hosted_control_planes/hcp-destroy/hcp-destroy-aws#hcp-destroy-aws)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
