// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_ibm_z/installation-config-parameters-ibm-z.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installation configuration parameters for {{ ibm_z_title }} and {{ ibm_linuxone_title }}\n---\n\n# Installation configuration parameters for {{ ibm_z_title }} and {{ ibm_linuxone_title }} {#installation-config-parameters-ibm-z}\n\nBefore you deploy an OpenShift Container Platform cluster on {{ ibm_z_name }} or {{ ibm_linuxone_name }}, you provide a customized `install-config.yaml` file. This reference describes the required and optional parameters for that file.\n\n> [!NOTE]\n> While this document refers only to {{ ibm_z_name }}, all information in it also applies to {{ ibm_linuxone_name }}.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
