// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/ovn_kubernetes_network_provider/configure-ovn-kubernetes-subnets.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring OVN-Kubernetes internal IP address subnets\n---\n\n# Configuring OVN-Kubernetes internal IP address subnets {#configure-ovn-kubernetes-subnets}\n\nAs a cluster administrator, you can change the IP address ranges that the OVN-Kubernetes network plugin uses for the join and transit subnets.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
