// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/ovn_kubernetes_network_provider/deploying-egress-router-ovn-redirection.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Deploying an egress router pod in redirect mode\n---\n\n# Deploying an egress router pod in redirect mode {#deploying-egress-router-ovn-redirection}\n\nAs a cluster administrator, you can deploy an egress router pod to redirect traffic to specified destination IP addresses from a reserved source IP address.\n\nThe egress router implementation uses the egress router Container Network Interface (CNI) plugin.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
