// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/ovn_kubernetes_network_provider/disabling-multicast.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Disabling multicast for a project\n---\n\n# Disabling multicast for a project {#nw-ovn-kubernetes-disabling-multicast}\n\nIn OpenShift Container Platform with OVN-Kubernetes, you can disable IP multicast on a per-project basis so pods no longer receive multicast traffic.\n\n## Disabling multicast between pods {#nw-disabling-multicast_ovn-kubernetes-disabling-multicast}\n\nTo disable multicast between pods in a project, you can remove the `k8s.ovn.org/multicast-enabled` annotation from the namespace by using the `oc annotate` command or a namespace manifest.\n\n**Prerequisites**\n\n- Install the OpenShift CLI (`oc`).\n- You must log in to the cluster with a user that has the `cluster-admin` role.\n\n**Procedure**\n\n- Disable multicast by running the following command:\n\n  ```terminal\n  $ oc annotate namespace <namespace> \\\n      k8s.ovn.org/multicast-enabled-\n  ```\n\n  For `<namespace>`, specify the namespace for the project you want to disable multicast for.\n\n  > [!TIP]\n  > You can alternatively apply the following YAML to delete the annotation:\n  >\n  > ```yaml\n  > apiVersion: v1\n  > kind: Namespace\n  > metadata:\n  >   name: <namespace>\n  >   annotations:\n  >     k8s.ovn.org/multicast-enabled: null\n  > ```\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
