// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/ovn_kubernetes_network_provider/ovn-kubernetes-tracing-using-ovntrace.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Tracing Openflow with ovnkube-trace\n---\n\n# Tracing Openflow with ovnkube-trace {#ovn-kubernetes-tracing-using-ovntrace}\n\nTo trace Open vSwitch and OVN traffic flows in OpenShift Container Platform, you can use the `ovnkube-trace` utility, which runs `ovn-trace`, `ovs-appctl ofproto/trace`, and `ovn-detrace` in a single correlated output.\n\nYou can execute the `ovnkube-trace` binary from a dedicated container. For releases after OpenShift Container Platform 4.7, you can also copy the binary to a local host and execute it from that host.\n\n## Additional resources {#additional-resources_ovn-kubernetes-tracing-with-ovnkube}\n\n- [Tracing Openflow with ovnkube-trace utility](https://access.redhat.com/solutions/5887511)\n- [ovnkube-trace](https://github.com/ovn-kubernetes/ovn-kubernetes/blob/master/docs/troubleshooting/ovnkube-trace.md)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
