// AUTO-GENERATED by `dogsbay site build` — do not edit.
// Composes the docs-layout middleware helpers.
//
// Static-prerender guard:
//   In Astro's static output mode, this middleware is invoked
//   for every prerendered route at build time. Reading
//   `context.request.headers` there triggers an Astro warning
//   per page ("Astro.request.headers was used during static
//   render"), which floods `dogsbay site build` / `site preview`
//   output. Worse, the negotiation can't actually happen at
//   build time — there's no runtime client whose Accept header
//   we'd be honoring.
//
//   We guard with `context.isPrerendered` so prerendered routes
//   short-circuit to `next()` immediately. At runtime in static
//   deploys, middleware doesn't fire at all (no server); at
//   runtime in SSR / hybrid deploys, only dynamic routes fire,
//   which is exactly when negotiation makes sense.
//
// Markdown content negotiation:
//   For pure-static deploys, `Accept: text/markdown` is honored
//   by the platform (Cloudflare _headers + Worker, Netlify Edge
//   functions). Agents that can't send Accept headers should
//   follow the page's <link rel="alternate" type="text/markdown">
//   to fetch the .md mirror directly (e.g. /docs.md).
import { defineMiddleware } from "astro:middleware";
import { shouldRewriteToMarkdown } from "@dogsbay/docs-layout/markdown-negotiation";

export const onRequest = defineMiddleware((context, next) => {
  if (context.isPrerendered) return next();
  const url = new URL(context.request.url);
  const accept = context.request.headers.get("accept");
  const mdTarget = shouldRewriteToMarkdown(accept, url.pathname);
  if (mdTarget) return context.rewrite(mdTarget);
  return next();
});
