// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/ingress_load_balancing/configuring_gateway_api/securing-httproutes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Securing HTTPRoutes\n---\n\n# Securing HTTPRoutes {#securing-httproutes}\n\nTo protect sensitive data and meet security compliance requirements, you must secure your Gateway API application traffic. You can secure 'HTTPRoute' custom resources (CRs) by either applying edge or re-encrypt Transport Layer Security (TLS) termination. Choose your method based on your security architecture and performance needs.\n\n## Additional resources {#additional-resources_securing-httproutes}\n\n- [Routing HTTP requests to services](/openshift-docs-markdown/networking/ingress_load_balancing/configuring_gateway_api/routing-http-requests-to-services#routing-http-requests-to-services)\n- [Securing routes](/openshift-docs-markdown/networking/ingress_load_balancing/routes/securing-routes#securing-routes)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
