// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/ingress_load_balancing/configuring_gateway_api/verifying-gateway-infrastructure-status.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Verify Gateway infrastructure status\n---\n\n# Verify Gateway infrastructure status {#verifying-gateway-infrastructure-status}\n\nTo ensure your gateway infrastructure is properly configured and functioning, review the `status` conditions of your `GatewayClass` and `Gateway` custom resources (CRs). Checking these conditions confirms that the controller has successfully programmed your underlying data plane without routing conflicts.\n\nTo verify that your gateway infrastructure is functioning correctly, complete the following tasks:\n\n- Understand `GatewayClass` status conditions to verify that the controller has claimed the class and that your installed API version is compatible.\n- Review `Gateway` CR and listener `status` conditions to pinpoint data plane failures, configuration errors, or negative polarity conflicts.\n- Query gateway infrastructure status using the CLI to quickly validate your deployment and retrieve assigned IP addresses.\n\n## Additional resources {#verifying-gateway-infrastructure-status-additional-resources}\n\n- [Installing a cluster on {{ gcp_short }} with customizations](/openshift-docs-markdown/installing/installing_gcp/installing-gcp-customizations#installation-gcp-provisioning-dns-records_installing-gcp-customizations)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
