// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: cli_reference/openshift_cli/administrator-cli-commands.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: OpenShift CLI administrator command reference\n---\n\n# OpenShift CLI administrator command reference {#cli-administrator-commands}\n\nTo learn more about the {{ oc_first }} administrator commands, review their descriptions and example commands. You must have `cluster-admin` or equivalent permissions to use these commands.\n\nFor developer commands, see the \"OpenShift CLI developer command reference\".\n\nRun `oc adm -h` to list all administrator commands or run `oc <command> --help` to get additional details for a specific command.\n\n## Additional resources {#additional-resources_cli-administrator-commands}\n\n- [OpenShift CLI developer command reference](/openshift-docs-markdown/cli_reference/openshift_cli/developer-cli-commands#cli-developer-commands)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
