// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: extensions/catalogs/fbc.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: File-based catalogs\n---\n\n# File-based catalogs {#fbc}\n\n{{ olmv1_first }} in OpenShift Container Platform supports *file-based catalogs* for discovering and sourcing cluster extensions, including Operators, on a cluster.\n\n**Additional resources**\n\n- [CUE language specification](https://cuelang.org/docs/references/spec/)\n\n**Additional resources**\n\n- [Updating or filtering a file-based catalog image](/openshift-docs-markdown/operators/admin/olm-managing-custom-catalogs#olm-filtering-fbc_olm-managing-custom-catalogs)\n\n**Additional resources**\n\n- [Creating a file-based catalog image](/openshift-docs-markdown/operators/admin/olm-managing-custom-catalogs#olm-creating-fb-catalog-image_olm-managing-custom-catalogs)\n- [opm CLI reference](/openshift-docs-markdown/cli_reference/opm/cli-opm-ref#cli-opm-ref)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
