// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: extensions/catalogs/rh-catalogs.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Red Hat-provided catalogs\n---\n\n# Red Hat-provided catalogs {#rh-catalogs}\n\nRed Hat provides several Operator catalogs that are included with OpenShift Container Platform by default.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
