// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/getting_started/virt-using-the-cli-tools.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using the CLI tools\n---\n\n# Using the CLI tools {#virt-using-the-cli-tools}\n\nYou can manage {{ VirtProductName }} resources by using the `virtctl` command-line tool. Virtual machine (VM) commands can also be used to manage virtual machine instances (VMIs) unless otherwise specified.\n\n> [!NOTE]\n> You can access and change VM disk images by using the `libguestfs` command-line tool. You deploy `libguestfs` by using the `virtctl libguestfs` command.\n\n{% include \"./modules/virt-installing-virtctl-binary.md\" %} {% include \"./modules/virt-virtctl-information-commands.md\" %} {% include \"./modules/virt-vm-information-commands.md\" %} {% include \"./modules/virt-vm-manifest-creation-commands.md\" %} {% include \"./modules/virt-vm-management-commands.md\" %} {% include \"./modules/virt-vm-connection-commands.md\" %} {% include \"./modules/virt-vm-export-commands.md\" %} {% include \"./modules/virt-hot-plug-and-hot-unplug-commands.md\" %} {% include \"./modules/virt-image-upload-commands.md\" %}\n\n## Additional resources {#_additional_resources}\n\n- [Red Hat Ansible Automation Hub](https://console.redhat.com/ansible/automation-hub)\n- [`libguestfs`](https://libguestfs.org)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
