// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/post_installation_configuration/virt-vm-recovery-from-node-failures.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Virtual machine recovery from node failures\n---\n\n# Virtual machine recovery from node failures {#virt-vm-recovery-from-node-failures}\n\nTo ensure that virtual machines (VMs) recover automatically when a node fails, configure node health checks, automated remediation, and capacity planning. These recommendations come from chaos testing results and help minimize VM downtime during node failure conditions.\n\n## Additional resources {#_additional_resources}\n\n- [Configure eviction and run strategies](/openshift-docs-markdown/virt/nodes/virt-eviction-strategies#virt-eviction-strategies)\n- [Run strategies](/openshift-docs-markdown/virt/nodes/virt-eviction-strategies#virt-runstrategies-vms_virt-eviction-strategies)\n- [About high availability for virtual machines](/openshift-docs-markdown/virt/managing_vms/advanced_vm_management/virt-high-availability-for-vms#virt-high-availability-for-vms)\n- [Control virtual machine states](/openshift-docs-markdown/virt/managing_vms/virt-controlling-vm-states#virt-controlling-vm-states)\n- [Workload Availability for Red Hat OpenShift](https://docs.redhat.com/en/documentation/workload_availability_for_red_hat_openshift/24.3)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
