// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/post_installation_configuration/virt-self-validation-checkups.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Self validation checkup\n---\n\n# Self validation checkup {#virt-self-validation-checkups}\n\nA self validation checkup runs conformance tests on critical subsystems to verify that the environment is fully functional and self-sustained before you deploy production workloads.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
