// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/post_installation_configuration/virt-configuring-certificate-rotation.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring certificate rotation\n---\n\n# Configuring certificate rotation {#virt-configuring-certificate-rotation}\n\nConfigure certificate rotation parameters to replace existing certificates.\n\n## Additional resources {#additional-resources_virt-configuring-certificate-rotation}\n\n- [golang `ParseDuration` format](https://golang.org/pkg/time/#ParseDuration)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
