// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/security_profiles_operator/spo-understanding.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Understanding the Security Profiles Operator\n---\n\n# Understanding the Security Profiles Operator {#spo-understanding}\n\nOpenShift Container Platform administrators can use the Security Profiles Operator to define increased security measures in clusters.\n\n> [!IMPORTANT]\n> The Security Profiles Operator supports only Red Hat Enterprise Linux CoreOS (RHCOS) worker nodes. Red Hat Enterprise Linux (RHEL) nodes are not supported.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
