// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/security_profiles_operator/spo-support.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Security Profiles Operator support\n---\n\n# Security Profiles Operator support {#spo-support}\n\nThe Security Profiles Operator is a \"Rolling Stream\" Operator, meaning updates are available asynchronously of OpenShift Container Platform releases.\n\n## Additional resources {#additional-resources_spo-support}\n\n- [OpenShift Operator Life Cycles on the Red Hat Customer Portal](https://access.redhat.com/support/policy/updates/openshift_operators)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
