// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/security_profiles_operator/spo-troubleshooting.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Troubleshooting the Security Profiles Operator\n---\n\n# Troubleshooting the Security Profiles Operator {#spo-troubleshooting}\n\nTroubleshoot the Security Profiles Operator to diagnose a problem or provide information in a bug report.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
