// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_openstack/installing-openstack-cloud-config-reference.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: OpenStack Cloud Controller Manager reference guide\n---\n\n# OpenStack Cloud Controller Manager reference guide {#installing-openstack-cloud-config-reference}\n\nThe reference guide provides a comprehensive overview of the {{ rh_openstack_first }} Cloud Controller Manager (CCM) config map parameters, specifically detailing load balancer options and properties automatically managed by the Operator.\n\n**Additional resources**\n\n- [Cloud Controller Manager (Kubernetes documentation)](https://kubernetes.io/docs/concepts/architecture/cloud-controller/)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
