// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_openstack/uninstalling-openstack-user.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Uninstalling a cluster on {{ rh_openstack }} from your own infrastructure\n---\n\n# Uninstalling a cluster on {{ rh_openstack }} from your own infrastructure {#uninstalling-openstack-user}\n\nYou can remove a cluster that you deployed to {{ rh_openstack_first }} on user-provisioned infrastructure.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
