// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: observability/network_observability/netobserv_cli/netobserv-cli-install.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing the Network Observability CLI\n---\n\n# Installing the Network Observability CLI {#netobserv-cli-install}\n\nThe Network Observability CLI (oc netobserv) is a standalone {{ oc_first }} plugin used to debug and troubleshoot cluster network traffic. It operates independently of the Network Observability Operator to gather immediate network performance diagnostics.\n\n**Additional resources**\n\n- [Installing and using CLI plugins](/openshift-docs-markdown/cli_reference/openshift_cli/extending-cli-plugins#cli-installing-plugins_cli-extend-plugins)\n- [Installing the {{ cli_manager }}](/openshift-docs-markdown/cli_reference/cli_manager/cli-manager-install#installing-cli-manager)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
