// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: observability/network_observability/netobserv_cli/netobserv-cli-using.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using the Network Observability CLI\n---\n\n# Using the Network Observability CLI {#netobserv-cli-using}\n\nThe Network Observability CLI filters and visualizes network flow and packet telemetry directly within the terminal. The tool exports captured data as JSON, database files, or Packet Capture (PCAP) files for seamless integration with third-party analysis utilities.\n\n{% include \"./modules/network-observability-cli-capturing-flows.md\" %} {% include \"./modules/network-observability-cli-capturing-packets.md\" %}\n\n**Additional resources**\n\n- [Network Observability CLI reference](/openshift-docs-markdown/observability/network_observability/netobserv_cli/netobserv-cli-reference#network-observability-netobserv-cli-reference_netobserv-cli-reference)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
