// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: post_installation_configuration/day_2_core_cnf_clusters/troubleshooting/troubleshooting-bmn-maintenance.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Bare-metal node maintenance\n---\n\n# Bare-metal node maintenance {#troubleshooting-bmn-maintenance}\n\nYou can connect to a node for general troubleshooting. However, in some cases, you need to perform troubleshooting or maintenance tasks on certain hardware components. This section discusses topics that you need to perform for hardware maintenance.\n\n**Additional resources**\n\n- [Working with nodes](/openshift-docs-markdown/nodes/nodes/nodes-nodes-working#nodes-nodes-working_nodes-nodes-working)\n\n**Additional resources**\n\n- [OpenShift Container Platform storage overview](/openshift-docs-markdown/storage/index#storage-overview_storage-overview)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
