// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: post_installation_configuration/day_2_core_cnf_clusters/troubleshooting/troubleshooting-intro.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Troubleshooting and maintaining OpenShift Container Platform clusters\n---\n\n# Troubleshooting and maintaining OpenShift Container Platform clusters {#troubleshooting-intro}\n\nTroubleshooting and maintenance are weekly tasks that can be a challenge if you do not have the tools to reach your goal, whether you want to update a component or investigate an issue. Part of the challenge is knowing where and how to search for tools and answers.\n\nTo maintain and troubleshoot a bare-metal environment with high performance requirements, see the following procedures.\n\n> [!IMPORTANT]\n> This troubleshooting information is not a reference for configuring OpenShift Container Platform or developing cloud-native applications.\n>\n> For information about developing cloud-native applications on OpenShift Container Platform, see [Red Hat Best Practices for Kubernetes](https://redhat-best-practices-for-k8s.github.io/guide/).\n\n{% include \"./modules/support-getting-support.md\" %} {% include \"./modules/support-knowledgebase-about.md\" %}\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
