// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: windows_containers/removing-windows-nodes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Removing Windows nodes\n---\n\n# Removing Windows nodes {#removing-windows-nodes}\n\nYou can remove a Windows node by deleting its host Windows machine.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
