// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: windows_containers/windows-node-upgrades.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Windows node updates\n---\n\n# Windows node updates {#windows-node-upgrades}\n\nYou can ensure your Windows nodes have the latest updates by updating the Windows Machine Config Operator (WMCO).\n\nYou can update the WMCO in any of the following scenarios:\n\n- Within the current version. for example, from <10.y.z> to <10.y.z+1>.\n- To a new, contiguous version. For example, from <10.y> to <10.y+1>.\n- From an EUS version to another EUS version by using a Control Plane Only update. For example, from <10.y> to <10.y+2>.\n\n## Additional resources {#additional-resources_windows-node-upgrades}\n\n- [Updating installed Operators](/operators/admin/olm-upgrading-operators#olm-upgrading-operators)\n- [Performing a Control Plane Only update](/updating/updating_a_cluster/control-plane-only-update#control-plane-only-update)\n- [Installing the Windows Machine Config Operator using the CLI](/windows_containers/enabling-windows-container-workloads#installing-wmco-using-cli_enabling-windows-container-workloads)\n- [Deleting Operators from a cluster using the CLI](/operators/admin/olm-deleting-operators-from-cluster#olm-deleting-operator-from-a-cluster-using-cli_olm-deleting-operators-from-a-cluster)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
