// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: windows_containers/windows-containers-troubleshooting.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Troubleshooting Windows container workloads\n---\n\n# Troubleshooting Windows container workloads {#windows-containers-troubleshooting}\n\nYou can troubleshoot Windows container workload issues to ensure that your Windows nodes are running correctly in your cluster.\n\n{% include \"./modules/accessing-windows-node.md\" %}\n\n{% include \"./modules/collecting-kube-node-logs-windows.md\" %}\n\n## Additional resources {#_additional_resources}\n\n- [Configuring hybrid networking](/openshift-docs-markdown/networking/ovn_kubernetes_network_provider/configuring-hybrid-networking#configuring-hybrid-ovnkubernetes)\n- [Containers on Windows troubleshooting (Microsoft documentation)](https://docs.microsoft.com/en-us/virtualization/windowscontainers/troubleshooting)\n- [Troubleshoot host and container image mismatches (Microsoft documentation)](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/update-containers#troubleshoot-host-and-container-image-mismatches)\n- [Common Kubernetes problems with Windows (Microsoft documentation)](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/common-problems)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
