// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: post_installation_configuration/day_2_core_cnf_clusters/updating/update-rhacm-talm-troubleshooting.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Troubleshoot cluster updates with {{ cgu_operator }}\n---\n\n# Troubleshoot cluster updates with {{ cgu_operator }} {#core-cluster-upgrades-troubleshooting}\n\nIf a cluster update gets stuck, fails, or results in degraded cluster Operators, use the following diagnostic procedures to identify the root cause and take corrective action.\n\n## Additional resources {#additional-resources_core-cluster-upgrades-troubleshooting}\n\n- [Perform health checks before a cluster update with {{ cgu_operator }}](/openshift-docs-markdown/post_installation_configuration/day_2_core_cnf_clusters/updating/update-rhacm-talm-health-checks#core-cluster-upgrades-health-checks)\n- [Using the {{ cgu_operator_full }} for cluster updates](/openshift-docs-markdown/edge_computing/cnf-talm-for-cluster-upgrades#cnf-talm-for-cluster-updates)\n- [Contact Red Hat support](https://access.redhat.com/support)\n- [Red Hat Knowledgebase](https://access.redhat.com/solutions)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
