// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: post_installation_configuration/day_2_core_cnf_clusters/updating/update-completing-the-z-stream-update.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Completing the z-stream cluster update\n---\n\n# Completing the z-stream cluster update {#update-completing-the-z-stream-update}\n\nComplete the following steps to perform a z-stream cluster update.\n\n**Additional resources**\n\n- [Selecting the target release](/post_installation_configuration/day_2_core_cnf_clusters/updating/update-api#update-selecting-the-target-release_update-api)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
