// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: post_installation_configuration/day_2_core_cnf_clusters/updating/update-api.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Verifying cluster API versions between update versions\n---\n\n# Verifying cluster API versions between update versions {#update-api}\n\nAPIs change over time as components are updated. It is important to verify that your application APIs are compatible with the updated cluster version.\n\n**Additional resources**\n\n- [Understanding API tiers](/rest_api/overview/understanding-api-support-tiers#understanding-api-support-tiers)\n- [Kubernetes version skew policy](https://kubernetes.io/releases/version-skew-policy/)\n\n**Additional resources**\n\n- [Understanding update channels and releases](/updating/understanding_updates/understanding-update-channels-release#understanding-update-channels-releases)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
