// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: post_installation_configuration/day_2_core_cnf_clusters/updating/update-rhacm-talm-operator-coordination.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Coordinate OLM-managed Operator updates with {{ cgu_operator }}\n---\n\n# Coordinate OLM-managed Operator updates with {{ cgu_operator }} {#core-cluster-upgrades-operator-coordination}\n\nOLM-managed Operators must be compatible with the target OpenShift Container Platform version before you begin a cluster update. Planning Operator updates alongside cluster updates prevents compatibility issues that can block or degrade the update process.\n\n## Additional resources {#additional-resources_core-cluster-upgrades-operator-coordination}\n\n- [Prepare {{ rh_rhacm }} policies and {{ cgu_operator }} for cluster updates](/post_installation_configuration/day_2_core_cnf_clusters/updating/update-rhacm-talm-preparing-policies#core-cluster-upgrades-preparing-policies)\n- [OpenShift Container Platform update documentation](https://docs.redhat.com/en/documentation/openshift_container_platform/)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
