// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/networking_operators/cluster-network-operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Cluster Network Operator in OpenShift Container Platform\n---\n\n# Cluster Network Operator in OpenShift Container Platform {#cluster-network-operator}\n\nWith the Cluster Network Operator, you can manage networking in OpenShift Container Platform, including how to view status, enable IP forwarding, and collect logs.\n\n## Additional resources {#cluster-network-operator-additional-resources}\n\n- [`Network` API in the `operator.openshift.io` API group](/openshift-docs-markdown/rest_api/operator_apis/network-operator-openshift-io-v1#network-operator-openshift-io-v1)\n- [Expanding the cluster network IP address range](/openshift-docs-markdown/networking/configuring_network_settings/configuring-cluster-network-range#nw-cluster-network-range-edit_configuring-cluster-network-range)\n- [How to configure OVN to use kernel routing table](https://access.redhat.com/solutions/6969174)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
