// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/networking_operators/dns-operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: DNS Operator in OpenShift Container Platform\n---\n\n# DNS Operator in OpenShift Container Platform {#dns-operator}\n\nIn OpenShift Container Platform, the DNS Operator deploys and manages a CoreDNS instance to provide a name resolution service to pods inside the cluster, enables DNS-based Kubernetes Service discovery, and resolves internal `cluster.local` names.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
