// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/external_secrets_management_console_plugin/external-secrets-console-plugin-release-notes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: External Secrets Management Console Plug-in release notes\n---\n\n# External Secrets Management Console Plug-in release notes {#external-secrets-console-plugin-release-notes}\n\nThe {{ external_secrets_console_plugin }} provides a unified OpenShift Console interface for viewing and managing secrets-related custom resources (CRs) from multiple Operators such as cert-manager, External Secrets Operator, and Secrets Store CSI Driver.\n\nThese release notes track the development of {{ external_secrets_console_plugin }}.\n\nFor more information, see [{{ external_secrets_operator_short }} overview](/security/external_secrets_management_console_plugin/index#external-secrets-console-plugin-overview).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
