// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/virtual_disks/virt-migrating-storage-class.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Migrate a VM disk to a different storage class\n---\n\n# Migrate a VM disk to a different storage class {#virt-migrating-storage-class}\n\nYou can migrate one or more virtual disks to a different storage class to optimize storage performance or reduce costs without stopping your virtual machine (VM) or virtual machine instance (VMI).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
