// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/virtual_disks/virt-expanding-vm-disks.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Expand virtual machine disks\n---\n\n# Expand virtual machine disks {#virt-expanding-vm-disks}\n\nExpand the  persistent volume claim (PVC) of your virtual machine disk to accomodate growing data requirements. If your storage provider does not support volume expansion, you can expand the available virtual storage of a VM by adding blank data volumes.\n\nYou cannot reduce the size of a VM disk.\n\n## Additional resources {#additional-resources_virt-expanding-vm-disks}\n\n- [Extending a basic volume in Windows](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/extend-a-basic-volume)\n- [Extending an existing file system partition without destroying data in Red Hat Enterprise Linux](https://access.redhat.com/solutions/29095)\n- [Extending a logical volume and its file system online in Red Hat Enterprise Linux](https://access.redhat.com/solutions/24770)\n- [Configuring preallocation mode for data volumes](/virt/storage/virt-using-preallocation-for-datavolumes#virt-using-preallocation-for-datavolumes)\n- [Managing data volume annotations](/virt/storage/virt-managing-data-volume-annotations#virt-managing-data-volume-annotations)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
