// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/virtual_disks/virt-hot-plugging-virtual-disks.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Hot-plug virtual disks to running VMs\n---\n\n# Hot-plug virtual disks to running VMs {#virt-hot-plugging-virtual-disks}\n\nYou can hot-plug or hot-unplug virtual disks from running VMs to dynamically adjust storage without downtime.\n\nOnly data volumes and persistent volume claims (PVCs) can be hot plugged and hot-unplugged. You cannot hot plug or hot-unplug container disks.\n\nA hot plugged disk remains attached to the VM even after reboot. You must unplug the disk to remove it from the VM.\n\n> [!NOTE]\n> Each VM has a `virtio-scsi` controller so that hot plugged disks can use the SCSI bus. The `virtio-scsi` controller overcomes the limitations of VirtIO while retaining its performance advantages. It is highly scalable and supports hot plugging over 4 million disks.\n>\n> When you hot plug disks to the VirtIO (`virtio-blk`) bus, each disk uses a PCI Express (PCIe) slot in the VM. The number of PCIe slots is limited and pre-set automatically at the VM creation as specified in the \"Available VirtIO Ports\" table. Therefore, you can use `virtio-blk` for a small number of disks that does not exceed the number of available slots.\n\n## Additional resources {#additional-resources_virt-hot-plugging-virtual-disks}\n\n- [Available VirtIO Ports](https://kubevirt.io/user-guide/storage/hotplug_volumes/#available-virtio-ports)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
