// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/virtual_disks/virt-configuring-shared-volumes-for-vms.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configure shared volumes for virtual machines\n---\n\n# Configure shared volumes for virtual machines {#virt-configuring-shared-volumes-for-vms}\n\nEnable high-availability scenarios like Windows Failover Clustering by configuring shared disks to allow multiple virtual machines to access the same storage volume. A shared disk’s volume must be block mode.\n\nYou configure disk sharing by exposing the storage as either of these types:\n\n- An ordinary VM disk\n- A logical unit number (LUN) disk with an SCSI connection and raw device mapping, as required for Windows Failover Clustering for shared volumes\n\nIn addition to configuring disk sharing, you can also set an error policy for each ordinary VM disk or LUN disk. The error policy controls how the hypervisor behaves when an input/output error occurs on a disk Read or Write.\n\n## Additional resources {#additional-resources_virt-configuring-shared-volumes-for-vms}\n\n- [Persistent reservation helper protocol](https://www.qemu.org/docs/master/interop/pr-helper.html)\n- [Failover Clustering in Windows Server and Azure Stack HCI](https://learn.microsoft.com/en-us/windows-server/failover-clustering/failover-clustering-overview)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
