// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: ai_workloads/kueue/admission-fair-sharing.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Admission fair sharing\n---\n\n# Admission fair sharing {#admission-fair-sharing}\n\nUse admission fair sharing to fairly distribute workloads across local Queues that share a single `ClusterQueue`.\n\nYou can balance workload admission by prioritizing workloads from local Queues that have used fewer resources historically. With admission fair sharing, you can track usage over time with a configurable decay function and apply admission penalties when workloads are admitted.\n\nWhen multiple tenants share a single `ClusterQueue`, some tenants risk resource starvation. Admission fair sharing adresses this issue by meeting the following requirements:\n\nEnforce multi-tenant fairness (business critical)\n:   Ensure fair distribution of cluster resources across all tenants based on their usage history.\n\nImprove service predictability\n:   Guarantee each tenant gets a consistent share of resources, reducing latency spikes and preventing starvation.\n\nEnable scalable governance\n:   Complement static quotas with dynamic, usage-based admission ordering that adapts as tenant demand changes.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
