// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: ai_workloads/kueue/configuring-quotas.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring quotas\n---\n\n# Configuring quotas {#configuring-quotas}\n\nAs an administrator, you can use {{ kueue_name }} to configure quotas to optimize resource allocation and system throughput for user workloads. You can configure quotas for compute resources such as CPU, memory, pods, and GPU.\n\nYou can configure quotas in {{ kueue_name }} by completing the following steps:\n\n1. Configure a cluster queue.\n2. Configure a resource flavor.\n3. Configure a local queue.\n\nUsers can then submit their workloads to the local queue.\n\n<a name=\"clusterqueues-next-steps_configuring-quotas\"></a>**Next steps**\n\nThe cluster queue is not ready for use until a [`ResourceFlavor` object](/openshift-docs-markdown/ai_workloads/kueue/configuring-quotas#configuring-resourceflavors_configuring-quotas) has also been configured.\n\n## Additional resources {#clusterqueues-additional-resources_configuring-quotas}\n\n- [RBAC permissions](/openshift-docs-markdown/ai_workloads/kueue/rbac-permissions#rbac-permissions)\n- [Kubernetes documentation about cluster queues](https://kueue.sigs.k8s.io/docs/concepts/cluster_queue/)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
