// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: ai_workloads/kueue/configuring-fairsharing.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring fair sharing\n---\n\n# Configuring fair sharing {#configuring-fairsharing}\n\nYou can configure fair sharing as a preemption strategy to distribute borrowable resources equally or by weight between tenants of a cohort.\n\nBorrowable resources are the unused nominal quota of all the cluster queues in a cohort.\n\nYou can configure fair sharing by setting the `preemptionPolicy` value in the `Kueue` custom resource (CR) to `FairSharing`.\n\n## Additional resources {#additional-resources_configuring-fairsharing}\n\n- [Creating a `Kueue` custom resource](/openshift-docs-markdown/ai_workloads/kueue/install-kueue#create-kueue-cr_install-kueue)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
