// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: ai_workloads/kueue/kueue-dra-integrating-dynamic-resource-allocation.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Integrating Dynamic Resource Allocation\n---\n\n# Integrating Dynamic Resource Allocation {#kueue-dra-integrating-dynamic-resource-allocation}\n\nYou can configure {{ kueue_name }} to manage quota for workloads that use Dynamic Resource Allocation (DRA) to request GPUs. When DRA quota management is configured, {{ kueue_name }} counts DRA device requests toward quota in the same way that it counts traditional resources such as CPU and memory.\n\nIf DRA device quota is not configured, {{ kueue_name }} does not account for GPU requests when admitting workloads, which can result in teams exceeding their GPU allocation.\n\n## Additional resources {#additional-resources_kueue-dra-integrating-dynamic-resource-allocation}\n\n- [Allocating GPUs to pods by using DRA](/nodes/pods/nodes-pods-allocate-dra#nodes-pods-allocate-dra)\n- [Configuring quotas](/ai_workloads/kueue/configuring-quotas#configuring-quotas)\n- [Creating a Kueue custom resource](/ai_workloads/kueue/install-kueue#create-kueue-cr_install-kueue)\n- [Enabling features using feature gates](/nodes/clusters/nodes-cluster-enabling-features#nodes-cluster-enabling-features)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
