// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: ai_workloads/kueue/managing-workloads.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Managing jobs and workloads\n---\n\n# Managing jobs and workloads {#managing-workloads}\n\nWhen you create jobs in your cluster, {{ kueue_name }} represents each job as a `Workload` object to track resource requirements, decisions, and statuses.\n\n{{ kueue_name }} does not directly manipulate your jobs. Instead, {{ kueue_name }} manages `Workload` objects that represent the resource requirements of a job, and syncs any decisions and statuses between the two objects.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
