// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: ai_workloads/kueue/using-cohorts.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using cohorts\n---\n\n# Using cohorts {#using-cohorts}\n\nYou can use cohorts to group cluster queues and determine which cluster queues can share borrowable resources with each other.\n\nBorrowable resources are defined as the unused nominal quota of all the cluster queues in a cohort.\n\nBy using cohorts, you can optimize resource utilization, prevent under-utilization, and enable fair sharing configurations. In addition, you can simplify resource management and allocation between teams, because you can group cluster queues for related workloads or for each team. You can also use cohorts to set resource quotas at a group level to define the limits for resources that a group of cluster queues can consume.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
