// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/audit-log-view.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Viewing audit logs\n---\n\n# Viewing audit logs {#audit-log-view}\n\nOpenShift Container Platform auditing provides a security-relevant chronological set of records documenting the sequence of activities that have affected the system by individual users, administrators, or other components of the system.\n\n## Additional resources {#viewing-audit-logs-additional-resources}\n\n- [Must-gather tool](/openshift-docs-markdown/support/gathering-cluster-data#about-must-gather_gathering-cluster-data)\n- [API audit log event structure](https://github.com/kubernetes/apiserver/blob/master/pkg/apis/audit/v1/types.go#L72)\n- [Configuring the audit log policy](/openshift-docs-markdown/security/audit-log-policy-config#audit-log-policy-config)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
