// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/external_secrets_management_console_plugin.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: \"{{ external_secrets_console_plugin }}\"\n---\n\n# {{ external_secrets_console_plugin }} {#external-secrets-console-plugin-overview}\n\nThe {{ external_secrets_console_plugin }} is an Operator that manages the secrets and custom resource definitions (CRDs) for the secrets management Operators. Using {{ external_secrets_console_plugin }}, you can monitor and delete the custom resources (CRs) of all the installed secrets management Operators.\n\nThe following secrets management Operators can be managed with {{ external_secrets_console_plugin }}:\n\n- {{ external_secrets_operator }}\n- {{ cert_manager_operator }}\n- {{ secrets_store_operator }}\n\nYou can use the plug-in to complete the following tasks:\n\n- View and filter secrets-related CRs from all installed secrets management Operators in a unified dashboard.\n- Inspect resource details including metadata, spec, status, and Kubernetes events.\n- Delete CRs directly from the console with name-confirmation.\n- View real-time resource health and status, including sync state, certificate expiry, and provider type.\n- Automatic Operator detection that shows resources only from Operators that are installed on the cluster.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
