// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/tls-security-profiles.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring TLS security profiles\n---\n\n# Configuring TLS security profiles {#tls-security-profiles}\n\nTo enforce secure cryptographic libraries for the OpenShift Container Platform components, cluster administrators can configure TLS security profiles to control cipher usage when the client connects to the Ingress Controller, the control plane, or the kubelet.\n\nThe control plane includes the following components:\n\n- Kubernetes API server\n- Kubernetes controller manager\n- Kubernetes scheduler\n- OpenShift API server\n- OpenShift OAuth API server\n- OpenShift OAuth server\n- etcd\n- Machine Config Operator\n- Machine Config Server.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
