// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/container_security/security-storage.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Securing attached storage\n---\n\n# Securing attached storage {#security-storage}\n\nYou should understand how OpenShift Container Platform secures attached storage to protect persistent data in containerized workloads. OpenShift Container Platform uses Security-Enhanced Linux (SELinux) capabilities, group ID (GID) annotations, and Container Storage Interface (CSI)-compliant storage providers to isolate storage access and prevent unauthorized data exposure.\n\n**Additional resources**\n\n- [Understanding persistent storage](/openshift-docs-markdown/storage/understanding-persistent-storage#understanding-persistent-storage)\n- [Configuring CSI volumes](/openshift-docs-markdown/storage/container_storage_interface/persistent-storage-csi#persistent-storage-csi)\n- [Dynamic provisioning](/openshift-docs-markdown/storage/dynamic-provisioning#dynamic-provisioning)\n- [Persistent storage using NFS](/openshift-docs-markdown/storage/persistent_storage/persistent-storage-nfs#persistent-storage-using-nfs)\n- [Persistent storage using AWS Elastic Block Store](/openshift-docs-markdown/storage/persistent_storage/persistent-storage-aws#persistent-storage-aws)\n- [Persistent storage using GCE Persistent Disk](/openshift-docs-markdown/storage/persistent_storage/persistent-storage-gce#persistent-storage-using-gce)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
