// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/container_security/security-build.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Securing the build process\n---\n\n# Securing the build process {#security-build}\n\nYou can secure your software supply chain by using trusted base images, integrating security testing, and building once to deploy everywhere. Managing this build process ensures production deployments match verified builds and protects the software stack where code and libraries integrate.\n\n## Additional resources {#additional-resources_security-build}\n\n- [Understanding image builds](/cicd/builds/understanding-image-builds#understanding-image-builds)\n- [Triggering and modifying builds](/cicd/builds/triggering-builds-build-hooks#triggering-builds-build-hooks)\n- [Creating build inputs](/cicd/builds/creating-build-inputs#creating-build-inputs)\n- [Input secrets and config maps](/cicd/builds/creating-build-inputs#builds-input-secrets-configmaps_creating-build-inputs)\n- [OpenShift Serverless overview](https://docs.openshift.com/serverless/1.28/about/about-serverless.html)\n- [Viewing application composition using the Topology view](/applications/odc-viewing-application-composition-using-topology-view#odc-viewing-application-composition-using-topology-view)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
