// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: operators/admin/olm-config.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring Operator Lifecycle Manager features\n---\n\n# Configuring Operator Lifecycle Manager features {#olm-config}\n\nCluster administrators can enable or disable Operator Lifecycle Manager (OLM) cluster features by editing the `OLMConfig` custom resource (CR) named `cluster` in OpenShift Container Platform.\n\n**Additional resources**\n\n- [Install modes](/operators/understanding/olm/olm-understanding-operatorgroups#olm-operatorgroups-membership_olm-understanding-operatorgroups)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
