// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: machine_management/control_plane_machine_management/cpmso-troubleshooting.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Troubleshooting the control plane machine set\n---\n\n# Troubleshooting the control plane machine set {#cpmso-troubleshooting}\n\nUse the following information to understand and recover from issues you might encounter.\n\n**Additional resources**\n\n- [Activating the control plane machine set custom resource](/openshift-docs-markdown/machine_management/control_plane_machine_management/cpmso-getting-started#cpmso-activating_cpmso-getting-started)\n- [Creating a control plane machine set custom resource](/openshift-docs-markdown/machine_management/control_plane_machine_management/cpmso-getting-started#cpmso-creating-cr_cpmso-getting-started)\n\n**Additional resources**\n\n- [Sample {{ azure_full }} provider specification](/openshift-docs-markdown/machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-azure#cpmso-yaml-provider-spec-azure_cpmso-config-options-azure)\n\n**Additional resources**\n\n- [Restoring to an earlier cluster state](/openshift-docs-markdown/backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state#dr-restoring-cluster-state)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
