// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: machine_management/control_plane_machine_management/cpmso-about.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: About control plane machine sets\n---\n\n# About control plane machine sets {#cpmso-about}\n\nWith control plane machine sets, you can automate management of the control plane machine resources within your OpenShift Container Platform cluster, simplifying upgrades and recovery from degraded control plane machines.\n\n> [!IMPORTANT]\n> Control plane machine sets cannot manage compute machines, and compute machine sets cannot manage control plane machines.\n\nControl plane machine sets provide for control plane machines similar management capabilities as compute machine sets provide for compute machines. However, these two types of machine sets are separate custom resources defined within the Machine API and have several fundamental differences in their architecture and functionality.\n\n## Additional resources {#additional-resources_cpmso-about}\n\n- [Control Plane Machine Set Operator reference](/openshift-docs-markdown/operators/operator-reference#control-plane-machine-set-operator_operator-reference)\n- [`ControlPlaneMachineSet` custom resource](/openshift-docs-markdown/rest_api/machine_apis/controlplanemachineset-machine-openshift-io-v1#controlplanemachineset-machine-openshift-io-v1)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
