// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: machine_management/control_plane_machine_management/cpmso-manually-scaling-control-planes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Manually scaling control plane machines\n---\n\n# Manually scaling control plane machines {#cpmso-manually-scaling-control-planes}\n\nManually scale to 4 or 5 control plane nodes on bare-metal infrastructure to recover from a degraded state, perform deep-level debugging, or ensure control plane stability in complex scenarios.\n\n> [!IMPORTANT]\n> Red Hat supports a cluster that has 4 or 5 control plane nodes only on bare-metal infrastructure.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
