// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/oadp-3scale/backing-up-3scale-api-management-by-using-oadp.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Backing up 3scale API Management by using OADP\n---\n\n# Backing up 3scale API Management by using OADP {#backing-up-3scale-api-management-by-using-oadp}\n\nBack up Red Hat 3scale API Management components, including the 3scale Operator, MySQL database, and Redis database, by using {{ oadp_first }}. This helps you protect your API management infrastructure and provides recovery in case of data loss.\n\nFor more information about installing and configuring Red Hat 3scale API Management, see *Installing 3scale API Management on OpenShift* and *Red Hat 3scale API Management*.\n\n**Additional resources**\n\n- [Installing 3scale API Management on OpenShift](https://docs.redhat.com/en/documentation/red_hat_3scale_api_management/2.15/html/installing_red_hat_3scale_api_management/install-threescale-on-openshift-guide)\n- [Red Hat 3scale API Management](https://docs.redhat.com/en/documentation/red_hat_3scale_api_management)\n- [Installing the Data Protection Application](/openshift-docs-markdown/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws#oadp-installing-dpa_installing-oadp-aws)\n- [Creating a Backup CR](/openshift-docs-markdown/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-creating-backup-cr#oadp-creating-backup-cr-doc)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
