// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: authentication/identity_providers/configuring-github-identity-provider.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring a GitHub or GitHub Enterprise identity provider\n---\n\n# Configuring a GitHub or GitHub Enterprise identity provider {#configuring-github-identity-provider}\n\nConfigure the `github` identity provider so users can log in to OpenShift Container Platform with GitHub or GitHub Enterprise accounts through OAuth. Use this integration when you want cluster users to authenticate with existing GitHub credentials instead of managing separate cluster passwords.\n\nYou can use the GitHub integration to connect to either GitHub or GitHub Enterprise. For GitHub Enterprise integrations, you must provide the `hostname` of your instance and can optionally provide a `ca` certificate bundle to use in requests to the server.\n\n> [!NOTE]\n> The following steps apply to both GitHub and GitHub Enterprise unless noted.\n\n**Additional resources**\n\n- [Identity provider parameters](/authentication/understanding-identity-provider#identity-provider-parameters_understanding-identity-provider)\n\n**Additional resources**\n\n- [GitHub authentication (GitHub documentation)](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/authorizing-oauth-apps)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
