// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: authentication/identity_providers/configuring-keystone-identity-provider.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring a Keystone identity provider\n---\n\n# Configuring a Keystone identity provider {#configuring-keystone-identity-provider}\n\nConfigure a Keystone identity provider to connect OpenShift Container Platform to an OpenStack Keystone v3 server so that users can sign in with Keystone credentials.\n\n**Additional resources**\n\n- [Identity provider parameters](/openshift-docs-markdown/authentication/understanding-identity-provider#identity-provider-parameters_understanding-identity-provider)\n\n## Additional resources {#additional-resources-keystone_configuring-keystone-identity-provider}\n\n- [Keystone](http://docs.openstack.org/developer/keystone/)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
