// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: authentication/identity_providers/configuring-ldap-identity-provider.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring an LDAP identity provider\n---\n\n# Configuring an LDAP identity provider {#configuring-ldap-identity-provider}\n\nConfigure an LDAP identity provider so users can log in to OpenShift Container Platform with usernames and passwords validated against your LDAPv3 directory.\n\n**Additional resources**\n\n- [Identity provider parameters](/authentication/understanding-identity-provider#identity-provider-parameters_understanding-identity-provider)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
