// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance/cluster-compare/advanced-ref-config-customization.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Performing advanced reference configuration customization\n---\n\n# Performing advanced reference configuration customization {#advanced-ref-config-customization}\n\nFor scenarios where you want to allow temporary deviations from the reference design, you can apply more advanced customizations.\n\n> [!WARNING]\n> These customizations override the default matching process that the `cluster-compare` plugin uses during a comparison. Use caution when applying these advanced customizations as it can lead to unintended consequences, such as excluding consequential information from a cluster comparison.\n\nSome advanced tasks to dynamically customize your reference configuration include the following:\n\n- **Manual matching**: Configure a user configuration file to manually match a custom resource from the cluster to a template in the reference configuration.\n- **Patching the reference**: Patch a reference to configure a reference configuration by using a patch option with the `cluster-compare` command.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
