// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance/cluster-compare/creating-a-reference-configuration.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating a reference configuration\n---\n\n# Creating a reference configuration {#creating-a-reference-configuration}\n\nConfigure a reference configuration to validate configuration resources from a cluster.\n\n**Additional resources**\n\n- [Sprig Function Documentation](https://masterminds.github.io/sprig/)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
