// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance/cluster-compare/troubleshooting-cluster-comparisons.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Troubleshooting cluster comparisons\n---\n\n# Troubleshooting cluster comparisons {#troubleshooting-cluster-comparisons}\n\nWhen using the `cluster-compare` plugin, you might see unexpected results, such as false positives or conflicts when multiple cluster custom resources (CRs) exist.\n\n## Additional resources {#_additional_resources}\n\n- [Installing the cluster-compare plugin](/scalability_and_performance/cluster-compare/installing-cluster-compare-plugin#installing-cluster-compare_installing-cluster-compare-plugin)\n- [Configuring manual matching between CRs and templates](/scalability_and_performance/cluster-compare/advanced-ref-config-customization#cluster-compare-manual-match_advanced-ref-config-customization)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
