// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance/cluster-compare/understanding-the-cluster-compare-plugin.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Understanding the cluster-compare plugin\n---\n\n# Understanding the cluster-compare plugin {#understanding-the-cluster-compare-plugin}\n\nThe `cluster-compare` plugin is an OpenShift CLI (`oc`) plugin that compares a cluster configuration with a reference configuration. The plugin reports configuration differences while suppressing expected variations by using configurable validation rules and templates.\n\nUse the `cluster-compare` plugin in development, production, and support scenarios to ensure cluster compliance with a reference configuration, and to quickly identify and troubleshoot relevant configuration differences.\n\n## Additional resources {#_additional_resources}\n\n- [Telco RAN DU reference design specification for OpenShift Container Platform](/openshift-docs-markdown/scalability_and_performance/telco-ran-du-rds#telco-ran-du-ref-design-specs)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
