// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: observability/logging/about-logging.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: About Logging\n---\n\n# About Logging {#about-logging}\n\nAs a cluster administrator, you can deploy logging on your OpenShift Container Platform cluster, and use it to collect and aggregate node system audit logs, application container logs, and infrastructure logs.\n\nYou can use logging to perform the following tasks:\n\n- Forward logs to your chosen log outputs, including on-cluster, Red Hat managed log storage.\n- Visualize your log data in the OpenShift Container Platform web console.\n\n> [!NOTE]\n> Because logging releases on a different cadence from OpenShift Container Platform, the logging documentation is available as a separate documentation set at [Red Hat OpenShift Logging](https://docs.redhat.com/en/documentation/red_hat_openshift_logging/).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
