// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: hosted_control_planes/hcp-destroy/hcp-destroy-ibm-power.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Destroying a hosted cluster on {{ ibm_power_title }}\n---\n\n# Destroying a hosted cluster on IBM Power {#hcp-destroy-ibm-power}\n\nYou might want to remove a hosted cluster if you are no longer using it, you are trying to reduce resources, or the hosted cluster is experiencing issues that are difficult to resolve.\n\n## Destroying a hosted cluster on IBM Power by using the CLI {#destroy-hc-ibm-power-cli_hcp-destroy-ibm-power}\n\nTo destroy a hosted cluster on IBM Power, you can use the hcp command-line interface (CLI).\n\n**Procedure**\n\n- Delete the hosted cluster by running the following command:\n\n  ```terminal\n  $ hcp destroy cluster agent\n   --name=<hosted_cluster_name> \\\n   --namespace=<hosted_cluster_namespace> \\\n   --cluster-grace-period <duration>\n  ```\n\n  - `<hosted_cluster_name>` specifies the name of your hosted cluster.\n  - `<hosted_cluster_namespace>` specifies the name of your hosted cluster namespace.\n  - `<duration>` specifies the duration to destroy the hosted cluster completely, for example, `20m0s`.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
