// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: registry/configuring_registry_storage/configuring-registry-storage-openstack-user-infrastructure.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring the registry for OpenStack user-provisioned infrastructure\n---\n\n# Configuring the registry for OpenStack user-provisioned infrastructure {#configuring-registry-storage-openstack-user-infrastructure}\n\nYou can configure the registry of a cluster that runs on your own {{ rh_openstack_first }} infrastructure.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
