// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: registry/configuring_registry_storage/configuring-registry-storage-rhodf.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring the registry for Red Hat OpenShift Data Foundation\n---\n\n# Configuring the registry for Red Hat OpenShift Data Foundation {#configuring-registry-storage-rhodf}\n\nTo configure the {{ product_registry }} on bare metal and vSphere to use {{ rh_storage_first }} storage, you must install {{ rh_storage }} and then configure image registry using Ceph or Noobaa.\n\n## Additional resources {#configuring-registry-storage-ocs}\n\n- [Configuring Image Registry to use {{ rh_storage }}](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/latest/html-single/managing_and_allocating_storage_resources/index#configuring-image-registry-to-use-openshift-data-foundation_rhodf)\n- [Performance tuning guide for Multicloud Object Gateway (NooBaa)](https://access.redhat.com/solutions/6719951)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
