// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_ibm_powervs/installing-ibm-cloud-account-power-vs.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring an {{ ibm_cloud_title }} account\n---\n\n# Configuring an {{ ibm_cloud_title }} account {#installing-ibm-cloud-account-power-vs}\n\nTo install OpenShift Container Platform on {{ ibm_power_server_name }}, you must configure an {{ ibm_cloud_name }} account with the correct quotas, DNS resolution, and IAM policies.\n\n## Prerequisites {#_prerequisites}\n\n- You have an {{ ibm_cloud_name }} account with a subscription. You cannot install OpenShift Container Platform on a free or on a trial {{ ibm_cloud_name }} account.\n\n**Additional resources**\n\n- [Quotas and service limits](https://cloud.ibm.com/docs/vpc?topic=vpc-quotas)\n- [Creating an {{ ibm_power_server_title }}](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server)\n\n**Additional resources**\n\n- [{{ ibm_cloud_name }} IAM overview](https://cloud.ibm.com/docs/account?topic=account-iamoverview)\n- [Access groups ({{ ibm_cloud_name }} documentation)](https://cloud.ibm.com/docs/account?topic=account-groups)\n- [Users and service IDs ({{ ibm_cloud_name }} documentation)](https://cloud.ibm.com/docs/account?topic=account-assign-access-resources)\n\n## Additional resources {#additional-resources_installing-ibm-cloud-account-power-vs}\n\n- [Creating an {{ ibm_power_server_name }} workspace](/installing/installing_ibm_powervs/creating-ibm-power-vs-workspace#creating-ibm-power-vs-workspace)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
