// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_ibm_powervs/uninstalling-cluster-ibm-power-vs.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Uninstalling a cluster on {{ ibm_power_server_title }}\n---\n\n# Uninstalling a cluster on {{ ibm_power_server_title }} {#uninstalling-cluster-ibm-power-vs}\n\nTo remove a OpenShift Container Platform cluster that you deployed on {{ ibm_power_server_name }}, run the delete cluster command to remove all associated cloud resources.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
