// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_azure_stack_hub/upi/upi-ash-preparing-to-install.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Preparing to install a cluster on Azure Stack Hub\n---\n\n# Preparing to install a cluster on Azure Stack Hub {#upi-ash-preparing-to-install}\n\nPrepare to install an OpenShift Container Platform cluster on Azure Stack Hub by verifying connectivity, configuring your account, generating SSH keys, downloading the installation program, and installing the CLI.\n\n- Verifying internet connectivity for your cluster.\n- Configuring an Azure Stack Hub account. See the \"Configuring an Azure Stack Hub account\".\n- Generating an SSH key pair. You can use this key pair to authenticate into the OpenShift Container Platform cluster’s nodes after it is deployed.\n- Downloading the installation program.\n- Installing the {{ oc_first }}.\n\n## Additional resources {#additional-resources_upi-ash-preparing-to-install}\n\n- [Configuring an Azure Stack Hub account](/installing/installing_azure_stack_hub/installing-azure-stack-hub-account#installing-azure-stack-hub-account)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
