// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/compliance_operator/co-scans/compliance-operator-checkresult-custom-metadata.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Propagating custom metadata to ComplianceCheckResult objects\n---\n\n# Propagating custom metadata to ComplianceCheckResult objects {#compliance-operator-checkresult-custom-metadata}\n\nStarting in Compliance Operator 1.9.0, add labels and annotations to `Rule` and `CustomRule` objects so matching metadata is displayed on `ComplianceCheckResult` objects after a scan. Downstream tools, dashboards, and ticketing workflows can use this metadata without maintaining a separate mapping.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
