// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/compliance_operator/co-scans/compliance-operator-remediation.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Managing Compliance Operator result and remediation\n---\n\n# Managing Compliance Operator result and remediation {#compliance-operator-remediation}\n\nYou can review compliance scan results and apply remediations to resolve failing rules. Remediations are not applied automatically, so you can verify each change before applying it to your cluster.\n\n> [!IMPORTANT]\n> Full remediation for Federal Information Processing Standards (FIPS) compliance requires enabling FIPS mode for the cluster. To enable FIPS mode, you must run the installation program from a {{ op_system_base_full }} computer configured to operate in FIPS mode. For more information about configuring FIPS mode on RHEL, see Installing the system in FIPS mode.\n>\n> FIPS mode is supported on the following architectures:\n>\n> - `x86_64`\n> - `ppc64le`\n> - `s390x`\n\n## Additional resources {#additional-resources_compliance-remediation}\n\n- [Modifying nodes](/nodes/nodes/nodes-nodes-managing#nodes-nodes-managing-about_nodes-nodes-managing)\n- [Ignition specification](https://coreos.github.io/ignition/specs/)\n- [Installing the system in FIPS mode](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/security_hardening/assembly_installing-the-system-in-fips-mode_security-hardening)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
