// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/compliance_operator/co-scans/compliance-scans.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Compliance Operator scans\n---\n\n# Compliance Operator scans {#compliance-operator-scans}\n\nYou can use the `ScanSetting` and `ScanSettingBinding` APIs to run compliance scans with the Compliance Operator.\n\nFor more information on these API objects, run the following command:\n\n```terminal\n$ oc explain scansettings\n```\n\nor\n\n```terminal\n$ oc explain scansettingbindings\n```\n\n## Additional resources {#additional-resources_compliance-operator-scans}\n\n- [Increasing Compliance Operator resource limits](/security/compliance_operator/co-scans/compliance-operator-troubleshooting#compliance-increasing-operator-limits_compliance-troubleshooting)\n- [Compliance Operator shows INCONSISTENT scan result with worker node](https://access.redhat.com/solutions/6970861)\n- [Managing Compliance Operator result and remediation](/security/compliance_operator/co-scans/compliance-operator-remediation#compliance-operator-remediation)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
