// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/compliance_operator/co-scans/compliance-operator-advanced.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Performing advanced Compliance Operator tasks\n---\n\n# Performing advanced Compliance Operator tasks {#compliance-operator-advanced}\n\nAs an advanced user, you can use options in the Compliance Operator for the purpose of debugging or integrating with existing tooling.\n\n## Additional resources {#additional-resources_compliance-advanced}\n\n- [Configuring priority and preemption](/nodes/pods/nodes-pods-priority#nodes-pods-priority-configuring_nodes-pods-priority)\n- [Managing security context constraints](/authentication/managing-security-context-constraints#managing-pod-security-policies)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
