// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_bare_metal/upi/scaling-a-user-provisioned-cluster-with-the-bare-metal-operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Scaling a user-provisioned cluster with the Bare Metal Operator\n---\n\n# Scaling a user-provisioned cluster with the Bare Metal Operator {#scaling-a-user-provisioned-cluster-with-the-bare-metal-operator}\n\nAfter deploying a user-provisioned infrastructure cluster, you can use the Bare Metal Operator (BMO) and other metal^3^ components to scale bare-metal hosts in the cluster. This approach helps you to scale a user-provisioned cluster in a more automated way.\n\n**Additional resources**\n\n- [Preparing the bare-metal node](/openshift-docs-markdown/installing/installing_bare_metal/bare-metal-expanding-the-cluster#preparing-the-bare-metal-node_bare-metal-expanding)\n- [Root device hints](/openshift-docs-markdown/installing/installing_bare_metal/ipi/ipi-install-installation-workflow#root-device-hints_ipi-install-installation-workflow)\n- [Diagnosing a duplicate MAC address when provisioning a new host in the cluster](/openshift-docs-markdown/installing/installing_bare_metal/bare-metal-expanding-the-cluster#ipi-install-diagnosing-duplicate-mac-address_bare-metal-expanding)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
