// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/cert_manager_operator/cert-manager-operator-integrating-istio.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Integrating the {{ cert_manager_operator }} with Istio-CSR\n---\n\n# Integrating the {{ cert_manager_operator }} with Istio-CSR {#cert-manager-operator-integrating-istio}\n\nThe {{ cert_manager_operator }} provides enhanced support for securing workloads and control plane components in {{ SMProductName }} or Istio. This includes support for certificates enabling mutual TLS (mTLS), which are signed, delivered, and renewed using cert-manager issuers. You can secure Istio workloads and control plane components by using the {{ cert_manager_operator }} managed Istio-CSR agent.\n\nWith this Istio-CSR integration, Istio can now obtain certificates from the {{ cert_manager_operator }}, simplifying security and certificate management.\n\n**Additional resources**\n\n- [{{ cert_manager_operator }} issuer providers](/security/cert_manager_operator/index#cert-manager-issuer-types_cert-manager-operator-about)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
