// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/cert_manager_operator/cert-manager-creating-certificate.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring certificates with an issuer\n---\n\n# Configuring certificates with an issuer {#cert-manager-creating-certificate}\n\nBy using the {{ cert_manager_operator }}, you can manage certificates, handling tasks such as renewal and issuance, for workloads within the cluster, as well as components interacting externally to the cluster.\n\n**Additional resources**\n\n- [Red Hat Knowledgebase solution](https://access.redhat.com/solutions/4542531)\n\n## Additional resources {#additional-resources_cert-manager-creating-certificate}\n\n- [Supported issuer types](/openshift-docs-markdown/security/cert_manager_operator/index#cert-manager-issuer-types_cert-manager-operator-about)\n- [Configuring an ACME issuer](/openshift-docs-markdown/security/cert_manager_operator/cert-manager-operator-issuer-acme#cert-manager-operator-issuer-acme)\n- [Adding an API server named certificate](/openshift-docs-markdown/security/certificates/api-server#customize-certificates-api-add-named_api-server-certificates)\n- [Replacing the default ingress certificate](/openshift-docs-markdown/security/certificates/replacing-default-ingress-certificate#replacing-default-ingress)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
