// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/cert_manager_operator/cert-manager-operator-release-notes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: \"{{ cert_manager_operator }} release notes\"\n---\n\n# {{ cert_manager_operator }} release notes {#cert-manager-operator-release-notes}\n\nThe {{ cert_manager_operator }} is a cluster-wide service that provides application certificate lifecycle management.\n\nThese release notes track the development of {{ cert_manager_operator }}.\n\nFor more information, see [About the {{ cert_manager_operator }}](/openshift-docs-markdown/security/cert_manager_operator/index#cert-manager-operator-about).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
