// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: vcp/vcp-preparing-environment.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Preparing the environment for virtualized control planes\n---\n\n# Preparing the environment for virtualized control planes {#vcp-preparing-environment}\n\nPrepare your hosting cluster environment before deploying a virtualized control plane cluster. This includes installing and configuring KubeVirt Redfish and creating the control plane VMs.\n\n## Additional resources {#additional-resources_vcp-preparing-environment}\n\n- [Recommended resources for topologies](/installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer#agent-based-installer-recommended-resources_preparing-to-install-with-agent-based-installer)\n- [Connecting a virtual machine to a secondary localnet user-defined network](/virt/vm_networking/virt-connecting-vm-to-secondary-udn#virt-connecting-vm-to-secondary-udn)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
