// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_nutanix/installing-nutanix-three-node.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing a three-node cluster on Nutanix\n---\n\n# Installing a three-node cluster on Nutanix {#installing-nutanix-three-node}\n\nIn OpenShift Container Platform version 4.22, you can install a three-node cluster on Nutanix. A three-node cluster consists of three control plane machines, which also act as compute machines. This type of cluster provides a smaller, more resource efficient cluster, for cluster administrators and developers to use for testing, development, and production.\n\n## Additional resources {#additional-resources_installing-nutanix-three-node}\n\n- [Installing a cluster on Nutanix](/openshift-docs-markdown/installing/installing_nutanix/installing-nutanix-installer-provisioned#installing-nutanix-installer-provisioned)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
