// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_nutanix/preparing-to-install-on-nutanix.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installation methods\n---\n\n# Installation methods {#preparing-to-install-on-nutanix}\n\nYou can install an OpenShift Container Platform cluster on Nutanix by using a variety of different installation methods. Each method has qualities that can make the method more suitable for different use cases, such as installing a cluster in a disconnected environment or installing a cluster that requires minimal configuration and provisioning. Before you install OpenShift Container Platform, ensure that your Nutanix environment meets specific requirements.\n\n**Additional resources**\n\n- [Preparing to install with the Agent-based Installer](/installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer#preparing-to-install-with-agent-based-installer)\n\n**Additional resources**\n\n- [Preparing to update a cluster with manually maintained credentials](/updating/preparing_for_updates/preparing-manual-creds-update#preparing-manual-creds-update)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
