// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: cli_reference/cli_manager/cli-manager-install.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing the {{ cli_manager }}\n---\n\n# Installing the {{ cli_manager }} {#cli-manager-install}\n\nYou can simplify the installation and management of CLI plugins in connected and disconnected environments with the {{ cli_manager }}. The {{ cli_manager }} makes Krew compatible with the `oc` CLI, allowing cluster administrators to manage custom CLI plugin resources.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
