// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: cli_reference/cli_manager/cli-manager-uninstall.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Uninstalling the {{ cli_manager }}\n---\n\n# Uninstalling the {{ cli_manager }} {#cli-manager-uninstall}\n\nYou can remove the {{ cli_manager }} from OpenShift Container Platform by uninstalling the {{ cli_manager }} and removing its related resources.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
