// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-3-expired-certs.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Recovering from expired control plane certificates\n---\n\n# Recovering from expired control plane certificates {#dr-recovering-expired-certs}\n\nYou can restore kubelet certificates on your OpenShift Container Platform cluster by approving pending certificate signing requests (CSRs) after control plane certificates expire. Approved CSRs return nodes to a healthy state.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
