// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: applications/idling-applications.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Reducing resource consumption with application idling\n---\n\n# Reducing resource consumption with application idling {#idling-applications}\n\nAs an administrator, you can reduce cluster resource consumption and lower public cloud costs by temporarily scaling inactive application resources to zero replicas.\n\nIf any scalable resources are not in use, OpenShift Container Platform discovers and idles them by scaling their replicas to `0`. The next time network traffic is directed to the resources, the resources are unidled by scaling up the replicas, and normal operation continues.\n\nApplications are made of services, as well as other scalable resources, such as deployment configs. The action of idling an application involves idling all associated resources.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
