// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: applications/odc-editing-applications.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Editing applications\n---\n\n# Editing applications {#odc-editing-applications}\n\nYou can edit the configuration and the source code of the application you create using the **Topology** view.\n\n## Prerequisites {#_prerequisites}\n\n- You have the appropriate [roles and permissions](/authentication/using-rbac#default-roles_using-rbac) in a project to create and modify applications in OpenShift Container Platform.\n- You have [created and deployed an application on OpenShift Container Platform using the **Developer** perspective](/applications/creating_applications/odc-creating-applications-using-developer-perspective#odc-creating-applications-using-developer-perspective).\n- You have [logged in to the web console](/web_console/web-console#web-console) and have switched to [the **Developer** perspective](/web_console/web-console-overview#about-developer-perspective_web-console-overview).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
