// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: applications/odc-monitoring-project-and-application-metrics-using-developer-perspective.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Monitoring project and application metrics using the Developer perspective\n---\n\n# Monitoring project and application metrics using the Developer perspective {#odc-monitoring-project-and-application-metrics-using-developer-perspective}\n\nThe **Observe** view in the **Developer** perspective provides options to monitor your project or application metrics, such as CPU, memory, and bandwidth usage, and network related information.\n\n## Prerequisites {#prerequisites_odc-monitoring-project-and-application-metrics-using-developer-perspective}\n\n- You have [created and deployed applications on OpenShift Container Platform](/openshift-docs-markdown/applications/creating_applications/odc-creating-applications-using-developer-perspective#odc-creating-applications-using-developer-perspective).\n- You have [logged in to the web console](/openshift-docs-markdown/web_console/web-console#web-console) and have switched to [the **Developer** perspective](/openshift-docs-markdown/web_console/web-console-overview#about-developer-perspective_web-console-overview).\n\n## Additional resources {#additional-resources-odc-monitoring-project-and-application-metrics-using-developer-perspective}\n\n- [About OpenShift Container Platform monitoring](https://docs.redhat.com/en/documentation/monitoring_stack_for_red_hat_openshift/latest/html/about_monitoring/about-ocp-monitoring)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
