// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: applications/odc-deleting-applications.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Deleting applications\n---\n\n# Deleting applications {#odc-deleting-applications}\n\nYou can delete applications created in your project.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
