// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/advanced_vm_management/virt-configuring-pxe-booting.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring PXE booting for virtual machines\n---\n\n# Configuring PXE booting for virtual machines {#configuring-pxe-booting}\n\nPXE booting, or network booting, allows a computer to boot and load an operating system or other program without requiring a locally attached storage device. For example, you can use it to choose your desired OS image from a PXE server when deploying a new host.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
