// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/advanced_vm_management/virt-understanding-aaq-operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring the Application-Aware Quota (AAQ) Operator\n---\n\n# Configuring the Application-Aware Quota (AAQ) Operator {#virt-understanding-aaq-operator}\n\nYou can use the Application-Aware Quota (AAQ) Operator to customize and manage resource quotas for individual components in an OpenShift Container Platform cluster.\n\n## Additional resources {#additional-resources_virt-understanding-aaq-operator}\n\n- [Resource quotas per project](/openshift-docs-markdown/applications/quotas/quotas-setting-per-project#quotas-setting-per-project)\n- [Resource quotas across multiple projects](/openshift-docs-markdown/applications/quotas/quotas-setting-across-multiple-projects#quotas-setting-across-multiple-projects)\n- [`ResourceQuota` API reference](/openshift-docs-markdown/rest_api/schedule_and_quota_apis/resourcequota-v1#resourcequota-v1)\n- [`ClusterResourceQuota` API reference](/openshift-docs-markdown/rest_api/schedule_and_quota_apis/clusterresourcequota-quota-openshift-io-v1#clusterresourcequota-quota-openshift-io-v1)\n- [Pod scheduling gates specification](/openshift-docs-markdown/rest_api/workloads_apis/pod-v1#spec-schedulinggates)\n- [Viewing system event information in an OpenShift Container Platform cluster](/openshift-docs-markdown/nodes/clusters/nodes-containers-events#nodes-containers-events)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
