// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/advanced_vm_management/virt-vm-control-plane-tuning.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Tune the control plane\n---\n\n# Tune the control plane {#virt-vm-control-plane-tuning}\n\nYou can configure how the control plane handles concurrency when you create or migrate virtual machines (VMs). For example, set the `QPS` or `burst` rates to batch create virtual machines (VMs) in a batch, or tune migration settings in the `HyperConverged` custom resource (CR).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
