// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/advanced_vm_management/virt-specifying-nodes-for-vms.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Specifying nodes for virtual machines\n---\n\n# Specifying nodes for virtual machines {#virt-specifying-nodes-for-vms}\n\nYou can place virtual machines (VMs) on specific nodes by using node placement rules.\n\n## Node placement examples {#node-placement-examples_virt-specifying-nodes-for-vms}\n\nThe following example YAML file snippets use `nodePlacement`, `affinity`, and `tolerations` fields to customize node placement for virtual machines.\n\n{% include \"./modules/virt-example-vm-node-placement-node-selector.md\" %} {% include \"./modules/virt-example-vm-node-placement-pod-affinity.md\" %}\n\n## Additional resources {#additional-resources_virt-specifying-nodes-for-vms}\n\n- [Specifying nodes for virtualization components](/openshift-docs-markdown/virt/post_installation_configuration/virt-node-placement-virt-components#virt-node-placement-virt-components)\n- [Placing pods on specific nodes using node selectors](/openshift-docs-markdown/nodes/scheduling/nodes-scheduler-node-selectors#nodes-scheduler-node-selectors)\n- [Controlling pod placement on nodes using node affinity rules](/openshift-docs-markdown/nodes/scheduling/nodes-scheduler-node-affinity#nodes-scheduler-node-affinity)\n- [Controlling pod placement using node taints](/openshift-docs-markdown/nodes/scheduling/nodes-scheduler-taints-tolerations#nodes-scheduler-taints-tolerations)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
