// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/advanced_vm_management/virt-configuring-virtual-gpus.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring virtual GPUs\n---\n\n# Configuring virtual GPUs {#virt-configuring-virtual-gpus}\n\nUse the NVIDIA GPU operator to create virtual GPUs (vGPUs) and assign them to virtual machines (VMs) in {{ VirtProductName }}.\n\n## Additional resources {#additional-resources_virt-configuring-virtual-gpus}\n\n- [Enabling Intel VT-X and AMD-V Virtualization Hardware Extensions in BIOS](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-troubleshooting-enabling_intel_vt_x_and_amd_v_virtualization_hardware_extensions_in_bios)\n- [MIG Support in OpenShift Container Platform](https://docs.nvidia.com/datacenter/cloud-native/openshift/latest/mig-ocp.html#)\n- [Configuring PCI passthrough](/openshift-docs-markdown/virt/managing_vms/advanced_vm_management/virt-configuring-pci-passthrough#virt-configuring-pci-passthrough)\n- [Obtaining Support from NVIDIA](https://access.redhat.com/solutions/5174941)\n- [MIG User Guide](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/supported-mig-profiles.html)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
