// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: serverless/about/about-serverless.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: \"{{ ServerlessProductName }} overview\"\n---\n\n# {{ ServerlessProductName }} overview {#about-serverless}\n\n{{ ServerlessProductName }} provides Kubernetes native building blocks that enable developers to create and deploy serverless, event-driven applications on OpenShift Container Platform. {{ ServerlessProductName }} is based on the open source [Knative project](https://knative.dev/docs/), which provides portability and consistency for hybrid and multi-cloud environments by enabling an enterprise-grade serverless platform.\n\n> [!NOTE]\n> Because {{ ServerlessProductName }} releases on a different cadence from OpenShift Container Platform, the {{ ServerlessProductName }} documentation is now available as a separate documentation set at [Red Hat OpenShift Serverless](https://docs.redhat.com/en/documentation/red_hat_openshift_serverless).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
