// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/nodes/nodes-node-tuning-operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using the Node Tuning Operator\n---\n\n# Using the Node Tuning Operator {#nodes-node-tuning-operator}\n\n{% include \"./_attributes/common-attributes.md\" %} {% include \"./_attributes/attributes-openshift-dedicated.md\" %} The Node Tuning Operator in OpenShift Container Platform helps you manage node-level tuning by orchestrating the TuneD daemon. You can use this unified interface to apply custom tuning specifications and achieve low latency performance for high-performance applications.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
