// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/oadp-use-cases/oadp-rosa-backup-restore.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Backing up workloads on OADP with OpenShift Container Platform\n---\n\n# Backing up workloads on OADP with OpenShift Container Platform {#oadp-rosa-backing-up-and-cleaning-example}\n\nTo back up and restore workloads on ROSA,\n\nyou can use {{ oadp_short }}. You can create a backup of a workload, restore it from the backup, and verify the restoration. You can also clean up the {{ oadp_short }} Operator, backup storage, and {{ aws_short }} resources when they are no longer needed.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
