// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: web_console/dynamic-plugin/deploy-plugin-cluster.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Deploy your plugin on a cluster\n---\n\n# Deploy your plugin on a cluster {#deploy-plugin-cluster_{{ context }}}\n\nYou can deploy the plugin to an OpenShift Container Platform\n\ncluster.\n\n**Additional resources**\n\n- [Service CA certificates](/openshift-docs-markdown/security/certificate_types_descriptions/service-ca-certificates#service-ca-certificates)\n- [Securing service traffic using service serving certificate secrets](/openshift-docs-markdown/security/certificates/service-serving-certificate#service-serving-certificate)\n- [Dynamic plugin API](/openshift-docs-markdown/web_console/dynamic-plugin/dynamic-plugins-reference#dynamic-plugin-api_dynamic-plugins-reference)\n\n## Additional resources {#dynamic-plugins_additional-resources}\n\n- [Understanding Helm](/openshift-docs-markdown/applications/working_with_helm_charts/understanding-helm#understaning-helm)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
