// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/storage/virt-managing-data-volume-annotations.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Managing data volume annotations\n---\n\n# Managing data volume annotations {#virt-managing-data-volume-annotations}\n\nData volume (DV) annotations allow you to manage pod behavior. You can add one or more annotations to a data volume, which then propagates to the created importer pods.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
