// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/storage/virt-configuring-storage-profile.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring storage profiles\n---\n\n# Configuring storage profiles {#virt-configuring-storage-profile}\n\nA storage profile provides recommended storage settings based on the associated storage class and is allocated for each storage class.\n\nThe Containerized Data Importer (CDI) recognizes a storage provider if it has been configured to identify and interact with the storage provider’s capabilities.\n\nFor recognized storage types, the CDI provides values that optimize the creation of PVCs. You can also configure automatic settings for the storage class by customizing the storage profile. If the CDI does not recognize your storage provider, you must configure storage profiles.\n\n> [!IMPORTANT]\n> When using {{ VirtProductName }} with {{ rh_storage_first }}, specify RBD block mode persistent volume claims (PVCs) when creating virtual machine disks. RBD block mode volumes are more efficient and provide better performance than Ceph FS or RBD filesystem-mode PVCs.\n>\n> To specify RBD block mode PVCs, use the 'ocs-storagecluster-ceph-rbd' storage class and `VolumeMode: Block`.\n\n{% include \"./modules/virt-customizing-storage-profile.md\" %} {% include \"./modules/virt-customizing-storage-profile-snapshot-class-web.md\" %} {% include \"./modules/virt-customizing-storage-profile-snapshot-class-cli.md\" %}\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
