// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/storage/virt-using-preallocation-for-datavolumes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using preallocation for data volumes\n---\n\n# Using preallocation for data volumes {#virt-using-preallocation-for-datavolumes}\n\nThe Containerized Data Importer (CDI) can preallocate disk space to improve write performance when creating data volumes. You can enable preallocation for specific data volumes.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
