// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: extensions/ce/crd-upgrade-safety.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Custom resource definition (CRD) upgrade safety\n---\n\n# Custom resource definition (CRD) upgrade safety {#crd-upgrade-safety}\n\nWhen you update a custom resource definition (CRD) provided by a cluster extension, {{ olmv1_first }} runs a CRD upgrade safety preflight check to ensure compatibility with earlier versions.\n\nThe CRD update must pass the validation checks before the change is allowed to progress on a cluster.\n\n**Additional resources**\n\n- [Updating a cluster extension](/extensions/ce/managing-ce#olmv1-updating-an-operator_managing-ce)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
