// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: extensions/ce/managing-ce.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Managing cluster extensions\n---\n\n# Managing cluster extensions {#managing-ce}\n\nYou use catalogs to access the versions, patches, and over-the-air updates for extensions and Operators. You use custom resources (CRs) to manage extensions declaratively from the CLI.\n\n**Additional resources**\n\n- [Supported extensions](/openshift-docs-markdown/extensions/ce/olmv1-supported-extensions#olmv1-supported-extensions)\n- [Projects and namespaces](/openshift-docs-markdown/authentication/using-rbac#rbac-projects-namespaces_using-rbac)\n- [Creating a service account](/openshift-docs-markdown/extensions/ce/managing-ce#olmv1-creating-a-service-account_managing-ce)\n- [Example custom resources (CRs) that specify a target version](/openshift-docs-markdown/extensions/ce/update-paths#olmv1-about-target-versions_update-paths)\n- [Support for version ranges](/openshift-docs-markdown/extensions/ce/update-paths#olmv1-version-range-support_update-paths)\n\n**Additional resources**\n\n- [Update paths](/openshift-docs-markdown/extensions/ce/update-paths#update-paths)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
