// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/ingress_load_balancing/metallb/about-advertising-ipaddresspool.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: About advertising for the IP address pools\n---\n\n# About advertising for the IP address pools {#about-advertise-for-ipaddress-pools}\n\nYou can configure MetalLB so that the IP address is advertised with layer 2 protocols, the BGP protocol, or both.\n\nWith layer 2, MetalLB provides a fault-tolerant external IP address. With BGP, MetalLB provides fault-tolerance for the external IP address and load balancing.\n\nMetalLB supports advertising by using Layer 2 and BGP for the same set of IP addresses.\n\nMetalLB provides the flexibility to assign address pools to specific BGP peers, effectively limiting advertising to a subset of nodes on the network. This allows for more complex configurations, such as facilitating the isolation of nodes or the segmentation of the network.\n\n## Additional resources {#additional-resources_about-advertiseipaddress}\n\n- [Configuring a community alias](/networking/ingress_load_balancing/metallb/metallb-configure-community-alias#metallb-configure-community-alias)\n- [Enable IP forwarding on specific interfaces](/networking/k8s_nmstate/k8s-nmstate-updating-node-network-config#nw-nmstate-enable-per-interface-ip-forwarding_k8s-nmstate-updating-node-network-config)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
