// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/ingress_load_balancing/metallb/monitoring-metallb-status.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Monitoring MetalLB configuration status {id=\"monitoring-metallb-status\"\"}\n---\n\n# Monitoring MetalLB configuration status {id=\"monitoring-metallb-status\"\"} {#monitoring-metallb-configuration-status-idmonitoring-metallb-status}\n\nAs an OpenShift Container Platform system administrator, you can monitor the operational status of your MetalLB deployment by examining its custom resources (CRs). These status fields provide information about IP address allocations, BGP peer announcements, and session states, which are important for effective monitoring and troubleshooting.\n\n## Additional resources {#_additional_resources}\n\n- [About MetalLB and the MetalLB Operator](/openshift-docs-markdown/networking/networking_operators/metallb-operator/about-metallb#about-metallb)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
