// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_aws/installing-aws-three-node.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing a three-node cluster on {{ aws_short }}\n---\n\n# Installing a three-node cluster on {{ aws_short }} {#installing-aws-three-node}\n\nIn OpenShift Container Platform version 4.22, you can install a three-node cluster on {{ aws_first }}. A three-node cluster consists of three control plane machines, which also act as compute machines.\n\nThis type of cluster provides a smaller, more resource efficient cluster, for cluster administrators and developers to use for testing, development, and production.\n\nYou can install a three-node cluster using either installer-provisioned or user-provisioned infrastructure.\n\n> [!NOTE]\n> Deploying a three-node cluster using an {{ aws_short }} Marketplace image is not supported.\n\n## Additional resources {#_additional_resources}\n\n- [Installing a cluster on AWS with customizations](/installing/installing_aws/ipi/installing-aws-customizations#installing-aws-customizations)\n- [Installing a cluster on user-provisioned infrastructure in AWS by using CloudFormation templates](/installing/installing_aws/upi/installing-aws-user-infra#installing-aws-user-infra)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
