// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_aws/installation-config-parameters-aws.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installation configuration parameters for AWS\n---\n\n# Installation configuration parameters for AWS {#installation-config-parameters-aws}\n\nBefore you deploy an OpenShift Container Platform cluster on {{ aws_first }}, you create the `install-config.yaml` file and provide parameters to customize your cluster and the platform that hosts it. You can then modify the `install-config.yaml` file to customize your cluster further.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
