// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_aws/uninstalling-cluster-aws.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Uninstalling a cluster on {{ aws_short }}\n---\n\n# Uninstalling a cluster on {{ aws_short }} {#uninstalling-cluster-aws}\n\nYou can remove a cluster that you deployed to {{ aws_first }}.\n\n## Additional resources {#installing-localzone-additional-resources}\n\n- [Working with stacks ({{ aws_short }} documentation)](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacks.html)\n- [Opt in to {{ aws_short }} Local Zones ({{ aws_short }} documentation)](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#opt-in-local-zone)\n- [{{ aws_short }} Local Zones available locations ({{ aws_short }} documentation)](https://aws.amazon.com/about-aws/global-infrastructure/localzones/locations)\n- [{{ aws_short }} Local Zones features ({{ aws_short }} documentation)](https://aws.amazon.com/about-aws/global-infrastructure/localzones/features)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
