// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_aws/upi/upi-aws-installation-reqs.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installation requirements for user-provisioned infrastructure on AWS\n---\n\n# Installation requirements for user-provisioned infrastructure on AWS {#upi-aws-installation-reqs}\n\nBefore you install OpenShift Container Platform on infrastructure that you provision, ensure that your {{ aws_first }} environment meets the installation requirements.\n\nFor a cluster that has user-provisioned infrastructure, you must deploy all of the required machines.\n\n**Additional resources**\n\n- [Optimizing storage](/openshift-docs-markdown/scalability_and_performance/optimization/optimizing-storage#optimizing-storage)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
