// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: support/managing-cluster-resources.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Managing your cluster resources\n---\n\n# Managing your cluster resources {#managing-cluster-resources}\n\nTo keep consistent behavior across your OpenShift Container Platform cluster, set global configuration options that Operators apply to all nodes.\n\n## Interacting with your cluster resources {#support-cluster-resources_managing-cluster-resources}\n\nTo view and edit the global configuration of your OpenShift Container Platform cluster, use the OpenShift CLI (`oc`) to query and change cluster resources.\n\n**Prerequisites**\n\n- You have access to the cluster as a user with the `cluster-admin` role.\n- You have access to the web console or you have installed the `oc` CLI tool.\n\n**Procedure**\n\n1. To check which configuration Operators apply to your cluster, run the following command:\n\n   ```terminal\n   $ oc api-resources -o name | grep config.openshift.io\n   ```\n2. To see what cluster resources you can configure, run the following command:\n\n   ```terminal\n   $ oc explain <resource_name>.config.openshift.io\n   ```\n3. To see the configuration of custom resource definition (CRD) objects in the cluster, run the following command:\n\n   ```terminal\n   $ oc get <resource_name>.config -o yaml\n   ```\n4. To edit the cluster resource configuration, run the following command:\n\n   ```terminal\n   $ oc edit <resource_name>.config -o yaml\n   ```\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
