// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: support/summarizing-cluster-specifications.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Summarizing cluster specifications\n---\n\n# Summarizing cluster specifications {#summarizing-cluster-specifications}\n\nTo verify the version, update history, and component status of your OpenShift Container Platform cluster, query the `clusterversion` resource.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
