// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/creating_vm/virt-creating-vms-from-cli.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating virtual machines by using the CLI\n---\n\n# Creating virtual machines by using the CLI {#virt-creating-vms-from-cli}\n\nYou can create virtual machines (VMs) from the command line by editing or creating a `VirtualMachine` manifest. You can simplify VM configuration by using an instance type in your VM manifest.\n\n> [!NOTE]\n> You can also create VMs from instance types by using the OpenShift Container Platform web console.\n\n{% include \"./modules/virt-creating-vm-cli.md\" %}\n\n## Additional resources {#additional-resources_virt-creating-vms-cli}\n\n- [SSH access for virtual machines](/openshift-docs-markdown/virt/managing_vms/ssh/virt-accessing-vm-ssh#virt-accessing-vm-ssh)\n- [Creating virtual machines from instance types](/openshift-docs-markdown/virt/creating_vm/virt-creating-vms-from-instance-types#virt-creating-vms-from-instance-types)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
