// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/creating_vm/virt-cloning-vms.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Cloning VMs\n---\n\n# Cloning VMs {#virt-cloning-vms}\n\nYou can clone virtual machines (VMs) or create new VMs from snapshots.\n\n> [!IMPORTANT]\n> Cloning a VM with a vTPM device attached to it or creating a new VM from its snapshot is not supported.\n\n## Additional resources {#additional-resources_virt-cloning-vms}\n\n- [Creating VMs by cloning PVCs](/virt/creating_vm/virt-creating-vms-by-cloning-pvcs#virt-creating-vms-by-cloning-pvcs)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
