// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/zero_trust_workload_identity_manager/zero-trust-manager-proxy.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring the egress proxy for the {{ zero_trust_full }}\n---\n\n# Configuring the egress proxy for the {{ zero_trust_full }} {#zero-trust-manager-proxy_{{ context }}}\n\nOperator Lifecycle Manager (OLM) automatically configures managed Operators with proxy settings when you use a cluster-wide egress proxy. To support proxying HTTPS connections, you can inject certificate authority (CA) certificates into the {{ zero_trust_full }}.\n\n## Additional resources {#zero-trust-manager-proxy_additional-resources}\n\n- [Configuring proxy support in Operator Lifecycle Manager](/operators/admin/olm-configuring-proxy-support#olm-configuring-proxy-support)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
