// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/zero_trust_workload_identity_manager/zero-trust-manager-overview.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Zero Trust Workload Identity Manager overview\n---\n\n# Zero Trust Workload Identity Manager overview {#zero-trust-manager-overview}\n\nThe {{ zero_trust_full }} is an OpenShift Container Platform Operator that manages the lifecycle of SPIFFE Runtime Environment (SPIRE) components. It enables workload identity management based on the Secure Production Identity Framework for Everyone (SPIFFE) standard, providing cryptographically verifiable identities (SVIDs) to workloads running in OpenShift Container Platform clusters.\n\nThe following are  components of the {{ zero_trust_full }} architecture:\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
