// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/zero_trust_workload_identity_manager/zero-trust-manager-mesh-integration.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Integrating Red Hat OpenShift Service Mesh with Zero Trust Workload Identity Manager in a single-cluster\n---\n\n# Integrating Red Hat OpenShift Service Mesh with Zero Trust Workload Identity Manager in a single-cluster {#zero-trust-manager-mesh-integration_{{ context }}}\n\nDeploy and configure {{ spire_full }} as the certificate authority (CA) for {{ SMProductName }} workloads, replacing the Istio built-in CA with SPIFFE-compliant identities and automatically rotated short-lived certificates.\n\n## Additional resources {#additional-resources-service-mesh-zero-trust_zero-trust-manager-mesh-integration}\n\n- [About OpenShift Service Mesh](https://docs.redhat.com/en/documentation/red_hat_openshift_service_mesh/3.3/html-single/about/index)\n- [Installing OpenShift Service Mesh](https://docs.redhat.com/en/documentation/red_hat_openshift_service_mesh/3.3/html-single/installing/index#ossm-supported-platforms-configurations)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
