// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: authentication/configuring-internal-oauth.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring the internal OAuth server\n---\n\n# Configuring the internal OAuth server {#configuring-internal-oauth}\n\nThe OpenShift Container Platform Control Plane includes a built-in OAuth server for user authentication. You can configure token duration, inactivity timeouts, and customize the OAuth server URL.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
