// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: authentication/managing-oauth-access-tokens.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Managing user-owned OAuth access tokens\n---\n\n# Managing user-owned OAuth access tokens {#managing-oauth-access-tokens}\n\nReview and manage your user-owned OAuth access tokens to monitor active sessions, verify token scopes, and revoke tokens that are no longer needed.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
