// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: authentication/understanding-identity-provider.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Understanding identity provider configuration\n---\n\n# Understanding identity provider configuration {#understanding-identity-provider}\n\nAs an administrator, you can configure OAuth to specify an identity provider after you install your cluster. Developers and administrators obtain OAuth access tokens to authenticate themselves to the API.\n\nThe OpenShift Container Platform master includes a built-in OAuth server.\n\n**Additional resources**\n\n- [How to create user, identity and map user and identity in LDAP authentication for `mappingMethod` as `lookup` inside the OAuth manifest](https://access.redhat.com/solutions/6006921)\n- [How to create user, identity and map user and identity in OIDC authentication for `mappingMethod` as `lookup`](https://access.redhat.com/solutions/7072510)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
