// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: authentication/understanding-authentication.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Understanding authentication\n---\n\n# Understanding authentication {#understanding-authentication}\n\nTo interact with OpenShift Container Platform, log in so the authentication layer can verify your identity. The authorization layer then uses your identity to determine which actions and resources you can access.\n\nAs an administrator, you can configure authentication for OpenShift Container Platform.\n\n**Additional resources**\n\n- [User impersonation (Kubernetes documentation)](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
