// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: authentication/managing_cloud_provider_credentials/cco-mode-mint.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: About the Cloud Credential Operator in mint mode\n---\n\n# About the Cloud Credential Operator in mint mode {#cco-mode-mint}\n\nYou can use the Cloud Credential Operator (CCO) in mint mode to create and reconcile credentials for components in the cluster.\n\nMint mode is the default CCO credentials mode for OpenShift Container Platform on platforms that support it. Mint mode supports {{ aws_first }} and {{ gcp_first }} clusters.\n\n## Additional resources {#additional-resources_cco-mode-mint}\n\n- [Removing cloud provider credentials](/openshift-docs-markdown/post_installation_configuration/changing-cloud-credentials-configuration#manually-removing-cloud-creds_changing-cloud-credentials-configuration)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
