// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: edge_computing/image_base_install/ibi-preparing-for-image-based-install.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Preparing for image-based installation for {{ sno }} clusters\n---\n\n# Preparing for image-based installation for {{ sno }} clusters {#ibi-preparing-for-image-based-install}\n\nTo prepare for an image-based installation for {{ sno }} clusters, you must complete the following tasks:\n\n- Create a seed image by using the {{ lcao }}.\n- Verify that all software components meet the required versions. For further information, see \"Software prerequisites for an image-based installation and deployment\".\n\n**Additional resources**\n\n- [Software prerequisites for an image-based installation and deployment](/openshift-docs-markdown/edge_computing/image_base_install/ibi-understanding-image-based-install#ztp-image-based-upgrade-prereqs_ibi-understanding-image-based-install)\n\n## Installing the {{ lcao }} {#_installing_the_lcao}\n\nUse the {{ lcao }} to generate a seed image from a seed cluster. You can install the {{ lcao }} using the {{ oc_first }} or the web console.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
