// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: rest_api/template_apis/template-apis-index.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Template APIs\n---\n\n# Template APIs {#template-apis}\n\n## BrokerTemplateInstance \\[template.openshift.io/v1\\] {#_brokertemplateinstance_templateopenshiftiov1}\n\nDescription\n:   BrokerTemplateInstance holds the service broker-related state associated with a TemplateInstance.  BrokerTemplateInstance is part of an experimental API.\n\n    Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).\n\nType\n:   ```\n    `object`\n    ```\n\n## PodTemplate \\[v1\\] {#_podtemplate_v1}\n\nDescription\n:   PodTemplate describes a template for creating copies of a predefined pod.\n\nType\n:   ```\n    `object`\n    ```\n\n## Template \\[template.openshift.io/v1\\] {#_template_templateopenshiftiov1}\n\nDescription\n:   Template contains the inputs needed to produce a Config.\n\n    Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).\n\nType\n:   ```\n    `object`\n    ```\n\n## TemplateInstance \\[template.openshift.io/v1\\] {#_templateinstance_templateopenshiftiov1}\n\nDescription\n:   TemplateInstance requests and records the instantiation of a Template. TemplateInstance is part of an experimental API.\n\n    Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).\n\nType\n:   ```\n    `object`\n    ```\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
