// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/hardware_networks/configuring-sriov-device.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring an SR-IOV network device\n---\n\n# Configuring an SR-IOV network device {#configuring-sriov-device}\n\nYou can configure a Single Root I/O Virtualization (SR-IOV) device in your cluster.\n\nBefore you perform any tasks in the following documentation, ensure that you [installed the SR-IOV Network Operator](/openshift-docs-markdown/networking/networking_operators/sr-iov-operator/installing-sriov-operator#installing-sriov-operator).\n\n**Additional resources**\n\n- [Understanding how to update labels on nodes](/openshift-docs-markdown/nodes/nodes/nodes-nodes-working#nodes-nodes-working-updating_nodes-nodes-working)\n\n**Additional resources**\n\n- [Using CPU Manager](/openshift-docs-markdown/scalability_and_performance/using-cpu-manager#using-cpu-manager)\n\n**Additional resources**\n\n- [Configuring an SR-IOV network attachment](/openshift-docs-markdown/networking/hardware_networks/configuring-sriov-net-attach#configuring-sriov-net-attach)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
