// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/hardware_networks/configuring-hardware-offloading.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring hardware offloading\n---\n\n# Configuring hardware offloading {#configuring-hardware-offloading}\n\nAs a cluster administrator, you can configure hardware offloading on compatible nodes to increase data processing performance and reduce load on host CPUs.\n\nBefore you perform any tasks in the following documentation, ensure that you [installed the SR-IOV Network Operator](/openshift-docs-markdown/networking/networking_operators/sr-iov-operator/installing-sriov-operator#installing-sriov-operator).\n\n**Additional resources**\n\n- [Installing the SR-IOV Network Operator](/openshift-docs-markdown/networking/networking_operators/sr-iov-operator/installing-sriov-operator#installing-sriov-operator)\n- [About the OVN-Kubernetes network plugin](/openshift-docs-markdown/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes#about-ovn-kubernetes)\n- [OVN-Kubernetes network plugin configuration](/openshift-docs-markdown/networking/networking_operators/cluster-network-operator#gatewayConfig-object_cluster-network-operator)\n\n<a name=\"additional-resources_using-vf-improve-network-traffic-performance\"></a>**Additional resources**\n\n- [SR-IOV network node configuration object](/openshift-docs-markdown/networking/hardware_networks/configuring-sriov-device#nw-sriov-networknodepolicy-object_configuring-sriov-device)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
