// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/oadp-vmdp/oadp-using-vmdp.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using {{ oadp_short }} virtual machine data protection\n---\n\n# Using {{ oadp_short }} virtual machine data protection {#oadp-using-vmdp}\n\nInstall the {{ oadp_full }} virtual machine data protection (VMDP) command-line interface (CLI), configure a backup storage location, and back up and restore data from within your VM. This helps you to manage your own VM backups independently.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
