// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: openshift_images/managing_images/tagging-images.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Tagging images\n---\n\n# Tagging images {#tagging-images}\n\nImage tags identify specific versions of container images in image streams. You can use image tags to organize images and control which versions your builds and deployments use.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
