// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: openshift_images/managing_images/using-image-pull-secrets.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using image pull secrets\n---\n\n# Using image pull secrets {#using-image-pull-secrets}\n\nTo authenticate with container registries and pull images across OpenShift Container Platform projects or from secured registries, you can configure and use image pull secrets. You first obtain the registry authentication credentials, which are typically found in the `~/.docker/config.json` file for Docker or the `~/.config/containers/auth.json` file for Podman, created by the {{ cluster_manager_url_pull }} process. This content is then used to create or update the global `pullSecret` object within your cluster.\n\n> [!NOTE]\n> If you are using the {{ product_registry }} and are pulling from image streams located in the same project, then your pod service account should already have the correct permissions. No additional action should be required.\n\n**Additional resources**\n\n- [Quay.io container registry](https://quay.io/)\n- [Red Hat container registry](https://registry.redhat.io)\n- [Transferring cluster ownership](https://docs.redhat.com/en/documentation/openshift_cluster_manager/1-latest/html-single/managing_clusters/index#transferring-cluster-ownership_downloading-and-updating-pull-secrets)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
