// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: machine_management/machine-phases-lifecycle.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Machine phases and lifecycle\n---\n\n# Machine phases and lifecycle {#machine-phases-lifecycle}\n\nMachines move through a *lifecycle* that has several defined phases. Understanding the machine lifecycle and its phases can help you verify whether a procedure is complete or troubleshoot undesired behavior. In OpenShift Container Platform, the machine lifecycle is consistent across all supported cloud providers.\n\n## Additional resources {#_additional_resources}\n\n- [Lifecycle hooks for the machine deletion phase](/openshift-docs-markdown/machine_management/deleting-machine#machine-lifecycle-hook-deletion_deleting-machine)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
