// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: machine_management/modifying-machineset.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Modifying a compute machine set\n---\n\n# Modifying a compute machine set {#modifying-machineset}\n\nTo add labels, change the instance type, change block storage, or make other changes, you can modify a compute machine set.\n\n> [!NOTE]\n> If you need to scale a compute machine set without making other changes, see \"Manually scaling a compute machine set\".\n\n**Additional resources**\n\n- [Lifecycle hooks for the machine deletion phase](/machine_management/deleting-machine#machine-lifecycle-hook-deletion_deleting-machine)\n- [Manually scaling a compute machine set](/machine_management/manually-scaling-machineset#machineset-manually-scaling_manually-scaling-machineset)\n- [Controlling pod placement using the scheduler](/nodes/scheduling/nodes-scheduler-about#nodes-scheduler-about)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
