// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: updating/updating_a_cluster/disconnected-update.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Updating a cluster in a disconnected environment\n---\n\n# Updating a cluster in a disconnected environment {#updating-disconnected-cluster}\n\nYou can update a cluster in an environment without access to the internet by taking additional steps to prepare your environment.\n\nFor information about updating a cluster in a disconnected environment, see [About cluster updates in a disconnected environment](/disconnected/updating/index#about-disconnected-updates).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
