// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/compliance_operator/compliance-operator-release-notes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Release notes for the Compliance Operator\n---\n\n# Release notes for the Compliance Operator {#compliance-operator-release-notes}\n\nThe Compliance Operator lets OpenShift Container Platform administrators describe the required compliance state of a cluster and provides them with an overview of gaps and ways to remediate them.\n\nThese release notes track the development of the Compliance Operator in the OpenShift Container Platform.\n\n## Additional resources {#compliance-operator-release-notes_additional-resources}\n\n- [Understanding the Compliance Operator](/security/compliance_operator/co-concepts/compliance-operator-understanding#understanding-compliance-operator)\n- [Updating the Compliance Operator](/security/compliance_operator/co-management/compliance-operator-updating#olm-preparing-upgrade_compliance-operator-updating)\n- [Product Compliance](https://access.redhat.com/compliance)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
