// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: storage/persistent_storage_local/ways-to-provision-local-storage.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Local storage overview\n---\n\n# Local storage overview {#ways-to-provision-local-storage_{{ context }}}\n\nLocal storage provides direct access to disks attached to cluster nodes, delivering lower latency and higher throughput than network-attached or cloud-based storage. Use local storage for performance-sensitive workloads, single-node clusters, or environments without cloud storage infrastructure.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
