// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance/cnf-tuning-low-latency-hosted-cp-nodes-with-perf-profile.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Tuning hosted control planes for low latency with the performance profile\n---\n\n# Tuning hosted control planes for low latency with the performance profile {#cnf-tuning-low-latency-hosted-cp-nodes-with-perf-profile}\n\nTune hosted control planes for low latency by applying a performance profile. With the performance profile, you can restrict CPUs for infrastructure and application containers and configure huge pages, Hyper-Threading, and CPU partitions for latency-sensitive processes.\n\n**Additional resources**\n\n- [Gathering data about your cluster](/support/gathering-cluster-data#nodes-nodes-managing)\n\n**Additional resources**\n\n- [Performance Profile Creator arguments](/scalability_and_performance/cnf-tuning-low-latency-nodes-with-perf-profile#performance-profile-creator-arguments_cnf-tuning-low-latency-nodes-with-perf-profile)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
