// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance/cnf-understanding-low-latency.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Understanding low latency tuning for cluster nodes\n---\n\n# Understanding low latency tuning for cluster nodes {#cnf-understanding-low-latency}\n\nBy first understanding low latency tuning for cluster nodes, you can then use edge computing as a key role in reducing latency and congestion problems and improving application performance for telco and 5G network applications.\n\nMaintaining a network architecture with the lowest possible latency is key for meeting the network performance requirements of 5G. Compared to 4G technology, with an average latency of 50 ms, 5G is targeted to reach latency of 1 ms or less. This reduction in latency boosts wireless throughput by a factor of 10.\n\n**Additional resources**\n\n- [Tuning for Zero Packet Loss in {{ rh_openstack_first }}](https://www.redhat.com/en/blog/tuning-zero-packet-loss-red-hat-openstack-platform-part-1)\n\n**Additional resources**\n\n- [Configuring Hyper-Threading for a cluster](/scalability_and_performance/cnf-tuning-low-latency-nodes-with-perf-profile#cnf-configuring-hyperthreading-for-a-cluster_cnf-tuning-low-latency-nodes-with-perf-profile)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
