// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance/cnf-debugging-low-latency-tuning-status.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Debugging low latency node tuning status\n---\n\n# Debugging low latency node tuning status {#cnf-debugging-low-latency-tuning-status}\n\nUse the `PerformanceProfile` custom resource (CR) status fields for reporting tuning status and debugging latency issues in a cluster node.\n\n**Additional resources**\n\n- [Gathering data about your cluster with the `must-gather` tool](/support/gathering-cluster-data#gathering-cluster-data)\n- [Managing nodes with MachineConfig and KubeletConfig CRs](/nodes/nodes/nodes-nodes-managing#nodes-nodes-managing)\n- [Using the Node Tuning Operator](/scalability_and_performance/using-node-tuning-operator#using-node-tuning-operator)\n- [Configuring huge pages at boot time](/scalability_and_performance/what-huge-pages-do-and-how-they-are-consumed-by-apps#configuring-huge-pages_huge-pages)\n- [How huge pages are consumed by apps](/scalability_and_performance/what-huge-pages-do-and-how-they-are-consumed-by-apps#how-huge-pages-are-consumed-by-apps_huge-pages)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
