// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance/node-observability-operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using the Node Observability Operator\n---\n\n# Using the Node Observability Operator {#using-node-observability-operator}\n\nThe Node Observability Operator collects and stores CRI-O and Kubelet profiling or metrics from scripts of compute nodes.\n\nWith the Node Observability Operator, you can query the profiling data, enabling analysis of performance trends in CRI-O and Kubelet. It supports debugging performance-related issues and executing embedded scripts for network metrics by using the `run` field in the custom resource definition. To enable CRI-O and Kubelet profiling or scripting, you can configure the `type` field in the custom resource definition.\n\n## Additional resources {#additional-resources_node-observability-operator}\n\n- [Collecting worker metrics using the Node Observability Operator](https://access.redhat.com/solutions/5343671)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
