// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance/scaling-worker-latency-profiles.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Improving cluster stability in high latency environments using worker latency profiles\n---\n\n# Improving cluster stability in high latency environments using worker latency profiles {#scaling-worker-latency-profiles}\n\nTo improve cluster stability in high latency environments, apply worker latency profiles.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
