// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance/using-cpu-manager.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using CPU Manager and Topology Manager\n---\n\n# Using CPU Manager and Topology Manager {#using-cpu-manager}\n\nCPU Manager manages groups of CPUs and constrains workloads to specific CPUs.\n\nCPU Manager is useful for workloads that have some of these attributes:\n\n- Require as much CPU time as possible.\n- Are sensitive to processor cache misses.\n- Are low-latency network applications.\n- Coordinate with other processes and benefit from sharing a single processor cache.\n\nTopology Manager collects hints from the CPU Manager, Device Manager, and other Hint Providers to align pod resources, such as CPU, SR-IOV VFs, and other device resources, for all Quality of Service (QoS) classes on the same non-uniform memory access (NUMA) node.\n\nTopology Manager uses topology information from the collected hints to decide if a pod can be accepted or rejected on a node, based on the configured Topology Manager policy and pod resources requested.\n\nTopology Manager is useful for workloads that use hardware accelerators to support latency-critical execution and high throughput parallel computation.\n\nTo use Topology Manager you must configure CPU Manager with the `static` policy.\n\n**Additional resources**\n\n- [Topology Manager policies](/openshift-docs-markdown/scalability_and_performance/using-cpu-manager#topology-manager-policies_using-cpu-manager-and-topology-manager)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
