// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance/using-node-tuning-operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using the Node Tuning Operator\n---\n\n# Using the Node Tuning Operator {#using-node-tuning-operator}\n\nLearn about the Node Tuning Operator and how you can use it to manage node-level tuning by orchestrating the tuned daemon.\n\n**Additional resources**\n\n- [Coordinating reboots for configuration changes](/openshift-docs-markdown/edge_computing/policygenerator_for_ztp/ztp-configuring-managed-clusters-policygenerator#ztp-coordinating-reboots-for-config-changes_ztp-configuring-managed-clusters-policygenerator)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
