// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_on_prem_assisted/installing-on-prem-assisted.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing an on-premise cluster using the {{ ai_full }}\n---\n\n# Installing an on-premise cluster using the {{ ai_full }} {#installing-on-prem-assisted}\n\nYou can install OpenShift Container Platform on on-premise hardware or on-premise VMs by using the {{ ai_full }} for OpenShift Container Platform.\n\nThe {{ ai_full }} is a user-friendly installation solution offered on the {{ hybrid_console_second }}. The {{ ai_full }} reduces installation complexity, enabling users to deploy and configure OpenShift Container Platform clusters with minimal manual intervention.\n\nFor access to the {{ ai_full }} user interface and documentation, see *Additional resources*.\n\n**Additional resources**\n\n- [{{ ai_full }} user interface](https://console.redhat.com/openshift/assisted-installer/clusters/~new)\n- [{{ ai_full }} documentation](https://access.redhat.com/documentation/en-us/assisted_installer_for_openshift_container_platform)\n- [{{ hybrid_console }}](https://console.redhat.com)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
