// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_on_prem_assisted/installing-on-prem-assisted.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing an on-premise cluster using the {{ ai_full }}\n---\n\n# Installing an on-premise cluster using the Assisted Installer {#installing-on-prem-assisted}\n\nYou can install OpenShift Container Platform on on-premise hardware or on-premise VMs by using the Assisted Installer for OpenShift Container Platform.\n\nThe Assisted Installer is a user-friendly installation solution offered on the Hybrid Cloud Console. The Assisted Installer reduces installation complexity, enabling users to deploy and configure OpenShift Container Platform clusters with minimal manual intervention.\n\nFor access to the Assisted Installer user interface and documentation, see *Additional resources*.\n\n**Additional resources**\n\n- [Assisted Installer user interface](https://console.redhat.com/openshift/assisted-installer/clusters/~new)\n- [Assisted Installer documentation](https://access.redhat.com/documentation/en-us/assisted_installer_for_openshift_container_platform)\n- [Red Hat Hybrid Cloud Console](https://console.redhat.com)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
