// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/oadp-self-service/oadp-self-service-troubleshooting.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: \"{{ oadp_short }} Self-Service troubleshooting\"\n---\n\n# {{ oadp_short }} Self-Service troubleshooting {#oadp-self-service-troubleshooting}\n\nResolve common errors and issues when using {{ oadp_short }} Self-Service by following troubleshooting procedures for backup storage locations and backup operations. This helps you quickly identify and fix problems independently.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
