// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/oadp-self-service/oadp-self-service-cluster-admin-use-cases.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: \"{{ oadp_short }} Self-Service cluster admin use cases\"\n---\n\n# {{ oadp_short }} Self-Service cluster admin use cases {#oadp-self-service-cluster-admin-use-cases}\n\nConfigure and manage {{ oadp_short }} Self-Service by enabling the feature, reviewing backup storage location requests, and enforcing policy templates. This helps you provide Self-Service backup capabilities while maintaining administrative control.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
