// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: web_console/adding-user-preferences.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Adding user preferences\n---\n\n# Adding user preferences {#adding-user-preferences}\n\nYou can change the default preferences for your profile to meet your requirements. You can set your default project, topology view (graph or list), editing medium (form or YAML), language preferences, and resource type.\n\nThe changes made to the user preferences are automatically saved.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
