// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: web_console/web-console.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Accessing the web console\n---\n\n# Accessing the web console {#web-console}\n\nThe OpenShift Container Platform web console is a user interface accessible from a web browser. You can use the web console to visualize, browse, and manage the contents of projects.\n\n## Prerequisites {#_prerequisites}\n\n- You must use one of the following supported web browsers: Edge, Chrome, Safari, or Mozilla Firefox. Internet Explorer 11 and earlier is not supported.\n- Review the OpenShift Container Platform 4.x Tested Integrations page before you create the supporting infrastructure for your cluster.\n\n**Additional resources**\n\n- [OpenShift Container Platform 4.x Tested Integrations](https://access.redhat.com/articles/4128421)\n- [Enabling feature sets using the web console](/nodes/clusters/nodes-cluster-enabling-features#nodes-cluster-enabling-features)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
