// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: machine_management/user_infra/adding-vsphere-compute-user-infra.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Adding compute machines to vSphere manually\n---\n\n# Adding compute machines to vSphere manually {#adding-vsphere-compute-user-infra}\n\nYou can add more compute machines to your OpenShift Container Platform cluster on VMware vSphere manually.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
