// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: machine_management/user_infra/adding-aws-compute-user-infra.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Adding compute machines to AWS by using CloudFormation templates\n---\n\n# Adding compute machines to AWS by using CloudFormation templates {#adding-aws-compute-user-infra}\n\nTo scale your OpenShift Container Platform cluster on {{ aws_first }} after user-provisioned installation, you can add compute machines by creating CloudFormation stacks from your installation templates. You can then approve certificate signing requests so the new nodes join the cluster.\n\n## Prerequisites {#prerequisites_adding-aws-compute-user-infra}\n\n- You installed your cluster on AWS by using the provided [AWS CloudFormation templates](/installing/installing_aws/upi/installing-aws-user-infra#installing-aws-user-infra).\n- You have the JSON file and CloudFormation template that you used to create the compute machines during cluster installation. If you do not have these files, you must recreate them by following the instructions in the [installation procedure](/installing/installing_aws/upi/installing-aws-user-infra#installing-aws-user-infra).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
