// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: machine_management/user_infra/adding-bare-metal-compute-user-infra.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Adding compute machines to bare metal\n---\n\n# Adding compute machines to bare metal {#adding-bare-metal-compute-user-infra}\n\nTo scale your OpenShift Container Platform cluster on bare-metal or platform-agnostic infrastructure, you can add more compute machines. Create {{ op_system }} machines, then approve their certificate signing requests.\n\n**Additional resources**\n\n- [How does one set up a serial terminal and/or console in Red Hat Enterprise Linux? (Red Hat Knowledgebase article)](https://access.redhat.com/articles/7212)\n- [`IMAGE_GZIP` option in iPXE (iPXE documentation)](https://ipxe.org/buildcfg/image_gzip)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
