// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_vsphere/installing-vsphere-three-node.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing a three-node cluster on vSphere\n---\n\n# Installing a three-node cluster on vSphere {#installing-vsphere-three-node}\n\nIn OpenShift Container Platform version 4.22, you can install a three-node cluster on VMware vSphere. A three-node cluster consists of three control plane machines, which also act as compute machines. This type of cluster provides a smaller, more resource efficient cluster, for cluster administrators and developers to use for testing, development, and production.\n\nYou can install a three-node cluster using either installer-provisioned or user-provisioned infrastructure.\n\n## Additional resources {#_additional_resources}\n\n- [Installing a cluster on vSphere with customizations](/installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-customizations#installing-vsphere-installer-provisioned-customizations)\n- [Installing a cluster on vSphere with user-provisioned infrastructure](/installing/installing_vsphere/upi/installing-vsphere#installing-vsphere)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
