// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_vsphere/installation-config-parameters-vsphere.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installation configuration parameters for vSphere\n---\n\n# Installation configuration parameters for vSphere {#installation-config-parameters-vsphere}\n\nBefore you deploy an OpenShift Container Platform cluster on vSphere, you can configure parameters to customize your cluster and the platform that hosts it. The installation program uses the information in the `install-config.yaml` file to provision required infrastructure and deploy cluster components. When you create the `install-config.yaml` file, you can configure the values for your required parameters through the command line. Edit the `install-config.yaml` file to customize your cluster further before installation begins.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
