// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_vsphere/vsphere-post-installation-encryption.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Enabling encryption on a vSphere cluster\n---\n\n# Enabling encryption on a vSphere cluster {#vsphere-post-installation-encryption}\n\nYou can encrypt your virtual machines after installing OpenShift Container Platform 4.22 on vSphere by draining and shutting down your nodes one at a time. While each virtual machine is shutdown, you can enable encryption in the vCenter web interface.\n\n## Additional resources {#additional-resources_enabling-encryption-installation}\n\n- [Evacuating pods on nodes](/openshift-docs-markdown/nodes/nodes/nodes-nodes-working#nodes-nodes-working-evacuating_nodes-nodes-working)\n- [vSphere persistent disks encryption](/openshift-docs-markdown/storage/container_storage_interface/persistent-storage-csi-vsphere#vsphere-pv-encryption)\n- [Requirements for encrypting virtual machines](/openshift-docs-markdown/installing/installing_vsphere/upi/upi-vsphere-installation-reqs#installation-vsphere-encrypted-vms_upi-vsphere-installation-reqs)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
