// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: operators/understanding/olm/olm-workflow.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Operator Lifecycle Manager workflow\n---\n\n# Operator Lifecycle Manager workflow {#olm-workflow}\n\nThe Operator Lifecycle Manager (OLM) resolves Operator installs and upgrades in OpenShift Container Platform. The OLM lifecycle involves interacting with catalog sources, subscriptions, and cluster service versions (CSVs).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
