// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: machine_management/creating_machinesets/creating-machineset-aws.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating a compute machine set on {{ aws_short }}\n---\n\n# Creating a compute machine set on {{ aws_short }} {#creating-machineset-aws}\n\nYou can create a different compute machine set to serve a specific purpose in your OpenShift Container Platform cluster on {{ aws_first }}. For example, you might create infrastructure machine sets and related machines so that you can move supporting workloads to the new machines.\n\n**Additional resources**\n\n- [Manually updating the boot image](/machine_configuration/mco-update-boot-images-manual#mco-update-boot-images-manual)\n\n**Additional resources**\n\n- [Cluster autoscaler resource definition](/machine_management/applying-autoscaling#cluster-autoscaler-cr_applying-autoscaling)\n\n**Additional resources**\n\n- [Use the Instance Metadata Service to access instance metadata ({{ aws_short }} documentation)](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html)\n- [Boot image management](/machine_configuration/mco-update-boot-images#mco-update-boot-images)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
