// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/network_security/network_policy/about-network-policy.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating a network policy\n---\n\n# Creating a network policy {#about-network-policy}\n\nTo restrict traffic between workloads and improve application security, configure `NetworkPolicy` objects for your cluster. Network policies define the allowed ingress and egress connections for selected pods and help isolate applications within namespaces.\n\nAs a developer, you can define network policies that restrict traffic to pods in your cluster.\n\n## Additional resources {#about-network-policy-additional-resources}\n\n- [Creating a network policy](/networking/network_security/network_policy/creating-network-policy#creating-network-policy)\n- [Defining a default network policy for projects](/networking/network_security/network_policy/default-network-policy#default-network-policy)\n- [Projects and namespaces](/authentication/using-rbac#rbac-projects-namespaces_using-rbac)\n- [Configuring multitenant isolation with network policy](/networking/network_security/network_policy/multitenant-network-policy#multitenant-network-policy)\n- [NetworkPolicy API](/rest_api/network_apis/networkpolicy-networking-k8s-io-v1#networkpolicy-networking-k8s-io-v1)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
