// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/network_security/network_policy/deleting-network-policy.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Deleting a network policy\n---\n\n# Deleting a network policy {#deleting-network-policy}\n\nAs a cluster administrator, you can delete a network policy from a namespace.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
