// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/network_security/network_policy/editing-network-policy.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Editing a network policy\n---\n\n# Editing a network policy {#editing-network-policy}\n\nAs a cluster administrator, you can edit an existing network policy for a namespace.\n\n## Additional resources {#editing-network-policy-additional-resources}\n\n- [Creating a network policy](/openshift-docs-markdown/networking/network_security/network_policy/creating-network-policy#creating-network-policy)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
