// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/network_security/network_policy/multitenant-network-policy.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring multitenant isolation with network policy\n---\n\n# Configuring multitenant isolation with network policy {#multitenant-network-policy}\n\nYou can configure network policies to isolate network traffic between projects in a multitenant cluster. This isolation helps prevent unauthorized communication between workloads in different namespaces.\n\nAs a cluster administrator, you can configure your network policies to provide multitenant network isolation.\n\n> [!NOTE]\n> Configuring network policies as described in this section provides network isolation similar to the multitenant mode of OpenShift SDN in previous versions of OpenShift Container Platform.\n\n## Additional resources {#multitenant-network-policy-additional-resources}\n\n- [Defining a default network policy for a project](/networking/network_security/network_policy/default-network-policy#default-network-policy)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
