// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/network_security/network_policy/viewing-network-policy.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Viewing a network policy\n---\n\n# Viewing a network policy {#viewing-network-policy}\n\nAs a cluster administrator, you can view a network policy for a namespace.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
