// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_two_node_cluster/installing_tnf/install-post-tnf.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Post-installation troubleshooting and recovery\n---\n\n# Post-installation troubleshooting and recovery {#installing-post-tnf}\n\nYou can troubleshoot and restore  a two-node OpenShift Container Platform cluster with fencing (TNF) after a disruption event. Manually recover services when automated recovery is unavailable, replace degraded control plane nodes, and use the `fencing_validator` script to verify cluster health.\n\n**Additional resources**\n\n- [Restoring etcd from a backup](/openshift-docs-markdown/backup_and_restore/control_plane_backup_and_restore/backing-up-etcd#backup-etcd-restoring_backing-up-etcd)\n- [Verifying etcd health in a two-node OpenShift cluster with fencing](/openshift-docs-markdown/installing/installing_two_node_cluster/installing_tnf/install-post-tnf#installation-verifying-etcd-health_install-post-tnf)\n- [Gathering an sosreport for OpenShift Container Platform](/openshift-docs-markdown/support/gathering-cluster-data#about-sosreport_gathering-cluster-data)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
