// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_two_node_cluster/installing_tnf/operating-a-degraded-tnf.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Operating a degraded two-node OpenShift cluster with fencing\n---\n\n# Operating a degraded two-node OpenShift cluster with fencing {#operating-a-degraded-tnf}\n\nA two-node OpenShift cluster with fencing (TNF) enters a `degraded` state when one of its two control plane nodes becomes unavailable. The remaining node continues to host the active control plane; however, the cluster loses its high-availability (HA) redundancy until the failed node recovers.\n\nDegraded operation is an intentional design state rather than a system failure. In this state, the cluster remains functional and core services continue to operate. Only specific capabilities that strictly require two-node redundancy are temporarily unavailable.\n\n> [!IMPORTANT]\n> A degraded cluster has zero fault tolerance. If the surviving node also fails, the cluster fails. Restore the second node as soon as possible. Degraded operation is a temporary recovery window, not a long-term steady state.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
