// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: ai_workloads.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Overview of AI workloads on OpenShift Container Platform\n---\n\n# Overview of AI workloads on OpenShift Container Platform {#ai-workloads-about}\n\nOpenShift Container Platform provides a secure, scalable foundation for running artificial intelligence (AI) workloads across training, inference, and data science workflows.\n\n**Additional resources**\n\n- [Introduction to {{ kueue_name }}](/openshift-docs-markdown/ai_workloads/kueue/about-kueue#about-kueue)\n- [{{ lws_operator }} overview](/openshift-docs-markdown/ai_workloads/leader_worker_set/index#lws-about)\n- [{{ js_operator }} overview](/openshift-docs-markdown/ai_workloads/jobset_operator/index#js-about)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
