// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: disconnected.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: About disconnected installation mirroring\n---\n\n# About disconnected installation mirroring {#installing-mirroring-disconnected-about}\n\nAs a cluster administrator, you can use a mirror registry to ensure that your clusters only use container images that satisfy your organizational controls on external content.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
