// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: extensions.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Extensions overview\n---\n\n# Extensions overview {#extensions-overview}\n\nYou can configure the operating system of your nodes and extend capabilities to your cluster by using pre-packaged software extensions. These extensions include ready-to-use tools that customize your environment for your requirements.\n\n{{ olm_first }} has been included with OpenShift Container Platform 4 since its initial release. OpenShift Container Platform 4.22 includes components for a next-generation iteration of {{ olm }} as a Generally Available (GA) feature, known during this phase as *{{ olmv1 }}*. This updated framework evolves many of the concepts that have been part of previous versions of {{ olm }} and adds new capabilities.\n\n**Additional resources**\n\n- [Operator Controller](/openshift-docs-markdown/extensions/arch/operator-controller#operator-controller)\n- [Catalogd](/openshift-docs-markdown/extensions/arch/catalogd#catalogd)\n- [Updating a cluster extension](/openshift-docs-markdown/extensions/ce/managing-ce#olmv1-updating-an-operator_managing-ce)\n- [Installing extensions](/openshift-docs-markdown/extensions/ce/managing-ce#managing-ce)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
