// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: registry.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: \"{{ product_registry }} overview\"\n---\n\n# {{ product_registry }} overview {#registry-overview}\n\nOpenShift Container Platform can build images from your source code, deploy them, and manage their lifecycle. OpenShift Container Platform provides an internal, integrated container image registry that can be deployed in your OpenShift Container Platform environment to locally manage images. The overview section includes {{ product_registry }} reference information and links for registries commonly used with OpenShift Container Platform.\n\n**Additional resources**\n\n- [Image Registry Operator in OpenShift Container Platform](/openshift-docs-markdown/registry/configuring-registry-operator#configuring-registry-operator)\n\n**Additional resources**\n\n- [Quay.io](https://quay.io)\n- [{{ quay }} product documentation](https://access.redhat.com/documentation/en-us/red_hat_quay/)\n\n**Additional resources**\n\n- [Registry service accounts](https://access.redhat.com/terms-based-registry/)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
