// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: scalability_and_performance.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: OpenShift Container Platform scalability and performance overview\n---\n\n# OpenShift Container Platform scalability and performance overview {#scalability-and-performance-overview}\n\nOpenShift Container Platform provides best practices and tools to help you optimize the performance and scale of your clusters.\n\nThe following documentation provides information on recommended performance and scalability practices, reference design specifications, optimization, and low latency tuning.\n\nTo contact Red Hat support, see \"Getting support\".\n\n> [!NOTE]\n> Some performance and scalability Operators have release cycles that are independent from OpenShift Container Platform release cycles. For more information, see \"OpenShift Operators\".\n\n## Additional resources {#additional-resources_index}\n\n- [Getting support](/openshift-docs-markdown/support/getting-support#getting-support)\n- [OpenShift Operators](https://access.redhat.com/support/policy/updates/openshift_operators)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
