// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: tutorials.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Tutorials overview\n---\n\n# Tutorials overview {#tutorials-overview}\n\nTo learn how to use OpenShift Container Platform, review the tutorials and other learning resources that are available.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
