// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: welcome.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: OpenShift Container Platform 4.22 Documentation\n---\n\n# OpenShift Container Platform 4.22 Documentation {#welcome-index}\n\ntrue\n\nWelcome to the official OpenShift Container Platform 4.22\n\ndocumentation, where you can learn about OpenShift Container Platform and start exploring its features.\n\nTo navigate the OpenShift Container Platform 4.22 documentation, you can use one of the following methods:\n\n- Use the navigation bar to browse the documentation.\n- Select the task that interests you from \"Learn more about OpenShift Container Platform\".\n- OpenShift Container Platform has a variety of layered offerings to add additional functionality and extend the capabilities of a cluster. For more information, see \"OpenShift Container Platform Operator Life Cycles\".\n\n## Additional resources {#additional-resources_welcome-index}\n\n- [Learn more about OpenShift Container Platform](/openshift-docs-markdown/welcome/learn_more_about_openshift#learn_more_about_openshift)\n- [OpenShift Container Platform Operator Life Cycles](https://access.redhat.com/support/policy/updates/openshift_operators)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
