// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: cicd/builds/advanced-build-operations.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Performing advanced builds\n---\n\n# Performing advanced builds {#advanced-build-operations}\n\nYou can set build resources and maximum duration, assign builds to nodes, chain builds, prune builds, and configure build run policies.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
