// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: cicd/builds/build-configuration.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Build configuration resources\n---\n\n# Build configuration resources {#build-configuration}\n\nUse the following procedure to configure build settings.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
