// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: cicd/builds/custom-builds-buildah.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Custom image builds with Buildah\n---\n\n# Custom image builds with Buildah {#custom-builds-buildah}\n\nWith OpenShift Container Platform 4.22, a docker socket will not be present on the host nodes. This means the *mount docker socket* option of a custom build is not guaranteed to provide an accessible docker socket for use within a custom build image.\n\nIf you require this capability in order to build and push images, add the Buildah tool your custom build image and use it to build and push the image within your custom build logic. The following is an example of how to run custom builds with Buildah.\n\n> [!NOTE]\n> Using the custom build strategy requires permissions that normal users do not have by default because it allows the user to execute arbitrary code inside a privileged container running on the cluster. This level of access can be used to compromise the cluster and therefore should be granted only to users who are trusted with administrative privileges on the cluster.\n\n## Prerequisites {#_prerequisites}\n\n- Review how to [grant custom build permissions](/openshift-docs-markdown/cicd/builds/securing-builds-by-strategy#securing-builds-by-strategy).\n\n{% include \"./modules/builds-create-custom-build-artifacts.md\" %}\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
