// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: cicd/builds/understanding-image-builds.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Understanding image builds\n---\n\n# Understanding image builds {#understanding-image-builds}\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
