// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/release-notes/oadp-1-6-release-notes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: \"{{ oadp_short }} 1.6 release notes\"\n---\n\n# {{ oadp_short }} 1.6 release notes {#oadp-1-6-release-notes}\n\nReview new features, resolved issues, known issues, Technology Preview features, removed features, and other additions in {{ oadp_first }} 1.6.\n\n> [!NOTE]\n> For additional information about {{ oadp_short }}, see *{{ oadp_first }} FAQ*.\n\n## Additional resources {#_additional_resources}\n\n- [{{ oadp_first }} FAQ](https://access.redhat.com/articles/5456281)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
