// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/network_security/egress_firewall/configuring-egress-firewall-ovn.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring an egress firewall for a project\n---\n\n# Configuring an egress firewall for a project {#configuring-egress-firewall-ovn}\n\nAs a cluster administrator, you can create an egress firewall for a project that restricts egress traffic leaving your OpenShift Container Platform cluster.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
