// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/network_security/egress_firewall/editing-egress-firewall-ovn.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Editing an egress firewall for a project\n---\n\n# Editing an egress firewall for a project {#editing-egress-firewall-ovn}\n\nAs a cluster administrator, you can modify network traffic rules for an existing egress firewall.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
