// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/network_security/egress_firewall/removing-egress-firewall-ovn.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Removing an egress firewall from a project\n---\n\n# Removing an egress firewall from a project {#removing-egress-firewall-ovn}\n\nAs a cluster administrator, you can remove an egress firewall from a project to remove all restrictions on network traffic from the project that leaves the OpenShift Container Platform cluster.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
