// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/network_security/egress_firewall/viewing-egress-firewall-ovn.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Viewing an egress firewall for a project\n---\n\n# Viewing an egress firewall for a project {#viewing-egress-firewall-ovn}\n\nAs a cluster administrator, you can list the names of any existing egress firewalls and view the traffic rules for a specific egress firewall.\n\n## Viewing an EgressFirewall custom resource (CR) {#nw-egress-firewall-view_viewing-egress-firewall-ovn}\n\nYou can view an `EgressFirewall` CR in your cluster.\n\n**Prerequisites**\n\n- A cluster using the OVN-Kubernetes network plugin.\n- Install the OpenShift Command-line Interface (CLI), commonly known as `oc`.\n- You must log in to the cluster.\n\n**Procedure**\n\n1. Optional: To view the names of the `EgressFirewall` CR defined in your cluster, enter the following command:\n\n   ```terminal\n   $ oc get egressfirewall --all-namespaces\n   ```\n2. To inspect a policy, enter the following command. Replace `<policy_name>` with the name of the policy to inspect.\n\n   ```terminal\n   $ oc describe egressfirewall <policy_name>\n   ```\n\n   ```terminal {title=\"Example output\"}\n   Name:\t\tdefault\n   Namespace:\tproject1\n   Created:\t20 minutes ago\n   Labels:\t\t<none>\n   Annotations:\t<none>\n   Rule:\t\tAllow to 1.2.3.0/24\n   Rule:\t\tAllow to www.example.com\n   Rule:\t\tDeny to 0.0.0.0/0\n   ```\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
