// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/about_virt/virt-supported-limits.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Supported limits\n---\n\n# Supported limits {#virt-supported-limits}\n\nRefer to tested object maximums when planning your environment for your specific use case, and consider all factors that can impact cluster scaling. For information options that impact performance, see the \"{{ VirtProductName }} - Tuning & Scaling Guide\" in the Red Hat Knowledgebase.\n\n## Additional resources {#additional-resources_virt-supported-limits}\n\n- [{{ VirtProductName }} - Tuning & Scaling Guide](https://access.redhat.com/articles/6994974)\n- [Virtualization limits for Red Hat Enterprise Linux with KVM](https://access.redhat.com/articles/rhel-kvm-limits)\n- [Planning your environment according to object maximums](/openshift-docs-markdown/scalability_and_performance/planning-your-environment-according-to-object-maximums#planning-your-environment-according-to-object-maximums)\n- [Managing the maximum number of pods per node](/openshift-docs-markdown/nodes/nodes/nodes-nodes-managing-max-pods#nodes-nodes-managing-max-pods)\n- [{{ rh_rhacm_title }} documentation](https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
