// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/ingress_load_balancing/load-balancing-openstack.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Load balancing on {{ rh_openstack }}\n---\n\n# Load balancing on {{ rh_openstack }} {#load-balancing-openstack}\n\nTo distribute network traffic and communications activity evenly across your compute instances in {{ rh_openstack }}, configure load balancing services.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
