// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/containers/nodes-containers-init.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using Init Containers to perform tasks before a pod is deployed\n---\n\n# Using Init Containers to perform tasks before a pod is deployed {#nodes-containers-init}\n\nYou can use *init containers*, which are specialized containers that run before application containers and can contain utilities or setup scripts not present in an app image.\n\n## Additional resources {#additional-resources_nodes-containers-init}\n\n- [Init Containers (Kubernetes documentation)](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
