// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/containers/nodes-containers-port-forwarding.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using port forwarding to access applications in a container\n---\n\n# Using port forwarding to access applications in a container {#nodes-containers-port-forwarding}\n\nYou can configure port forwarding to pods, which expose services in your cluster to clients outside of the cluster.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
