// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/containers/nodes-containers-downward-api.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Allowing containers to consume API objects\n---\n\n# Allowing containers to consume API objects {#nodes-containers-downward-api}\n\nYou can use the *Downward API* to allow containers to consume information about API objects, such as the pod’s name, namespace, and resource values, without coupling to OpenShift Container Platform by using environment variables or a volume plugin.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
