// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/containers/nodes-containers-volumes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using volumes to persist container data\n---\n\n# Using volumes to persist container data {#nodes-containers-volumes}\n\nYou can use *volumes* to persist the data used by the containers in a pod. A volume is directory, accessible to the containers in a pod, where data is stored for the life of the pod.\n\nFiles in a container are ephemeral. As such, when a container crashes or stops, the data is lost.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
