// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: hosted_control_planes/hcp-certificates.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring certificates for {{ hcp }}\n---\n\n# Configuring certificates for {{ hcp }} {#hcp-certificates}\n\nTo establish secure and encrypted communication between your clients and the hosted control plane, you must configure a server certificate for your hosted cluster.\n\nWith {{ hcp }}, the steps to configure certificates differ from those of standalone OpenShift Container Platform.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
