// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: hosted_control_planes/hcp-import.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Manually importing a hosted cluster\n---\n\n# Manually importing a hosted cluster {#hcp-import}\n\nHosted clusters are automatically imported into {{ mce_short }} after the hosted control plane becomes available.\n\n**Additional resources**\n\n- [Updating node pools in a hosted cluster](/openshift-docs-markdown/hosted_control_planes/hcp-updating#hcp-update-node-pools_hcp-updating)\n- [Updating a control plane in a hosted cluster](/openshift-docs-markdown/hosted_control_planes/hcp-updating#hcp-update-ocp-hc_hcp-updating)\n- [Discovering {{ mce }} hosted clusters in {{ rh_rhacm_title }}](https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/latest/html/multicluster_engine_operator_with_red_hat_advanced_cluster_management/hosted-acm#discover-hosted-acm)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
