// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/network_observability_operator/network-observability-operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Network Observability Operator\n---\n\n# Network Observability Operator {#network-observability-operator-default}\n\nNetwork Observability Operator provides network flow monitoring, visualization, and analysis capabilities for OpenShift Container Platform clusters.\n\n## Network Observability Operator features {#network-observability-operator-stub_network-observability-operator}\n\nWith the Network Observability Operator, you can monitor ingress, egress, and internal network traffic flows between pods, services, and nodes in your cluster.\n\nUse this network flow data to troubleshoot connectivity issues, analyze traffic patterns, detect security threats, and optimize overall network performance.\n\nYou can perform the following tasks with this Operator:\n\n- Collect network flow data by using eBPF technology.\n- Visualize traffic flows inside the OpenShift Container Platform web console.\n- Filter and analyze flows by namespace, pod, service, or port attributes.\n- Export flow data to external analysis tools for long-term storage or processing.\n\n> [!NOTE]\n> For complete documentation about installing, configuring, and using the Network Observability Operator, see [Network Observability overview](/openshift-docs-markdown/observability/network_observability/network-observability-overview#network-observability-overview) in the Observability section.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
