// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/backup_restore/virt-using-vm-file-restore.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Use virtual machine file restore\n---\n\n# Use virtual machine file restore {#virt-using-vm-file-restore}\n\nDiscover VM backups, restore files, and access restored files through a web browser or SSH-based tools.\n\n## Additional resources {#additional-resources_virt-using-vm-file-restore}\n\n- [Recover individual files from virtual machine backups](/virt/backup_restore/virt-recovering-individual-files-from-vm-backups#virt-recovering-individual-files-from-vm-backups)\n- [Backing up and restoring virtual machines](/virt/backup_restore/virt-backup-restore-overview#virt-backup-restore-overview)\n- [Introduction to {{ oadp_full }}](/backup_and_restore/application_backup_and_restore/oadp-intro#oadp-introduction)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
