// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: hosted_control_planes/hcp_high_availability/hcp-backup-etcd-snapshot.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Backing up etcd data for {{ hcp }} by using the etcd snapshot method\n---\n\n# Backing up etcd data for {{ hcp }} by using the etcd snapshot method {#hcp-backup-etcd-snapshot}\n\nTo back up etcd data for {{ hcp }}, you can use the default volume snapshot approach, or you can take the etcd snapshot approach, which results in smaller backup artifacts.\n\n**Additional resources**\n\n- [Configuring {{ oadp_short }}](/openshift-docs-markdown/hosted_control_planes/hcp_high_availability/hcp-disaster-recovery-oadp-auto#hcp-dr-prep-oadp-auto_hcp-disaster-recovery-oadp-auto)\n- [Automating the backup and restore process by using DPA](/openshift-docs-markdown/hosted_control_planes/hcp_high_availability/hcp-disaster-recovery-oadp-auto#hcp-dr-oadp-dpa_hcp-disaster-recovery-oadp-auto)\n- [About installing {{ oadp_short }}](/openshift-docs-markdown/backup_and_restore/application_backup_and_restore/installing/about-installing-oadp#about-installing-oadp)\n\n**Additional resources**\n\n- [Configuring the etcd snapshot method](/openshift-docs-markdown/hosted_control_planes/hcp_high_availability/hcp-backup-etcd-snapshot#hcp-backup-etcd-snapshot-config_hcp-backup-etcd-snapshot)\n\n**Additional resources**\n\n- [Configuring the etcd snapshot method](/openshift-docs-markdown/hosted_control_planes/hcp_high_availability/hcp-backup-etcd-snapshot#hcp-backup-etcd-snapshot-config_hcp-backup-etcd-snapshot)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
