// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/live_migration/virt-about-mtv-providers.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: About {{ mtv_first }} providers\n---\n\n# About {{ mtv_first }} providers {#virt-about-mtv-providers}\n\nTo migrate a virtual machine (VM) across OpenShift Container Platform clusters, you must configure an OpenShift Container Platform provider for each cluster that you are including in the migration. If {{ mtv_short }} is already installed on a cluster, a local provider already exists.\n\n## Additional resources {#additional-resources_virt-about-mtv-providers}\n\n- [Adding a Red Hat {{ VirtProductName }} source provider](https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.9/html-single/installing_and_using_the_migration_toolkit_for_virtualization/index#adding-source-provider_cnv)\n- [Adding an {{ VirtProductName }} destination provider](https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.9/html-single/installing_and_using_the_migration_toolkit_for_virtualization/index#adding-source-provider_dest_cnv)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
