// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/live_migration/virt-about-live-migration.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: About live migration\n---\n\n# About live migration {#virt-about-live-migration}\n\nLive migration moves a running virtual machine to another node without interrupting the workload. It enables smooth transitions during cluster upgrades and node maintenance. Traffic is encrypted using TLS by default.\n\n## Additional resources {#additional-resources_virt-about-live-migration}\n\n- [Default cluster roles for {{ VirtProductName }}](/virt/about_virt/virt-security-policies#default-cluster-roles-for-virt_virt-security-policies)\n- [Prometheus queries for live migration](/virt/monitoring/virt-prometheus-queries#virt-live-migration-metrics_virt-prometheus-queries)\n- [Configure eviction and run strategies](/virt/nodes/virt-eviction-strategies#virt-eviction-strategies)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
