// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/vm_networking/virt-connecting-vm-to-default-pod-network.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Connecting a virtual machine to the default pod network\n---\n\n# Connecting a virtual machine to the default pod network {#virt-connecting-vm-to-default-pod-network}\n\nYou can connect a virtual machine to the default internal pod network by configuring its network interface to use the `masquerade` binding mode.\n\n> [!NOTE]\n> Traffic passing through network interfaces to the default pod network is interrupted during live migration.\n\n## Additional resources {#additional-resources_virt-connecting-vm-to-default-pod-network}\n\n- [Changing the MTU for the cluster network](/networking/advanced_networking/changing-cluster-network-mtu#changing-cluster-network-mtu)\n- [Optimizing the MTU for your network](/scalability_and_performance/optimization/optimizing-networking#optimizing-mtu_optimizing-networking)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
