// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/vm_networking/virt-configuring-viewing-ips-for-vms.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring and viewing IP addresses\n---\n\n# Configuring and viewing IP addresses {#virt-configuring-viewing-ips-for-vms}\n\nYou can configure an IP address when you create a virtual machine (VM). The IP address is provisioned with cloud-init. View the IP address of a VM by using the OpenShift Container Platform web console or the command line. The network information is collected by the QEMU guest agent.\n\n## Additional resources {#additional-resources_virt-configuring-viewing-ips-for-vms}\n\n- [Installing the QEMU guest agent](/openshift-docs-markdown/virt/managing_vms/virt-installing-qemu-guest-agent#virt-installing-qemu-guest-agent)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
