// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/vm_networking/virt-connecting-vm-to-linux-bridge.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Connecting a virtual machine to a Linux bridge network\n---\n\n# Connecting a virtual machine to a Linux bridge network {#virt-connecting-vm-to-linux-bridge}\n\nBy default, {{ VirtProductName }} is installed with a single, internal pod network. You can connect a virtual machine (VM) to the physical network by using a Linux bridge.\n\nTo create a Linux bridge network and attach a VM to the network, perform the following steps:\n\n1. Prepare the node network by creating a Linux bridge node network configuration policy (NNCP).\n2. Define the secondary Linux bridge network by creating a network attachment definition (NAD).\n3. Attach the VM to the Linux bridge network.\n\n> [!NOTE]\n> {{ VirtProductName }} does not support Linux bridge bonding modes 0, 5, and 6. For more information, see \"Additional resources\".\n\n## Additional resources {#additional-resources_virt-connecting-vm-to-linux-bridge}\n\n- [Configuring IP addresses for virtual machines](/openshift-docs-markdown/virt/vm_networking/virt-configuring-viewing-ips-for-vms#virt-configuring-viewing-ips-for-vms)\n- [Which bonding modes work when used with a bridge that virtual machine guests or containers connect to?](https://access.redhat.com/solutions/67546)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
