// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/vm_networking/virt-connecting-vm-to-service-mesh.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Connecting a virtual machine to a service mesh\n---\n\n# Connecting a virtual machine to a service mesh {#virt-connecting-vm-to-service-mesh}\n\n{{ VirtProductName }} is now integrated with {{ SMProductName }}. You can monitor, visualize, and control traffic between pods that run virtual machine (VM) workloads on the default pod network with IPv4.\n\n## Additional resources {#additional-resources_virt-connecting-vm-to-service-mesh}\n\n- [Installing the Service Mesh Operator](https://docs.redhat.com/en/documentation/red_hat_openshift_service_mesh/3.0/html/installing/ossm-installing-service-mesh)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
