// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: cli_reference/tkn_cli/op-tkn-reference.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: OpenShift Pipelines tkn reference\n---\n\n# OpenShift Pipelines tkn reference {#op-tkn-reference}\n\nThis section lists the basic `tkn` CLI commands.\n\n## Basic syntax {#_basic_syntax}\n\n`tkn [command or options] [arguments...]`\n\n## Global options {#_global_options}\n\n`--help, -h`\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
