// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: openshift_images/using_images/customizing-s2i-images.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Customizing source-to-image images\n---\n\n# Customizing source-to-image images {#customizing-s2i-images}\n\nTo modify the default assemble and run script behavior in OpenShift Container Platform, you can customize source-to-image (S2I) builder images. You can adapt S2I builders to meet your specific application requirements when the default scripts are not suitable.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
