// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/install_config/configuring-firewall.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring your firewall\n---\n\n# Configuring your firewall {#configuring-firewall}\n\nIf you use a firewall, you must configure your allowlist for the firewall to ensure OpenShift Container Platform has access to the URLs it requires to pull container images and access Red Hat services. Additional URLs are required for features such as Telemetry, {{ red_hat_lightspeed }}, cloud provider integrations, or certain build strategies.\n\n**Additional resources**\n\n- [OpenID Connect requirements for AWS STS](/openshift-docs-markdown/authentication/managing_cloud_provider_credentials/cco-short-term-creds#cco-short-term-creds-auth-flow-aws-oidc_cco-short-term-creds)\n\n**Additional resources**\n\n- [{{ cli_manager }} overview](/openshift-docs-markdown/cli_reference/cli_manager/index#cli-manager-overview)\n\n**Additional resources**\n\n- [Minimizing node disruption with MachineConfig changes](/openshift-docs-markdown/machine_configuration/machine-config-node-disruption#machine-config-node-disruption)\n\n**Additional resources**\n\n- [Installing Butane](/openshift-docs-markdown/installing/install_config/installing-customizing#installation-special-config-butane-install_installing-customizing)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
