// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_ibm_cloud/configuring-iam-ibm-cloud.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring IAM for {{ ibm_cloud_title }}\n---\n\n# Configuring IAM for {{ ibm_cloud_title }} {#configuring-iam-ibm-cloud}\n\nIn environments where the cloud identity and access management (IAM) APIs are not reachable, you must put the Cloud Credential Operator (CCO) into manual mode before you install the cluster.\n\n<a name=\"additional-resources_configuring-iam-ibm-cloud-about-cco\"></a>**Additional resources**\n\n- [About the Cloud Credential Operator](/openshift-docs-markdown/authentication/managing_cloud_provider_credentials/about-cloud-credential-operator#about-cloud-credential-operator)\n\n<a name=\"additional-resources_configuring-iam-ibm-cloud-refreshing-ids\"></a>**Additional resources**\n\n- [Rotating API keys for {{ ibm_cloud_name }}](/openshift-docs-markdown/post_installation_configuration/changing-cloud-credentials-configuration#refreshing-service-ids-ibm-cloud_changing-cloud-credentials-configuration)\n\n## Additional resources {#additional-resources_configuring-iam-ibm-cloud}\n\n- [Installing a cluster on {{ ibm_cloud_name }} with customizations](/openshift-docs-markdown/installing/installing_ibm_cloud/installing-ibm-cloud-customizations#installing-ibm-cloud-customizations)\n- [Preparing to update a cluster with manually maintained credentials](/openshift-docs-markdown/updating/preparing_for_updates/preparing-manual-creds-update#preparing-manual-creds-update)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
