// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_ibm_cloud/installation-config-parameters-ibm-cloud-vpc.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installation configuration parameters for {{ ibm_cloud_title }}\n---\n\n# Installation configuration parameters for {{ ibm_cloud_title }} {#installation-config-parameters-ibm-cloud-vpc}\n\nBefore you deploy an OpenShift Container Platform cluster on {{ ibm_cloud_name }}, you give values for parameters to customize your cluster and the platform that hosts it.\n\nWhen you create the `install-config.yaml` file, you give values for the required parameters through the command line. You can then change the `install-config.yaml` file to customize your cluster further.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
