// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_ibm_cloud/installing-ibm-cloud-account.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring an {{ ibm_cloud_title }} account\n---\n\n# Configuring an {{ ibm_cloud_title }} account {#installing-ibm-cloud-account}\n\nBefore you can install OpenShift Container Platform on {{ ibm_cloud_name }}, you must configure your account by setting up DNS, IAM policies, and an API key.\n\nYou must have a subscription account; free or trial accounts are not supported.\n\n**Additional resources**\n\n- [{{ ibm_cloud_name }} CLI ({{ ibm_cloud_name }} documentation)](https://www.ibm.com/cloud/cli)\n- [{{ ibm_name }} DNS documentation](https://cloud.ibm.com/docs/dns?topic=dns-getting-started)\n- [CIS web console ({{ ibm_cloud_name }} documentation)](https://cloud.ibm.com/catalog/services/internet-services)\n- [{{ ibm_cloud_name }} documentation for configuring name servers](https://cloud.ibm.com/docs/cis?topic=cis-getting-started#configure-your-name-servers-with-the-registrar-or-existing-dns-provider)\n\n**Additional resources**\n\n- [{{ ibm_cloud_name }} CLI ({{ ibm_cloud_name }} documentation)](https://www.ibm.com/cloud/cli)\n- [{{ ibm_name }} DNS documentation](https://cloud.ibm.com/docs/dns?topic=dns-getting-started)\n\n## Additional resources {#additional-resources_installing-ibm-cloud-account}\n\n- [Configuring IAM for {{ ibm_cloud_name }}](/openshift-docs-markdown/installing/installing_ibm_cloud/configuring-iam-ibm-cloud#configuring-iam-ibm-cloud)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
