// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/installing_ibm_cloud/uninstalling-cluster-ibm-cloud.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Uninstalling a cluster on {{ ibm_cloud_title }}\n---\n\n# Uninstalling a cluster on {{ ibm_cloud_title }} {#uninstalling-cluster-ibm-cloud}\n\nYou can remove an OpenShift Container Platform cluster that you deployed to {{ ibm_cloud_name }}. The uninstall process removes all cluster resources and infrastructure components that the installation program provisioned.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
