// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: cicd/builds_using_shipwright/overview-openshift-builds.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Overview of Builds\n---\n\n# Overview of Builds {#overview-openshift-builds}\n\nBuilds is an extensible build framework based on the [Shipwright project](https://shipwright.io/), which you can use to build container images on your OpenShift Container Platform cluster. You can build container images from source code and Dockerfiles by using image build tools, such as Source-to-Image (S2I) and Buildah. You can create and apply build resources, view logs of build runs, and manage builds in your OpenShift Container Platform namespaces.\n\nBuilds includes the following capabilities:\n\n- Standard Kubernetes-native API for building container images from source code and Dockerfiles\n- Support for Source-to-Image (S2I) and Buildah build strategies\n- Extensibility with your own custom build strategies\n- Execution of builds from source code in a local directory\n- Shipwright CLI for creating and viewing logs, and managing builds on the cluster\n- Integrated user experience with the **Developer** perspective of the OpenShift Container Platform web console\n\n> [!NOTE]\n> Because Builds releases on a different cadence from OpenShift Container Platform, the Builds documentation is now available as a separate documentation set at [Builds for Red Hat OpenShift](https://docs.redhat.com/en/documentation/builds_for_red_hat_openshift).\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
