// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/clusters/nodes-containers-events.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Viewing system event information in OpenShift Container Platform clusters\n---\n\n# Viewing system event information in OpenShift Container Platform clusters {#nodes-containers-events}\n\nYou can view events in OpenShift Container Platform, which are based on events that happen to API objects in an OpenShift Container Platform cluster.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
