// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/clusters/nodes-cluster-limit-ranges.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Restrict resource consumption with limit ranges\n---\n\n# Restrict resource consumption with limit ranges {#nodes-cluster-limit-ranges}\n\nYou can use limit ranges to restrict resource consumption for specific objects in a project.\n\nBy default, containers run with unbounded compute resources on an OpenShift Container Platform cluster.\n\nYou can configure resource consumption for the following objects:\n\n- pods and containers: You can set minimum and maximum requirements for CPU and memory for pods and their containers.\n- Image streams: You can set limits on the number of images and tags in an `ImageStream` object.\n- Images: You can limit the size of images that can be pushed to an internal registry.\n- Persistent volume claims (PVC): You can restrict the size of the PVCs that can be requested.\n\nIf a pod does not meet the constraints imposed by the limit range, the pod cannot be created in the namespace.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
