// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/clusters/nodes-cluster-worker-latency-profiles.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Improving cluster stability in high latency environments using worker latency profiles\n---\n\n# Improving cluster stability in high latency environments using worker latency profiles {#nodes-cluster-worker-latency-profiles}\n\nReview the following information to learn about *worker latency profiles*, which adjust the frequency that the Kubelet and the Kubernetes Controller Manager wait for status updates before taking action if a pod is unreachable.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
