// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/external_secrets_operator/external-secrets-operator-config-net-policy.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring network policy for the operand\n---\n\n# Configuring network policy for the operand {#external-secrets-operator-config-net-policy}\n\nThe {{ external_secrets_operator }} for OpenShift Container Platform includes pre-defined `NetworkPolicies` for security that rejects all egress traffic and allows traffic towards services that are required for the operand functionality. You must configure additional custom policies to allow the `external-secrets` controller to egress traffic towards external providers. These configurable policies are set through the `ExternalSecretsConfig` custom resource to establish the egress allow policy.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
