// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/networking_overview/understanding-networking.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Understanding networking\n---\n\n# Understanding networking {#understanding-networking}\n\nUnderstanding networking is essential for building resilient, secure, and scalable applications in OpenShift Container Platform. From basic pod-to-pod communication to complex traffic routing and security rules, every component of your application relies on the network to function correctly.\n\nThe following diagram shows the flow of external and internal network traffic among networking components for an {{ aws_first }} external client when connecting to a pod in a cluster.\n\n**Figure 1. Diagram showing traffic flow among networking components**\n\n![Diagram showing traffic flow among networking components](/openshift-docs-markdown/_assets/images/494_OpenShift_pod_networking_0426.png)\n\n**Additional resources**\n\n- [About network policy](/openshift-docs-markdown/networking/network_security/network_policy/about-network-policy#about-network-policy)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
