// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: disconnected/installing.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing a cluster in a disconnected environment\n---\n\n# Installing a cluster in a disconnected environment {#installing-disconnected-environments}\n\nYou can install an OpenShift Container Platform cluster in a disconnected environment, choosing the installation method and infrastructure that best suits your requirements. This includes installing OpenShift Container Platform on either on-premise hardware or on a cloud hosting service such as Amazon Web Services (AWS).\n\nThe following sections outline all of the supported methods for installing a cluster in a disconnected environment.\n\n> [!NOTE]\n> To learn about other requirements for installing a cluster using a particular method, be sure to review other content in the procedure’s respective section of the documentation.\n>\n> For example, if you plan to install a cluster on {{ aws_short }} with installer-provisioned infrastructure, see \"Configuring an AWS account\" and \"Preparing to install a cluster on {{ aws_short }}\".\n\n## Additional resources {#additional-resources_installing-disconnected-environments}\n\n- [Configuring an AWS account](/installing/installing_aws/installing-aws-account#installing-aws-account)\n- [Preparing to install a cluster on {{ aws_short }}](/installing/installing_aws/ipi/ipi-aws-preparing-to-install#ipi-aws-preparing-to-install)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
