// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: disconnected/oc-mirror-migration-v1-to-v2.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Migrating from oc-mirror plugin v1 to v2\n---\n\n# Migrating from oc-mirror plugin v1 to v2 {#oc-mirror-migration-v1-to-v2}\n\nThe oc-mirror v2 plugin introduces major changes to image mirroring workflows. Understand the migration process and check for compatibility with oc-mirror plugin v2 to ensure a successful migration.\n\n> [!IMPORTANT]\n> You must manually update the configurations by modifying the API version and removing deprecated fields. For more information, see \"Changes from oc-mirror plugin v1 to v2\".\n\n## Additional resources {#additional-resources_oc-mirror-migration-v1-to-v2}\n\n- [Mirroring an image set in a partially disconnected environment](/disconnected/about-installing-oc-mirror-v2#oc-mirror-workflows-partially-disconnected-v2_about-installing-oc-mirror-v2)\n- [Mirroring an image set in a fully disconnected environment](/disconnected/about-installing-oc-mirror-v2#oc-mirror-workflows-fully-disconnected-v2_about-installing-oc-mirror-v2)\n- [Changes from oc-mirror plugin v1 to v2](/disconnected/oc-mirror-migration-v1-to-v2#oc-mirror-migration-differences_oc-mirror-migration-v1-to-v2)\n- [Deletion of images from your disconnected environment](/disconnected/about-installing-oc-mirror-v2#oc-mirror-procedure-delete-v2_about-installing-oc-mirror-v2)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
