// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: disconnected/updating.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: About cluster updates in a disconnected environment\n---\n\n# About cluster updates in a disconnected environment {#about-disconnected-updates}\n\nYou can update a OpenShift Container Platform cluster in a disconnected environment where the cluster nodes cannot access the internet or where you want to manage update recommendations and release images locally for policy or performance purposes.\n\n**Additional resources**\n\n- [Mirroring OpenShift Container Platform images](/openshift-docs-markdown/disconnected/updating/mirroring-image-repository#mirroring-ocp-image-repository)\n\n**Additional resources**\n\n- [Updating a cluster in a disconnected environment using the OpenShift Update Service](/openshift-docs-markdown/disconnected/updating/disconnected-update-osus#updating-disconnected-cluster-osus)\n- [Updating a cluster in a disconnected environment without the OpenShift Update Service](/openshift-docs-markdown/disconnected/updating/disconnected-update#updating-disconnected-cluster)\n\n**Additional resources**\n\n- [Uninstalling the OpenShift Update Service from a cluster](/openshift-docs-markdown/disconnected/updating/uninstalling-osus#uninstalling-osus)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
