// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/multiple_networks/secondary_networks/configuring-master-interface.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring the master interface in the container network namespace\n---\n\n# Configuring the master interface in the container network namespace {#configuring-master-interface-secondary-nwt}\n\nYou can create and manage a MAC-VLAN, IP-VLAN, and VLAN subinterface based on a `master` interface.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
