// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/multiple_networks/secondary_networks/configuring-ip-secondary-nwt.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring IP address assignment on secondary networks\n---\n\n# Configuring IP address assignment on secondary networks {#configuring-ip-secondary-nwt}\n\nYou can configure IP address assignments for secondary networks so that pods can connect to the secondary networks.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
