// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/multiple_networks/secondary_networks/editing-additional-network.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Editing a secondary network\n---\n\n# Editing a secondary network {#edit-additional-network}\n\nTo update network settings or change network parameters for a secondary network in OpenShift Container Platform, you can modify the configuration for an existing secondary network. Edit the `NetworkAttachmentDefinition` custom resource to apply your changes.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
