// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/multiple_networks/secondary_networks/removing-pod.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Removing a pod from a secondary network\n---\n\n# Removing a pod from a secondary network {#removing-pod}\n\nTo disconnect a pod from specific network configurations in OpenShift Container Platform, you can remove the pod from a secondary network. Delete the pod to remove its connection to the secondary network.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
