// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/multiple_networks/secondary_networks/removing-additional-network.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Removing an additional network\n---\n\n# Removing an additional network {#remove-additional-network}\n\nTo clean up unused network configurations or free up network resources in OpenShift Container Platform, you can remove an additional network attachment. Delete the `NetworkAttachmentDefinition` custom resource to remove the secondary network from your cluster.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
