// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: ai_workloads/jobset_operator.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: \"{{ js_operator }} overview\"\n---\n\n# {{ js_operator }} overview {#js-about}\n\nUse the {{ js_operator }} on OpenShift Container Platform to manage and run large-scale, coordinated workloads like high-performance computing (HPC) and AI training. Features like multi-template job support and stable networking can help you recover quickly and use resources efficiently.\n\n## Additional resources {#js-about_additional-resources}\n\n- [JobSet documentation (Kubernetes)](https://jobset.sigs.k8s.io/docs/overview/)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
