// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: ai_workloads/leader_worker_set.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: \"{{ lws_operator }} overview\"\n---\n\n# {{ lws_operator }} overview {#lws-about}\n\nUse the {{ lws_operator }} to manage multi-node AI/ML inference deployments efficiently. The {{ lws_operator }} treats groups of pods as one unit to simplify scaling, recovery, and updates for large workloads.\n\nUsing large language models (LLMs) for AI/ML inference often requires significant compute resources, and workloads typically must be sharded across multiple nodes. This can make deployments complex, creating challenges around scaling, recovery from failures, and efficient pod placement.\n\nThe {{ lws_operator }} simplifies these multi-node deployments by treating a group of pods as a single, coordinated unit. It manages the lifecycle of each pod in the group, scales the entire group together, and performs updates and failure recovery at the group level to ensure consistency.\n\n## Additional resources {#lws-about_additional-resources}\n\n- [LeaderWorkerSet documentation (Kubernetes)](https://lws.sigs.k8s.io/docs/overview/)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
