// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/ingress_load_balancing/routes/creating-basic-routes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Creating basic routes\n---\n\n# Creating basic routes {#creating-basic-routes}\n\nIf you have unencrypted HTTP, you can create a basic route with a route object.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
