// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/troubleshooting/backup-and-restore-cr-issues.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Backup and Restore CR issues\n---\n\n# Backup and Restore CR issues {#backup-and-restore-cr-issues}\n\nResolve common issues with `Backup` and `Restore` custom resources (CRs), such as volume retrieval failures, and backups remaining in progress or partially failed states. This helps you ensure successful backup and restore operations in {{ oadp_short }}.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
