// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/troubleshooting/using-the-must-gather-tool.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using the must-gather tool\n---\n\n# Using the must-gather tool {#using-the-must-gather-tool}\n\nCollect logs and information about {{ oadp_short }} custom resources by using the `must-gather` tool. The `must-gather` data must be attached to all customer cases.\n\nThe `must-gather` tool is a container and does not run all the time. The tool runs for a few minutes only after you start the tool by running the `must-gather` command.\n\n**Additional resources**\n\n- [Gathering cluster data](/openshift-docs-markdown/support/gathering-cluster-data#gathering-cluster-data)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
