// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/networking_operators/aws_load_balancer_operator/aws-load-balancer-operator-release-notes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: AWS Load Balancer Operator release notes\n---\n\n# AWS Load Balancer Operator release notes {#aws-load-balancer-operator-release-notes}\n\nThe release notes for the AWS Load Balancer (ALB) Operator summarize all new features and enhancements, notable technical changes, major corrections from the previous version, and any known bugs upon general availability.\n\n> [!IMPORTANT]\n> The AWS Load Balancer (ALB) Operator is only supported on the `x86_64` architecture.\n\nThese release notes track the development of the AWS Load Balancer Operator in OpenShift Container Platform.\n\n> [!NOTE]\n> AWS Load Balancer Operator currently does not support AWS GovCloud.\n\n**Additional resources**\n\n- [AWS Load Balancer Operator in OpenShift Container Platform](/networking/networking_operators/aws_load_balancer_operator/understanding-aws-load-balancer-operator#aws-load-balancer-operator)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
