// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/graceful-cluster-shutdown.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Shutting down the cluster gracefully\n---\n\n# Shutting down the cluster gracefully {#graceful-shutdown-cluster}\n\nYou can shut down your OpenShift Container Platform cluster for planned maintenance by cordoning nodes, draining workloads, and stopping nodes in order. Graceful shutdown preserves cluster state so you can restart the cluster when maintenance is complete.\n\n## Additional resources {#additional-resources_restarting-restoring-cluster}\n\n- [Backing up etcd](/backup_and_restore/control_plane_backup_and_restore/backing-up-etcd#backup-etcd)\n- [Restoring to an earlier cluster state](/backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state#dr-restoring-cluster-state)\n- [Restarting the cluster gracefully](/backup_and_restore/graceful-cluster-restart#graceful-restart-cluster)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
