// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/graceful-cluster-restart.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Restarting the cluster gracefully\n---\n\n# Restarting the cluster gracefully {#graceful-restart-cluster}\n\nYou can restart your OpenShift Container Platform cluster after a graceful shutdown by powering on nodes and verifying cluster health. The cluster returns to normal operations when nodes and Operators are healthy.\n\nEven though the cluster is expected to be functional after the restart, the cluster might not recover due to unexpected conditions:\n\n- etcd data corruption during shutdown\n- Node failure due to hardware\n- Network connectivity issues\n\nIf your cluster fails to recover, follow the steps in \"Restoring to an earlier cluster state\".\n\n**Additional resources**\n\n- [Shutting down the cluster gracefully](/openshift-docs-markdown/backup_and_restore/graceful-cluster-shutdown#graceful-shutdown-cluster)\n- [Restoring to an earlier cluster state](/openshift-docs-markdown/backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state#dr-restoring-cluster-state)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
