// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: ai_workloads/jobset_operator/jobset-release-notes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: JobSet Operator release notes\n---\n\n# JobSet Operator release notes {#js-release-notes}\n\nTrack the development, features, and fixes for the JobSet Operator, which manages coordinated, large-scale computing workloads on OpenShift Container Platform.\n\nFor more information, see [About the JobSet Operator](/openshift-docs-markdown/ai_workloads/jobset_operator/index#js-about).\n\n## Release notes for JobSet Operator 1.0 {#js-rn-1-0_js-release-notes}\n\nReview the new features and advisories for the initial release of JobSet Operator 1.0.\n\nIssued: 12 February 2026\n\nThe following advisories are available for the JobSet Operator 1.0:\n\n- [RHBA-2026:2570](https://access.redhat.com/errata/RHBA-2026:2570)\n\n### New features and enhancements {#js-rn-1-0-new-features_js-release-notes}\n\n- This is the initial Generally Available release of the JobSet Operator.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
