// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/advanced_networking/associating-secondary-interfaces-metrics-to-network-attachments.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Associating secondary interfaces metrics to network attachments\n---\n\n# Associating secondary interfaces metrics to network attachments {#associating-secondary-interfaces-metrics-to-network-attachments}\n\nTo gain better visibility into cluster traffic, you can associate secondary interface metrics with specific network attachments. By using the `pod_network_info` metric to label interfaces based on their `NetworkAttachmentDefinition` resource, you can more easily monitor performance and troubleshoot connectivity issues across your network.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
