// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: networking/advanced_networking/verifying-connectivity-endpoint.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Verifying connectivity to an endpoint\n---\n\n# Verifying connectivity to an endpoint {#verifying-connectivity-endpoint}\n\nThe Cluster Network Operator (CNO) runs a controller, the connectivity check controller, that performs a connection health check between resources within your cluster. By reviewing the results of the health checks, you can diagnose connection problems or eliminate network connectivity as the cause of an issue that you are investigating.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
