// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: installing/overview/installing-preparing.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Selecting a cluster installation method and preparing it for users\n---\n\n# Selecting a cluster installation method and preparing it for users {#installing-preparing}\n\nBefore you install OpenShift Container Platform, decide what kind of installation process to follow and verify that you have all of the required resources to prepare the cluster for users.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
