// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: release_notes/ocp-4-22-release-notes.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: OpenShift Container Platform 4.22 release notes\n---\n\n# OpenShift Container Platform 4.22 release notes {#ocp-4-22-release-notes}\n\nOpenShift Container Platform ([RHEA-2026:0449](https://access.redhat.com/errata/RHEA-2026:0449)) is now available. Before working with this release, familiarize yourself with the new features, changes, and known issues that pertain to OpenShift Container Platform 4.22 are included in this topic.\n\nRed Hat OpenShift Container Platform provides developers and IT organizations with a hybrid cloud application platform for deploying both new and existing applications on secure, scalable resources with minimal configuration and management. OpenShift Container Platform supports a wide selection of programming languages and frameworks, such as Java, JavaScript, Python, Ruby, and PHP.\n\nBuilt on {{ op_system_base_full }} and Kubernetes, OpenShift Container Platform provides a more secure and scalable multitenant operating system for today’s enterprise-class applications, while delivering integrated application runtimes and libraries. OpenShift Container Platform enables organizations to meet security, privacy, compliance, and governance requirements.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
