// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: machine_management/cluster_api_machine_management/cluster_api_provider_configurations/cluster-api-config-options-bare-metal.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Cluster API configuration options for bare metal\n---\n\n# Cluster API configuration options for bare metal {#cluster-api-config-options-bare-metal}\n\nYou can change the configuration of your bare metal Cluster API machines by updating values in the Cluster API custom resource manifests.\n\n## Sample YAML for configuring bare metal clusters {#cluster-api-sample-yaml-bare-metal_cluster-api-config-options-bare-metal}\n\nThe following example YAML files show configurations for a bare metal cluster.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
