// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: machine_management/cluster_api_machine_management/cluster_api_provider_configurations/cluster-api-config-options-azure.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Cluster API configuration options for {{ azure_full }}\n---\n\n# Cluster API configuration options for {{ azure_full }} {#cluster-api-config-options-azure}\n\nYou can change the configuration of your {{ azure_first }} Cluster API machines by updating values in the Cluster API custom resource manifests.\n\nThe following example YAML files show configurations for an {{ azure_short }} cluster.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
