// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: support/remote_health_monitoring/remote-health-reporting.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Remote health reporting\n---\n\n# Remote health reporting {#remote-health-reporting}\n\nYou can *opt in*, enable, or *opt out*, disable, reporting health and usage data for your cluster.\n\n**Additional resources**\n\n- [How does the subscriptions service show my subscription data?(Getting Started with the Subscription Service)](https://access.redhat.com/documentation/en-us/subscription_central/2023/html/getting_started_with_the_subscriptions_service/con-how-does-subscriptionwatch-show-data_assembly-viewing-understanding-subscriptionwatch-data-ctxt)\n\n**Additional resources**\n\n- [Transferring cluster ownership](https://docs.redhat.com/en/documentation/openshift_cluster_manager/1-latest/html-single/managing_clusters/index#transferring-cluster-ownership_downloading-and-updating-pull-secrets)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
