// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: support/remote_health_monitoring/remote-health-reporting-from-restricted-network.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Using remote health reporting in a restricted network\n---\n\n# Using remote health reporting in a restricted network {#remote-health-reporting-from-restricted-network}\n\nYou can manually gather and upload {{ insights_operator }} archives to diagnose issues from a restricted network.\n\nTo use the {{ insights_operator }} in a restricted network, you must complete the following tasks:\n\n- Create a copy of your {{ insights_operator }} archive.\n- Upload the {{ insights_operator }} archive to the {{ hybrid_console }}.\n\nAdditionally, you can select to obfuscate the {{ insights_operator }} data before data upload.\n\n**Additional resources**\n\n- [{{ hybrid_console }}](https://console.redhat.com)\n- [Enabling {{ insights_operator }} data obfuscation](/support/remote_health_monitoring/remote-health-reporting-from-restricted-network#insights-operator-enable-obfuscation_remote-health-reporting-from-restricted-network)\n\n**Additional resources**\n\n- [Showing data collected by the {{ insights_operator }}](/support/remote_health_monitoring/showing-data-collected-by-remote-health-monitoring#insights-operator-showing-data-collected-from-the-cluster_showing-data-collected-by-remote-health-monitoring)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
