// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: support/remote_health_monitoring/showing-data-collected-by-remote-health-monitoring.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Showing data collected by remote health monitoring\n---\n\n# Showing data collected by remote health monitoring {#showing-data-collected-by-remote-health-monitoring}\n\nAs an administrator, you can review the metrics collected by Telemetry and the {{ insights_operator }}.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
