// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/oadp-vmfr/oadp-vmfr.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: \"{{ oadp_short }} virtual machine file restore\"\n---\n\n# {{ oadp_short }} virtual machine file restore {#oadp-vmfr}\n\nRecover individual files from virtual machine backups without restoring the entire VM. Browse, compare, and download files from multiple backups simultaneously through a web browser or SSH-based tools.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
