// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/network_bound_disk_encryption/nbde-managing-encryption-keys.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Tang server encryption key management\n---\n\n# Tang server encryption key management {#nbde-managing-encryption-keys}\n\nThe cryptographic mechanism to recreate the encryption key is based on the *blinded key* stored on the node and the private key of the involved Tang servers.\n\n> [!NOTE]\n> To protect against the possibility of an attacker who has obtained both the Tang server private key and the node’s encrypted disk, periodic rekeying is advisable.\n>\n> You must perform the rekeying operation for every node before you can delete the old key from the Tang server.\n\nThe following sections provide procedures for rekeying and deleting old keys.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
