// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-deleting-backups.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Deleting backups\n---\n\n# Deleting backups {#oadp-deleting-backups}\n\nDelete a backup by creating the `DeleteBackupRequest` custom resource (CR) or by running the `velero backup delete` command. This helps you to free up storage space and remove outdated backup artifacts.\n\nThe volume backup artifacts are deleted at different times depending on the backup method:\n\n- Restic: The artifacts are deleted in the next full maintenance cycle, after the backup is deleted.\n- Container Storage Interface (CSI): The artifacts are deleted immediately when the backup is deleted.\n- Kopia: The artifacts are deleted after three full maintenance cycles of the Kopia repository, after the backup is deleted.\n\n{% include \"./modules/oadp-deleting-backups-using-oc.md\" %} {% include \"./modules/oadp-deleting-backups-using-velero.md\" %}\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
