// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/cpu_models/virt-configuring-default-cpu-model.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configure CPU models\n---\n\n# Configure CPU models {#virt-configuring-default-cpu-model}\n\nYou can configure CPU models for your virtual machines at both the cluster level and individual VM level. Set a cluster-wide default CPU model to automatically apply to all new VMs, or configure a specific CPU model for individual VMs to override the cluster default.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
