// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: virt/managing_vms/cpu_models/virt-schedule-vms.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Schedule virtual machines\n---\n\n# Schedule virtual machines {#virt-schedule-vms}\n\nYou can schedule a virtual machine (VM) on a node by ensuring that the VM’s CPU model and policy attribute are matched for compatibility with the CPU models and policy attributes supported by the node.\n\n **Additional resources**\n\n- [Deploying a secondary scheduler](/openshift-docs-markdown/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-configuring#nodes-secondary-scheduler-configuring-console_secondary-scheduler-configuring)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
