// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/nbde_tang_server_operator/nbde-tang-server-operator-overview.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: NBDE Tang Server Operator overview\n---\n\n# NBDE Tang Server Operator overview {#nbde-tang-server-operator-overview}\n\nNetwork-bound Disk Encryption (NBDE) provides an automated unlocking of LUKS-encrypted volumes using one or more dedicated network-binding servers. The client side of NBDE is called the Clevis decryption policy framework and the server side is represented by Tang.\n\nThe NBDE Tang Server Operator allows the automation of deployments of one or several Tang servers in the OpenShift Container Platform (OCP) environment.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
