// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: security/nbde_tang_server_operator/nbde-tang-server-operator-configuring-managing.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Configuring and managing Tang servers using the NBDE Tang Server Operator\n---\n\n# Configuring and managing Tang servers using the NBDE Tang Server Operator {#configuring-and-managing-nbde-tang-server-operator}\n\nWith the NBDE Tang Server Operator, you can deploy and quickly configure Tang servers. On the deployed Tang servers, you can list existing keys and rotate them.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
