// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: storage/container_storage_interface/ephemeral-storage-csi-inline.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: CSI inline ephemeral volumes\n---\n\n# CSI inline ephemeral volumes {#ephemeral-storage-csi-inline}\n\nYou can provision temporary, pod-specific storage by using Container Storage Interface (CSI) inline ephemeral volumes that are automatically created at pod deployment and removed at pod termination.\n\n **Additional resources**\n\n- [{{ builds_v2title }} 1.1](https://docs.redhat.com/en/documentation/builds_for_red_hat_openshift/1.1)\n\n## Additional resources {#additional-resources_ephemeral-storage-csi-inline}\n\n- [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
