// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: storage/container_storage_interface/persistent-storage-csi-smb-cifs.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: CIFS/SMB CSI Driver Operator\n---\n\n# CIFS/SMB CSI Driver Operator {#persistent-storage-csi-smb-cifs}\n\nYou can provision and manage Common Internet File System (CIFS)/Server Message Block (SMB) network shares in OpenShift Container Platform by using the CIFS/SMB Container Storage Interface (CSI) Driver Operator, which supports dynamic volume provisioning.\n\n **Additional resources**\n\n- [Understanding persistent storage](/storage/understanding-persistent-storage#understanding-persistent-storage)\n- [Configuring CSI volumes](/storage/container_storage_interface/persistent-storage-csi#persistent-storage-csi)\n- [Dynamic provisioning](/storage/container_storage_interface/persistent-storage-csi-smb-cifs#persistent-storage-csi-smb-cifs-provision-dynamic_persistent-storage-csi-smb-cifs)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
