// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: storage/container_storage_interface/persistent-storage-csi-cloning.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: CSI volume cloning\n---\n\n# CSI volume cloning {#persistent-storage-csi-cloning}\n\nContainer Storage Interface (CSI) volume cloning duplicates existing persistent volumes to create independent copies for data protection, testing, or deployment. You can use cloning to create new volumes from existing data without manual copying or backup restoration.\n\n**Additional resources**\n\n- [Understanding persistent volumes](/openshift-docs-markdown/storage/understanding-persistent-storage#persistent-volumes_understanding-persistent-storage)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
