// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: storage/container_storage_interface/persistent-storage-csi-azure-file.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Azure File CSI Driver Operator\n---\n\n# Azure File CSI Driver Operator {#persistent-storage-csi-azure-file}\n\nYou can provision and manage Azure File storage in OpenShift Container Platform by using the Azure File Container Storage Interface (CSI) Driver Operator and driver, which provide dynamic volume provisioning and eliminate the need to pre-provision storage.\n\n**Additional resources**\n\n- [Understanding persistent storage](/openshift-docs-markdown/storage/understanding-persistent-storage#understanding-persistent-storage)\n- [Configuring CSI volumes](/openshift-docs-markdown/storage/container_storage_interface/persistent-storage-csi#persistent-storage-csi)\n- [Managing the default storage class](/openshift-docs-markdown/storage/container_storage_interface/persistent-storage-csi-sc-manage#persistent-storage-csi-sc-manage)\n- [Supported CSI drivers and features](/openshift-docs-markdown/storage/container_storage_interface/persistent-storage-csi#persistent-storage-csi-drivers-supported_persistent-storage-csi)\n\n**Additional resources**\n\n- [Persistent storage using Azure File](/openshift-docs-markdown/storage/persistent_storage/persistent-storage-azure-file#persistent-storage-using-azure-file)\n- [Access modes](/openshift-docs-markdown/storage/understanding-persistent-storage#pv-access-modes_understanding-persistent-storage)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
