// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: storage/container_storage_interface/persistent-storage-csi-sc-manage.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Managing the default storage class\n---\n\n# Managing the default storage class {#persistent-storage-csi-sc-manage}\n\n\\[role=\"\\_abstract\"\\] Many Container Storage Interface (CSI) operators can actively manage default storage classes, removing manual intervention needs and avoiding accidental deletion. Proper management ensures persistent volume claims provision correctly with the appropriate storage backend for your applications.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
