// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: storage/container_storage_interface/persistent-storage-csi-snapshots.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: CSI volume snapshots\n---\n\n# CSI volume snapshots {#persistent-storage-csi-snapshots}\n\nContainer Storage Interface (CSI) snapshots capture point-in-time copies for data protection and recovery. Snapshots enable restoring volumes to previous states or creating new volumes from existing data using `VolumeSnapshot`, `VolumeSnapshotContent`, and `VolumeSnapshotClass` objects.\n\n## Additional resources {#additional-resources_persistent-storage-csi-snapshots}\n\n- [Persistent volumes](/openshift-docs-markdown/storage/understanding-persistent-storage#persistent-volumes_understanding-persistent-storage)\n- [Kubernetes CSI Developer Documentation](https://kubernetes-csi.github.io/docs/drivers.html)\n- [Dynamically creating a volume snapshot](/openshift-docs-markdown/storage/container_storage_interface/persistent-storage-csi-snapshots#persistent-storage-csi-snapshots-create_persistent-storage-csi-snapshots)\n- [Statically creating a volume snapshot](/openshift-docs-markdown/storage/container_storage_interface/persistent-storage-csi-snapshots#persistent-storage-csi-snapshots-create-static_persistent-storage-csi-snapshots)\n- [Best practices for using VMware snapshots in the vSphere environment](https://kb.vmware.com/s/article/1025279)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
