// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: storage/container_storage_interface/persistent-storage-csi-group-snapshots.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: CSI volume group snapshots\n---\n\n# CSI volume group snapshots {#persistent-storage-csi-group-snapshots}\n\nVolume group snapshots capture point-in-time copies of multiple volumes simultaneously, gathering data across related volumes. This enables restoring multi-volume applications to a previous state or provisioning new volume sets with the same data for testing or development purposes.\n\n**Additional resources**\n\n- [Quiesce and Unquiesce Hooks](https://github.com/kubernetes/community/blob/master/wg-data-protection/data-protection-workflows-white-paper.md#quiesce-and-unquiesce-hooks)\n\n## Additional resources {#additional-resources_persistent-storage-csi-group-snapshots}\n\n- [Understanding persistent volumes](/storage/understanding-persistent-storage#persistent-volumes_understanding-persistent-storage)\n- [Enabling features using feature gates](/nodes/clusters/nodes-cluster-enabling-features#nodes-cluster-enabling-features)\n- [CSI volume snapshots](/storage/container_storage_interface/persistent-storage-csi-snapshots#persistent-storage-csi-snapshots)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
