// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/scheduling/descheduler.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Descheduler overview\n---\n\n# Descheduler overview {#nodes-descheduler-about}\n\nThe descheduler evicts running pods so that the default scheduler can place them on more suitable nodes.\n\n**Additional resources**\n\n- [Default scheduling](/nodes/scheduling/nodes-scheduler-about#nodes-scheduler-about)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
