// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/scheduling/nodes-scheduler-profiles.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Scheduling pods using a scheduler profile\n---\n\n# Scheduling pods using a scheduler profile {#nodes-scheduler-profiles}\n\nYou can use a scheduling profile to configure how the scheduler spreads pods across nodes to enforce low or high node utilization.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
