// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: nodes/scheduling/nodes-scheduler-taints-tolerations.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Controlling pod placement using node taints\n---\n\n# Controlling pod placement using node taints {#nodes-scheduler-taints-tolerations}\n\nYou can use taints and tolerations to allow the scheduler to control which pods should or should not be scheduled on a node.\n\n## Additional resources {#additional-resources_nodes-scheduler-taints-tolerations}\n\n- [Adding taints and tolerations](/openshift-docs-markdown/nodes/scheduling/nodes-scheduler-taints-tolerations#nodes-scheduler-taints-tolerations-adding_nodes-scheduler-taints-tolerations)\n- [Adding taints and tolerations using a compute machine set](/openshift-docs-markdown/nodes/scheduling/nodes-scheduler-taints-tolerations#nodes-scheduler-taints-tolerations-adding-machineset_nodes-scheduler-taints-tolerations)\n- [Creating project-wide node selectors](/openshift-docs-markdown/nodes/scheduling/nodes-scheduler-node-selectors#nodes-scheduler-node-selectors-project_nodes-scheduler-node-selectors)\n- [Pod placement of Operator workloads](/openshift-docs-markdown/operators/admin/olm-adding-operators-to-cluster#olm-pod-placement_olm-adding-operators-to-a-cluster)\n- [Rate limits on eviction (Kubernetes documentation)](https://kubernetes.io/docs/concepts/architecture/nodes/#rate-limits-on-eviction)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
