// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: ai_applications/mcp_server/mcp-server-overview.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Inspect clusters with MCP server for Red Hat OpenShift\n---\n\n# Inspect clusters with MCP server for Red Hat OpenShift {#mcp-server-overview}\n\nWhen problems occur on your OpenShift Container Platform cluster, you want to determine exactly what is happening, so that you can fix the issue as soon as possible. The MCP server for Red Hat OpenShift feature provides an AI tool to quickly and easily diagnose your OpenShift Container Platform cluster.\n\n**Additional resources**\n\n- [Revoke access to Custom Resources](/openshift-docs-markdown/ai_applications/mcp_server/mcp-server-overview#ai-app-mcp-server-revoke-cr-access_mcp-server-overview)\n- [Install the MCP server](/openshift-docs-markdown/ai_applications/mcp_server/mcp-server-overview#ai-app-mcp-server-install-helm_mcp-server-overview)\n\n**Additional resources**\n\n- [Install the MCP gateway (Red Hat Connectivity Link)](https://docs.redhat.com/en/documentation/red_hat_connectivity_link/1.4/html/install_the_mcp_gateway/index)\n\n**Additional resources**\n\n- [Microsoft Entra ID](https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-id)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
