// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: post_installation_configuration/converting-to-disconnected.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Converting a connected cluster to a disconnected cluster\n---\n\n# Converting a connected cluster to a disconnected cluster {#converting-to-disconnected}\n\nYou can convert a connected OpenShift Container Platform cluster to a disconnected cluster by mirroring required registry content and installation media for use without internet access.\n\nThere might be some scenarios where you need to convert your OpenShift Container Platform cluster from a connected cluster to a disconnected cluster.\n\nA disconnected cluster, also known as a restricted cluster, does not have an active connection to the internet. As such, you must mirror the contents of your registries and installation media. You can create this mirror registry on a host that can access both the internet and your closed network, or copy images to a device that you can move across network boundaries.\n\nFor information on how to convert your cluster, see the \"Converting a connected cluster to a disconnected cluster\" procedure in the Disconnected environments section.\n\n## Additional resources {#additional-resources_converting-to-disconnected}\n\n- [Converting a connected cluster to a disconnected cluster](/disconnected/connected-to-disconnected#converting-to-disconnected)\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
