// AUTO-GENERATED by `dogsbay convert` — do not edit.
// Source: cli_reference/opm/cli-opm-install.md
// Edit the source markdown and re-run `dogsbay convert` to regenerate.
export const prerender = true;
const body = "---\ntitle: Installing the opm CLI\n---\n\n# Installing the opm CLI {#cli-opm-install}\n\n**Additional resources**\n\n- See [Operator Framework packaging format](/operators/understanding/olm-packaging-format#olm-bundle-format_olm-packaging-format) for more information about the bundle format.\n\n## Additional resources {#opm-addtl-resources}\n\n- See [Managing custom catalogs](/operators/admin/olm-managing-custom-catalogs#olm-managing-custom-catalogs) for `opm` procedures including creating, updating, and pruning catalogs.\n";
export const GET = () =>
  new Response(body, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
